### ISSUE TITLE
ncWMS  Google Earth animation broken in 4.5.4

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/thredds#100]
@lesserwhirls , @dopplershift (not sure who is doing the ncWMS work), I just discovered that animations in Google Earth are no longer working.  Just a single frame appears, with no time slider. 

This TDS 4.5.4 kmz request DOES NOT display property in Google Earth (no time slider, no multiple frames):
<http://geoport-dev.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?LAYERS=temp&ELEVATION=-0.03125&TIME=2015-02-11T00:00:00.000Z,2015-02-12T00:00:00.000Z&TRANSPARENT=true&STYLES=boxfill%2Frainbow&CRS=EPSG%3A4326&COLORSCALERANGE=0%2C30&NUMCOLORBANDS=64&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=application/vnd.google-earth.kmz&SRS=EPSG%3A4326&BBOX=-72.199045333399,40.121831318462,-63.954587564625,46.562813950316&WIDTH=512&HEIGHT=400>
![2-13-2015 10-58-47 am](https://cloud.githubusercontent.com/assets/1872600/6190895/4a63a25c-b373-11e4-8bcc-65c4d5fe4655.png)

while in TDS 4.3, the same kmz request DOES display properly in Google Earth:
<http://geoport.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?LAYERS=temp&ELEVATION=-0.03125&TIME=2015-02-11T00:00:00.000Z,2015-02-12T00:00:00.000Z&TRANSPARENT=true&STYLES=boxfill%2Frainbow&CRS=EPSG%3A4326&COLORSCALERANGE=0%2C30&NUMCOLORBANDS=64&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=application/vnd.google-earth.kmz&SRS=EPSG%3A4326&BBOX=-72.199045333399,40.121831318462,-63.954587564625,46.562813950316&WIDTH=512&HEIGHT=400>
![2-13-2015 11-25-29 am](https://cloud.githubusercontent.com/assets/1872600/6190891/42ea1e70-b373-11e4-916d-b1d48d91d0f9.png)

This also seems to be a problem on your thredds 4.5.4 server, so I conclude it's not some local configuration problem on my end.   No time slider here with this kmz either:
<http://thredds.ucar.edu/thredds/wms/grib/NCEP/WW3/Global/Best?LAYERS=Significant_height_of_combined_wind_waves_and_swell_surface&ELEVATION=0&TIME=2015-02-13T00:00:00.000Z,2015-02-14T00:00:00.000Z&TRANSPARENT=true&STYLES=boxfill%2Frainbow&CRS=EPSG%3A4326&COLORSCALERANGE=0.1%2C5.34&NUMCOLORBANDS=20&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=application/vnd.google-earth.kmz&SRS=EPSG%3A4326&BBOX=-79.1578125,35.78125,-59.3578125,51.25&WIDTH=512&HEIGHT=400>

**Comment by rsignell-usgs** [comment]
Ping. @lesserwhirls , @dopplershift ?  My boss is bugging me...

**Comment by lesserwhirls** [comment]
Hmmm...it looks like the time information is not getting encoded in the
newer kml file, although the layers are all there in the kmz. I'll dig in
and see what I can find out, although I first need to figure out on which
side the kml is being generated (TDS or ncWms). I've CC'd Ethan just in
case he knows off the top of his head.

Sean

**Comment by rsignell-usgs** [comment]
It should be the ncwms, right @ethanrd ?

**Comment by ethanrd** [comment]
Yeah, I'm quite sure it is ncWMS not THREDDS.

**Comment by rsignell-usgs** [comment]
@lesserwhirls , are you looking into this?   My boss is dying to make an animation of a winter storm and can't until this is fixed.

**Comment by lesserwhirls** [comment]
Hi @rsignell-usgs - I am looking into it. I found where the tag is getting dropped, but I might need to ping Reading to see if they have a quick fix.

**Comment by lesserwhirls** [comment]
Hi @rsignell-usgs - this should be fixed in on the master branch of ncWMS here on git (https://github.com/Unidata/ncWMS). The master branch version (1.2.tds.4.6.0-SNAPSHOT) of ncWMS is what is being used in tds 4.6.

**Comment by rsignell-usgs** [comment]
@lesserwhirls , awesome!  Is there a way we could patch our 4.5 on our development server, or would you recommend trying 4.6?

**Comment by lesserwhirls** [comment]
@rsignell-usgs - do you guys serve GRIB? Do you have FMRCs?

**Comment by rsignell-usgs** [comment]
Yes, we have both GRIB and FMRCs.

**Comment by lesserwhirls** [comment]
A few weeks back I recommended 4.6 to a user, which spun up an internal discussion on when we should reccommend 4.3 vs 4.5 vs 4.6. Here is what @JohnLCaron had to say:

"AFAICT, NcML Aggregations are working <on 4.5>. So, unless they are using FMRC, I would recommend 4.5, and 4.6 for anyone serving GRIB. <snip> On FMRC, 4.3 is the safest solution, but not exactly solid."

Are you feeling adventurous? Trying 4.6 would be a great way for someone to really kick the tires. We've been using it on our development server, but it hardly sees any use :-( If not, I could apply a patch to our 4.5.5 branch for the simple GoogleEarth fix and you could use that. Just know that GRIB is known to be broken on 4.5 (and below, for that matter).

**Comment by cwardgar** [comment]
I'm getting some fixes together for THREDDS 4.5.5. Is there any reason we can't include this? It looks like we'd need to create a "uk.ac.rdg.resc:ncwms:1.2.tds.4.5.5" artifact.

**Comment by rsignell-usgs** [comment]
I hope that this can get included!

**Comment by lesserwhirls** [comment]
It will be included :-) w00t!

**Comment by rsignell-usgs** [comment]
excellent!

**Comment by JohnLCaron** [comment]
going to release this afternoon

**Comment by rsignell-usgs** [comment]
Yes, just confirmed the time slider is back in 4.5.5!

[This curl command](curl -L -o coawst_4_use_fmrc_coawst_4_use_best.ncd_temp.kmz 'http://geoport-dev.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?LAYERS=temp&ELEVATION=-0.03125&TIME=2015-03-01T00:00:00.000Z,2015-03-02T00:00:00.000Z,2015-03-03T00:00:00.000Z,2015-03-04T00:00:00.000Z,2015-03-05T00:00:00.000Z,2015-03-06T00:00:00.000Z,2015-03-07T00:00:00.000Z&TRANSPARENT=true&STYLES=boxfill%2Frainbow&CRS=EPSG%3A4326&COLORSCALERANGE=-0.5%2C30&NUMCOLORBANDS=64&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=application/vnd.google-earth.kmz&SRS=EPSG%3A4326&BBOX=-101.74989476701,11.88846735222873,-53.253084362468,48.463925392207926&WIDTH=512&HEIGHT=400')
 downloads a kmz animation from our 4.5.5 server and it comes up nicely in Google Earth:
![3-7-2015 6-55-22 am](https://cloud.githubusercontent.com/assets/1872600/6541348/197efde0-c498-11e4-8ee3-4ef5d0699a41.png)
