### ISSUE TITLE
Empty reply from ncss dataset page for NetCDF files

### ISSUE THREAD

**Issue by amarandon** [Unidata/thredds#1016]
I have an issue with [air quality NetCDF files from Copernicus](http://www.regional.atmosphere.copernicus.eu/?category=data_access).

When I try to get a NetCDF dataset page, I get an empty reply:

$ curl -D - 'http://172.24.0.3:8080/thredds/ncss/weather/archive/W_fr-meteofrance,MODEL,ENSEMBLE+FORECAST+SURFACE+NO2+0H24H_C_LFPW_20171219000000.nc/dataset.html'
HTTP/1.1 200 OK
Content-Length: 0
Date: Mon, 29 Jan 2018 09:23:06 GMT
Server: Apache

Here is the file, gzipped so that Github upload feature accepts it:

[W_fr-meteofrance,MODEL,ENSEMBLE+FORECAST+SURFACE+OLIVEPOLLEN+0H24H_C_LFPW_20180129000000.nc.gz](https://github.com/Unidata/thredds/files/1672920/W_fr-meteofrance.MODEL.ENSEMBLE.FORECAST.SURFACE.OLIVEPOLLEN.0H24H_C_LFPW_20180129000000.nc.gz)

I got this file from Copernicus by selecting these options:

![pollen-selection](https://user-images.githubusercontent.com/101934/35502775-590d0aae-04de-11e8-92b1-b0d4046f79b7.png)

Here is an other example which is causing the same issue:

[W_fr-meteofrance,MODEL,ENSEMBLE+FORECAST+SURFACE+NO2+0H24H_C_LFPW_20171219000000.nc.gz](https://github.com/Unidata/thredds/files/1672869/W_fr-meteofrance.MODEL.ENSEMBLE.FORECAST.SURFACE.NO2.0H24H_C_LFPW_20171219000000.nc.gz)

It works fine with other NetCDF files. Actually if I download the GRIB version of the same data and convert it to NetCDF using ecCodes' grib_to_netcdf, then I can get the dataset page from thredds. So something must be weird with NetCDF files produced by Copernicus.

**Comment by cofinoa** [comment]
@amarandon

The problem is that the time variable doesn't have the right units to be identified as a Time coordinate, needed by the ncss service 

You should contact to the data provider and ask to fix that. BTW, the metadata should be improved and be more explicit to avoid ambiguities and interpretations. 

Meanwhile and to check that the ncss service it's working you can add a ncml file with this content:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2" 
     location="W_fr-meteofrance,MODEL,ENSEMBLE+FORECAST+SURFACE+OLIVEPOLLEN+0H24H_C_LFPW_20180129000000.nc">
  <variable name="time">
    <attribute name="units" value="hours since 2018-01-29T00:00:00Z" />
  </variable>
</netcdf>
```

**Comment by amarandon** [comment]
@cofinoa Thanks a lot for your quick reply! I works with the ncml file you provided. I guess I can close this issue then.

I can see that the file only contains *hours* as unit of the time variable. I understand now that it should also specify a start time, as in your example.

When contacting the data provider, do you know if there is an authoritative reference regarding unit formats that I should point them to? Since their files are usable with tools like ncview or Panoply, I anticipate "resistance" ;)

**Comment by cofinoa** [comment]
Dear @amarandon

Please point to them to the C3S [CDM: Common data model specification - v1.0](https://software.ecmwf.int/wiki/display/COPSRV/CDM%3A+Common+data+model+specification+-+v1.0#CDM:Commondatamodelspecification-v1.0-4.3TimeCoordinates)

That specification is based on the CF1.6. 

P.S: You can also pass them my profile to contact me: @cofinoa

**Comment by amarandon** [comment]
We created a ticket for Copernicus, referring this issue

**Comment by amarandon** [comment]
For the record, we received a reply from the ECMWF saying that they acknowledge the issue and intend to fix it in the future. However as they don't guarantee CF-compliance, they can't tell when it will be done.
