### ISSUE TITLE
Can I get just vertical section plot png instead with axis ?

### ISSUE THREAD

**Issue by Siddeshi** [Unidata/thredds#1018]
Hi there,

I need vertical section png file without chart (without axis) to render it directly as an image. Can you please help me how can I achieve in **thredds** as it is generating chart for me?

This is the url i'm trying in my local:

**`http://localhost:8080/thredds/wms/testAll/ModelTemperature.nc?REQUEST=GetVerticalSection&LAYER=TEMP&CRS=CRS:84&ELEVATION=-145&TIME=2009-12-29T12:00:00.0000Z&LINESTRING=65.06689453125%2014.340454101563,75.20556640625%200.6182861328125&FORMAT=image/png&COLORSCALERANGE=-50,50&NUMCOLORBANDS=20&VERSION=1.1.1&PALETTE=ferret&LOGSCALE=false`**

Attaching the image file which is getting generate.

![potential temperature](https://user-images.githubusercontent.com/10955336/35523776-9fbadbae-0545-11e8-9327-c25a58f93858.png)

But image which I want is as below.

![render](https://user-images.githubusercontent.com/10955336/35523883-e51be530-0545-11e8-90d3-8fef61611fd2.png)

**Comment by lesserwhirls** [comment]
Greetings @Siddeshi -  unfortunately, I do not believe there is a way to ask the wms server to return just the 2D color image.

**Comment by Siddeshi** [comment]
Hi @lesserwhirls thanks for the information, I wanted just 2D image, @guygriffiths suggested me to use thredds APIs to get the subset of the data and use some other wms server which provides 2D images, so that am trying to debug thredds code I found that it uses [edal-java](https://github.com/Reading-eScience-Centre/edal-java).
[The log which is getting generated like this](https://drive.google.com/file/d/1anEOWH3XmKn0QfDYWtLYZdwFByuE6JDb/view?usp=sharing).

*`DEBUG - thredds.servlet.DatasetHandler - DatasetHandler wants testAll/ModelTemperature.nc
DEBUG - thredds.catalog.InvDatasetScan - translatePathToLocation(): url dsPath= testAll/ModelTemperature.nc to dataset dsPath=/public/testdata/ModelTemperature.nc
DEBUG - ucar.nc2.NetcdfFile - Using IOSP ucar.nc2.iosp.netcdf3.N3raf
DEBUG - uk.ac.rdg.resc.edal.cdm.CdmUtils - Creating coordinate system objects
DEBUG - uk.ac.rdg.resc.ncwms.controller.AbstractWmsController - Got 2 control points
DEBUG - uk.ac.rdg.resc.edal.util.Utils - Transforming 500 points from CRS:WGS84 to WGS84(DD)
DEBUG - uk.ac.rdg.resc.edal.util.Utils - Transforming 1000 points from CRS:WGS84 to WGS84(DD)
DEBUG - uk.ac.rdg.resc.ncwms.controller.AbstractWmsController - With 1000 transect points, we'll sample 74 grid points
DEBUG - uk.ac.rdg.resc.ncwms.controller.AbstractWmsController - Using transect consisting of 500 points
DEBUG - uk.ac.rdg.resc.edal.cdm.PixelMap - Creating PixelMap: Source CRS: WGS84(DD), Target CRS: CRS:WGS84
DEBUG - uk.ac.rdg.resc.edal.cdm.PixelMap - SourceGrid class: class uk.ac.rdg.resc.edal.coverage.grid.impl.RectilinearGridImpl, targetDomain class: class uk.ac.rdg.resc.edal.coverage.domain.impl.HorizontalDomain`*

I wanted some clarification; I went through [edal-java](https://github.com/Reading-eScience-Centre/edal-java) I could see the class *CdmUtils* which is implemented in the package *uk.ac.rdg.resc.edal.util.cdm*, but in the log it is showing different package *uk.ac.rdg.resc.edal.cdm.CdmUtils*. 

1. My question is, does thredds use the external jar (edal-cdm) or customising as per the requirement ?
2. Is it possible to use thredds for reading subset of data from necdf file and invoke some other wms server API for 2D image? How can I achieve this ?

**Comment by guygriffiths** [comment]
@Siddeshi - To clarify, you could use THREDDS to get a subset of the data, but you will not be able to plot it using a WMS server - that's not what WMS is designed for.  I suggested that you use another package, by which I meant e.g. ncview, python, MATLAB etc.

I guess you are using a 4.x version of THREDDS?  That depends on an older version of EDAL, hence the diffference package.

**Comment by Siddeshi** [comment]
@guygriffiths thank you so much for the clarification. Sure will look into other packages.
