### ISSUE TITLE
Missing servlet configuration for NetCDF Subset Service 

### ISSUE THREAD

**Issue by cofinoa** [Unidata/thredds#102]
At least for, TDS 4.3.22 and 4.5.4 war files the any reference to ncss configuratio entries in WEB-INF/web.xml is missing and also the ncss-servlet.xml file are missing. 

Also this configuration is not in the the GitHub repositories for the previous branches and the 4.6.0. 

Antonio

**Comment by JohnLCaron** [comment]
Hi Antonio:

We have switched to using annotated spring controllers, so we dont need anything in the web.xml, nor do we need the ncss-servlet.xml anymore, because of the annotation.

John
