### ISSUE TITLE
Dap4 requests returns 404 on default catalog (v5.0.0)

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#1020]
When making a request for DAP4 using the default catalogs that come with TDS 5, I am getting 404's. For example:

http://localhost:8080/thredds/dap4/test/testData.nc.dmr.xml

returns:

~~~
HTTP Status 404 – Not Found
Type Status Report

Message <Error httpcode="404"> <Message>dap4.core.util.DapException: Not found:
test/testData.nc at thredds.server.dap4.Dap4Controller.getResourcePath(Dap4Controller.java:158) 
at dap4.servlet.DapController.doDMR(DapController.java:305) 
at dap4.servlet.DapController.handleRequest(DapController.java:230) 
at thredds.server.dap4.Dap4Controller.handleRequest(Dap4Controller.java:73) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at 
<snip>
java.lang.Thread.run(Thread.java:748) </Message> <Context>http://localhost:8080/thredds/dap4/test/testData.nc.dmr.xml</Context>

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
~~~

The issue is that the `getResourcePath(DapRequest drq, String location)` method in `thredds.server.dap4.Dap4Controller` is finds that

`String prefix = drq.getResourceRoot()` 

is not null, and the path is determined using `realpath = DapUtil.canonjoin(prefix, location)`. The value of `realpath` gets set to 

`/Users/sarms/dev/unidata/repos/thredds/50/tds/build/libs/exploded/tds-5.0.0-SNAPSHOT.war/WEB-INF/test/testData.nc`

which isn't correct. The actual location is properly obtained using `realpath = TdsRequestedDataset.getLocationFromRequestPath(location)`, which sets `realpath` as:

`/Users/sarms/dev/unidata/content/5.0/thredds/public/testdata/testData.nc`

`TdsRequestedDataset.getLocationFromRequestPath(location)` is used in the current code if `prefix` is null, but in this case, `prefix` isn't null so the wrong value for `realpath` is set.

**Comment by DennisHeimbigner** [comment]
Apparently the reason I was doing this is that when I run TestServlet,
which uses mocking,  under Intellij, 
 TdsRequestedDataset.getLocationFromRequestPath(location)
returns null. Looks like I need some kind of better way to tell is I am using Mocking.

**Comment by DennisHeimbigner** [comment]
Turns out that under mocking, TdsRequestedDataset.datasetManager is null.
I suspect this is a Spring wiring issue.
