### ISSUE TITLE
The NetCdf Subset Service has 404 problems when restricted datests are accessed

### ISSUE THREAD

**Issue by cofinoa** [Unidata/thredds#103]
Dear all, 

I'm using TDS version 4.3.22 and I have configured NCSS servlet to serve datasets. The servlet is working, but when I'm tryn to access restricte datasets the servlet reports a 404 HTTP error. 

I think it's a issue with the restricted acces configuration, because if I access to same dataset using the OpenDAP service the TDS challenges to me with the Basic authentication and after login I can access (partially) to the restricted dataset using the ncss. I said partially because only the web form is shown. The css and images files are not loaded and the requests are not working. 

Regards

Antonio

**Comment by lesserwhirls** [comment]
Please see Unidata/thredds#106
