### ISSUE TITLE
cannot click on Godiva2 map in TDS 4.6.11

### ISSUE THREAD

**Issue by pacioos** [Unidata/thredds#1033]
After upgrading to TDS 4.6.11, I noticed that clicking on the map in Godiva2 fails to produce a pop-up with the data value at the clicked location. It is stuck with the message "loading..." and the browser console shows the following error message:

`TypeError: OpenLayers.loadURL is not a function
godiva2.js:499:9`

For a working example, here is one of our wave forecast FMRC's around Oahu:

http://oos.soest.hawaii.edu/thredds/catalog/hioos/model/wav/swan/oahu/catalog.html?dataset=hioos/model/wav/swan/oahu/SWAN_Oahu_Regional_Wave_Model_best.ncd

http://oos.soest.hawaii.edu/thredds/godiva2/godiva2.html?server=http://oos.soest.hawaii.edu/thredds/wms/hioos/model/wav/swan/oahu/SWAN_Oahu_Regional_Wave_Model_best.ncd

Thanks,
John Maurer
Data System Engineer
Pacific Islands Ocean Observing System (PacIOOS)
University of Hawaii at Manoa

**Comment by lesserwhirls** [comment]
Greetings @pacioos!

We have this fixed in master. You can patch `godiva.js` or wait until the next 4.6 release, which might be a few weeks or more. For more info, see:

https://www.unidata.ucar.edu/mailing_lists/archives/thredds/2018/msg00010.html

and

Unidata/thredds#1014

Thanks for the report!

**Comment by pacioos** [comment]
Excellent, thanks @lesserwhirls! I patched `godiva.js` and the map clicking works again.
Cheers,
John
