### ISSUE TITLE
Multiples links for the same dataset in catalog?

### ISSUE THREAD

**Issue by marceloandrioni** [Unidata/thredds#1039]
Hello, I was wandering if it is possible to create multiples links for the same dataset in thredds. That is, I am asking if I can create a dataset (FMRC,aggregation,etc) with the usual code in catalog.xml and reference this same dataset with a link inside other dataset. I usually create sub-catalog files by institutions (e.g. catalog_noaa.xml, catalog_ecmwf.xml) and call then in catalog.xml. I also would like to create sub-catalog files by location (e.g. catalog_atlantic.xml, catalog_pacific.xml) without having to re-create the datasets already created in catalog_<institution>.xml. Should I just use a catalogRef element like if I was referencing a remote dataset?
Thank you and sorry if this was asked before, but I couldn't find in the mailing list or previous issues.

**Comment by lesserwhirls** [comment]
Greetings @marceloandrioni! Unfortunately, I don't think there is currently a good way of doing this. Certainly, one way would be to use the remote catalog service. Another way would be to write out individual dataset configuration in individual catalogs, and reference those individual catalogs using `catalogRef` elements.

**Comment by marceloandrioni** [comment]
Thank you for the suggestions @lesserwhirls and sorry for taking so long to answer, but I was out of the office. Setting allowRemote=true in threddsConfig.xml and creating the link as
`  <catalogRef xlink:title="Link to local dataset" xlink:href="http://myserver:8080/thredds/catalog/mercator/catalog.xml" name=""/>
`
solved my problem. I will be closing this issue now. Thank you very much.
