### ISSUE TITLE
Specifying more than one convention in FMRC

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/thredds#104]
I'm trying to specify more than one convention in an FMRC.

Inside the `<featureCollection>` tag in the catalog `NcML`, I've got:
```
    <attribute name="Conventions" value="CF-1.4, SGRID-0.1"/>
```
but when I look at the FMRC:
http://geoport.whoi.edu/thredds/dodsC/coawst_4/use/fmrc/coawst_4_use_best.ncd.html
the result is: `Conventions: CF-1.4, _Coordinates`.

This is the case on TDS 4.3.21 and on 4.5.4.

I also notice that on aggregations on motherlode:
http://thredds.ucar.edu/thredds/dodsC/satellite/3.9/WEST-CONUS_4km.html
we have `Conventions: _Coordinates`. 

It would appear that FMRC is selecting only the 1st specified convention and then adding `_Coordinates`.

How can I modify my NcML so that the resulting conventions are `Conventions: CF-1.4, SGRID-0.1` ?

**Comment by JohnLCaron** [comment]
Ill try to fix this in 4.5.5

**Comment by rsignell-usgs** [comment]
@JohnLCaron , oh that would be so great!    :pray:

**Comment by JohnLCaron** [comment]
Sorry couldnt get it done. will try again later.

**Comment by lesserwhirls** [comment]
@JohnLCaron - were you able to get this in the 4.6.1 release, or is this still an issue?

**Comment by JohnLCaron** [comment]
still an issue - probably a jira ticket alreaady

**Comment by lesserwhirls** [comment]
Ok, there is a Jira ticket:

https://bugtracking.unidata.ucar.edu/browse/TDS-631

I will close this issue as it's in Jira.
