### ISSUE TITLE
thredds.crawl.Util package missing in 4.6.0

### ISSUE THREAD

**Issue by vegasm** [Unidata/thredds#105]
The class TestTDSdataset.java in ui expects to get some Util functionalities from  thredds.crawl.Util; but this package does not exist. How to fix this?

**Comment by JohnLCaron** [comment]
should be fixed now, thanks for reporting.

**Comment by vegasm** [comment]
It works! Thank you John

De: John Caron [mailto:notifications@github.com]
Enviado el: lunes, 16 de marzo de 2015 17:50
Para: Unidata/thredds
CC: Vega Saldarriaga, Manuel
Asunto: Re: [thredds] thredds.crawl.Util package missing in 4.6.0 (#105)

should be fixed now, thanks for reporting.
