### ISSUE TITLE
Possible FPE for valid_min, valid_max of scaled data

### ISSUE THREAD

**Issue by msdsoftware** [Unidata/thredds#1068]
A user sent me a sample dataset where testing whether data values were good/bad was not working correctly because FPE was resulting in values that equalled the supposed `valid_max` being reported as invalid because the calculated `valid_max` was incorrect by a minuscule amount.

The var is described as
```
byte qa_value(time=1, scanline=2929, ground_pixel=450);
  :units = "1";
  :scale_factor = 0.01f; // float
  :add_offset = 0.0f; // float
  :valid_min = 0UB; // byte
  :valid_max = 100UB; // byte
  :long_name = "data quality value";
  :coordinates = "longitude latitude";
  :_FillValue = -1UB; // byte
  :_Unsigned = "true";
```

After opening the dataset in enhanced mode, calling `VariableDS.getValidMax()` on this variable returns a value of 0.9999999776482582.

But when extracting values from the array, there are values that are reported as being == 1.0, and calling either `VariableDS.isInvalidData(1.0)` or `VariableDS.isMissing(1.0)` returns `true`.

**Comment by lesserwhirls** [comment]
The fix is on 5.0, but I think @msdsoftware is on 4.6.x but looking at 5 (is that understanding correct?)

**Comment by msdsoftware** [comment]
Yes, I am still using 4.6.x, @lesserwhirls. Started looking at switching to 5.0 last week but then backed off after finding that changes to catalog handling were significant. I may take another whack at it later this week.

**Comment by msdsoftware** [comment]
@lesserwhirls, I managed to get my code to compile and link against 5.0.0, but I am encountering some problems obtaining listings from remote catalogs (i.e., branches reported as having nothing in them), so it looks like I will stick with 4.6 for a while longer.

I have a kludge in place in my own code to deal with the scaled valid_max problem, so there's no crying need on my end to apply the #1070 fix to 4.6.

**Comment by cwardgar** [comment]
@msdsoftware Thanks for the update. It would have been tedious to apply #1070 to 4.6, as it builds atop #1047, which is 5.0-specific.

**Comment by msdsoftware** [comment]
@cwardgar, I may have figured out the 5.0 problem reading catalogs. It appears that I need to call `DatasetsNode.getDatasetsLogical()` rather than just `DatasetsNode.getDatasets()`

**Comment by cwardgar** [comment]
That's good news! Frankly, I haven't had a chance to look into the new Catalog code much (it was one of John's last contributions before he left), so I can't provide any guidance there. We'd love to know the steps you end up taking to get it working though.
