### ISSUE TITLE
writeEnumData raises NPE with empty section.getStride()

### ISSUE THREAD

**Issue by r0perice** [Unidata/thredds#1072]
Hello, 

I have a dataset of netcdf4 files and I try to read/write this dataset using netcdf library version **4.6.11**

Reading the files works but writing fails on 

> Nc4Iosp::writeEnumData()

This is an extract of my test

```java
NetcdfFile ncFile = NetcdfFile.open(inputFile.getAbsolutePath());
final Nc4Chunking chunker = Nc4ChunkingStrategy.factory(Strategy.standard, 0, true);
final FileWriter2 fw = new FileWriter2(ncFile, outputFileName, NetcdfFileWriter.Version.netcdf4, chunker);
    fw.write();
```
The problem comes from Nc4Iosp::writeEnumData(). 
Line 2946 
```java
SizeT[] stride = convertSizeT(section.getStride());
```
the 'stride' reference is null. This is because method 'convertSizeT' does:

```java
if (from.length == 0) return null;
```

And just after in writeEnumData their is a loop trying to use 'stride.length' (which in my case is null)
```java
for(int i = 0; i < stride.length; i++)
```

I will try to provide a fix for this problem.

Regards,
Robin

PS: Unfortunately I cannot provide you the dataset I'm using.

**Comment by cwardgar** [comment]
Can you provide a similar dataset that demonstrates the bug?

**Comment by r0perice** [comment]
Sorry but I'm not authorized to provide my dataset. I don't have the time to search or build a similar dataset that provokes the NPE.
