### ISSUE TITLE
Broken NCSS on HRRR

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/thredds#1083]
http://thredds-jumbo.unidata.ucar.edu/thredds/catalog/grib/HRRR/CONUS_3km/surface/catalog.html?dataset=grib/HRRR/CONUS_3km/surface/Best

The NCSS link doesn't work.  It's missing the "grid".
Instead of:
http://thredds-jumbo.unidata.ucar.edu/thredds/ncss/grib/HRRR/CONUS_3km/surface/Best/dataset.html

It should be
http://thredds-jumbo.unidata.ucar.edu/thredds/ncss/grid/grib/HRRR/CONUS_3km/surface/Best/dataset.html

**Comment by lesserwhirls** [comment]
Oops - server config error. We had the service elements still set up to use `/thredds/ncss/`, but it should have been `/thredds/ncss/grid/`. I updated the [config](https://github.com/Unidata/TdsConfig/pull/50/files) to use the 5.0 default services feature, and now it works. Thanks for the report!
