### ISSUE TITLE
Javadoc API online

### ISSUE THREAD

**Issue by msdsoftware** [Unidata/thredds#1105]
The Unidata website documentation page for netCDF-Java at https://www.unidata.ucar.edu/software/thredds/current/netcdf-java/documentation.htm
has links to Javadoc APIs for NJ 4.6 (stable), 4.5 (previous) and (OMG!!!) 4.3 (previous).

It really seems that that the 4.5 and most def the 4.3 links could be dropped. But more importantly (at least for my needs), there should be a 5.0 (beta) Javadoc link added.

**Comment by lesserwhirls** [comment]
Greetings @msdsoftware - we are in the process of re-doing our docs, and how they are served. The Javadocs for 5.0 can be found at:

https://docs.unidata.ucar.edu/thredds/5.0.0-SNAPSHOT/javadoc/index.html

Cheers!
