### ISSUE TITLE
Invalid interpretation of GRIB2 header

### ISSUE THREAD

**Issue by linsroel** [Unidata/thredds#112]
There appears to be a problem with the interpretation of specific GRIB2 time delta headers in THREDDS. The problem occurs with regard to the NCEP GEFS dataset (downloaded form http://nomads.ncep.noaa.gov/pub/data/nccf/com/gens/prod/gefs.20150326/00/pgrb2/). Until time step +252 things go correctly. From +258 onward, the GRIB2 headers change, causing THREDDS to come up with wrong variable names for some parameters. For example the maximum temperature shows up (via OpenDAP) as Maximum_temperature_height_above_ground_36_Hour_Maximum instead of Maximum_temperature_height_above_ground_6_Hour_Maximum.

A grib_compare of the +252 and +258 GRIB2 files yields the following relevant differences (ie. for the TMAX parameter):
long [indicatorOfUnitOfTimeRange]: [1] != [11]
long [forecastTime]: [246] != [42]
long [lengthOfTimeRange]: [6] != [1]

With indicatorOfUnitOfTimeRange 1 and lengthOfTimeRange 6, the time delta is correctly interpreted as 6 hours. With indicatorOfUnitOfTimeRange 11 and lengthOfTimeRange 1 the time delta is interpreted as 36 hours, which is incorrect. This also messes up the NcML Aggregation for the entire dataset.

Is there a way to work around this?

Server version: 
opendap/3.7 
THREDDS Data Server Version: 4.3.16
Build Date: 20130319.1353

**Comment by JohnLCaron** [comment]
GRIB2 processing has been rewritten twice since version 4.3.16.
Could you try the above issues with 4,6.0, which is being released as we speak.
Thanks.

**Comment by linsroel** [comment]
Thank you for your feedback John. Good to hear that GRIB2 processing has been improved. Upgrading the TDS is currently not really an option for us as we would also have to upgrade our Java and Tomcat versions. For now we have reverted to converting the Grib2 files to netcdf and using those. As we will not be able to test whether the problem persists in a more recent Thredds version on a short notice, I think this issue can be closed.
