### ISSUE TITLE
Valid range on unsigned int types

### ISSUE THREAD

**Issue by msdsoftware** [Unidata/thredds#1139]
A Panoply user has run into a problem that seems to be the result of Panoply now using NJ 5. (Note: Panoply is acquiring the dataset in enhanced mode.) The data var looks like

```
ushort TB(time=732, y=968, x=816);
  :_FillValue = 0US; // ushort
  :missing_value = 60000US; // ushort
  :valid_range = 5000US, 35000US; // ushort
  :scale_factor = 0.01f; // float
  :add_offset = 0.0f; // float
```

The problem is that all of the data values are being reported as NaN, even though an eyeball of the ncdump shows most values are good (i.e., not fill). The cause of this seems to that the valid max is taken from the attribute and converted to 35000 - 65536 = -30536. Calling getValidMin and getValidMax on the VariableDS gives

valid min 49.99999888241291, max -305.3599931746721

This is happening with 5.0 both beta-2 and the latest snapshot, so the work done by @cwardgar in the June 2 commit doesn't seem to have caused/fixed the issue.

**Comment by msdsoftware** [comment]
Possibly this actually has been fixed. When I was looking into this an hour ago, I could swear the latest snapshot was giving me the bad valid mx. But after poking at things a bit, I started getting the expected/resulted value. Trying again after downloading and compiling a fresh snapshot, the result is good. I'll have to spend more time poking at this tomorrow to see what the hey was going on.

**Comment by msdsoftware** [comment]
Closing this. It appears @cwardgar 's commit of June 2 did fix the problem, and I must have initially been linking against the wrong jar when trying to test a recent snapshot.

**Comment by cwardgar** [comment]
@msdsoftware Glad to hear it!
