### ISSUE TITLE
dap4 500 on thredds-dev

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#1143]
We are getting `500`s on our grib collections on thredds-dev, which is using the latest version 5 snapshot. The issue is that, on this line:

https://github.com/Unidata/thredds/blob/e7588da3175d6e4507fb1cef5a6a16744e8e51e7/dap4/d4cdm/src/main/java/dap4/cdm/dsp/CDMDSP.java#L1031-L1034

The variable `decl` is a null dimension (not shared?), and comes from the `cdmmap` from the CDMNode/DapNode map `nodemap`. When calling `getShortName()`, we get a `null` and throw an NPE on the comparison.

Not sure what the right thing to do here would be. Naively I'd think check for the null and, if null, return false?

**Comment by lesserwhirls** [comment]
Here is an example:

https://thredds-dev.unidata.ucar.edu/thredds/catalog/grib/NCEP/NAM/CONUS_80km/latest.html?dataset=grib/NCEP/NAM/CONUS_80km/NAM_CONUS_80km_20180907_1200.grib1

**Comment by DennisHeimbigner** [comment]
I am unable to access thredds-dev; is it down?

**Comment by lesserwhirls** [comment]
I think I had it locked in my debugger when you tried. It should be good again.

**Comment by DennisHeimbigner** [comment]
I will add the null test, but since I cannot debug this in-situ, I have no confidence
that that adding the null check is anything more than a band-aid.
My guess is that the problem will just crop up somewhere else in the code
and I will end up playing whack-a-mole.

**Comment by DennisHeimbigner** [comment]
fixed by pull request https://github.com/Unidata/thredds/pull/1146

**Comment by lesserwhirls** [comment]
A simple check on thredds-dev looks good!

https://thredds-dev.unidata.ucar.edu/thredds/dap4/grib/NCEP/GFS/Global_0p5deg/GFS_Global_0p5deg_20180910_0600.grib2.dmr.xml
