### ISSUE TITLE
TDS can't serve *.png files in public folder

### ISSUE THREAD

**Issue by shane-axiom** [Unidata/thredds#115]
In a change from previous versions (4.3.x), TDS seems to have lost the ability to serve files in the `public` content directory other than css, gif, and jpg files. The description in the docs doesn't mention this limitation.

http://www.unidata.ucar.edu/software/thredds/current/tds/reference/ThreddsConfigXMLFile.html#Server_Description

> NOTE: The best way to use your own logo is to put it in the ${tomcat_home}/content/thredds/public/ directory, and specify it in serverInformation as /thredds/<name>

This seems to be the code restricting the extensions via a spring RequestMapping pattern.

https://github.com/Unidata/thredds/blob/4.6.0/tds/src/main/java/thredds/server/root/RootController.java#L70

It also seems that subdirectories of `public` can't be used anymore either (e.g. `images` subdirectory). These two changes bit us when upgrading to 4.6.0 from 4.3.20 as we used to serve a PNG logo image from `public/images/header.png`.

**Comment by JohnLCaron** [comment]
Hi Shane:

Thanks for reporting that, we will get it fixed. Are png files the only
ones you need to serve from there?

John

**Comment by shane-axiom** [comment]
In an ideal world we could serve any file type (and subdirectories) from the public dir, either by explicitly including "public" in the path or by looking any unmapped URL in the public folder. But yes, for now we could get by with just *.png :)

**Comment by JohnLCaron** [comment]
ok, we are in some Spring mapping confusion but we will get it sorted out.

**Comment by lesserwhirls** [comment]
@JohnLCaron - did we get this fixed? If not, I'll add a ticket to jira.

**Comment by JohnLCaron** [comment]
i think its fixed

**Comment by lesserwhirls** [comment]
Ok, I'll close this issue for now. @shane-axiom - if the problem still exists in our latest release, can you let us know? Thanks!

**Comment by lesserwhirls** [comment]
Never mind...I'll just tag this as needs testing but keep it open...still trying to get a decent github workflow going here...

**Comment by shane-axiom** [comment]
Tested 4.6.2, was able to serve a .png image in the public folder. Closing, thanks.
