### ISSUE TITLE
Upgrading to 4.5 document not accessible from main TDS page

### ISSUE THREAD

**Issue by shane-axiom** [Unidata/thredds#117]
The [Upgrading to TDS 4.5 document](http://www.unidata.ucar.edu/software/thredds/current/tds/UpgradingTo4.5.html) doesn't seem to be available from the [current TDS page](http://www.unidata.ucar.edu/software/thredds/current/tds/TDS.html), which just includes the [Upgrading to TDS 4.6 document](http://www.unidata.ucar.edu/software/thredds/current/tds/UpgradingTo4.6.html). The current stable -> dev upgrade path includes the 4.5 changes. In particular, the breaking NCSS path changes (removal of `/grid`) aren't mentioned in the 4.6 upgrade doc, and old 4.3.x style NCSS URLs which include `/grid` result in blank 200 responses from TDS 4.6 which is confusing. Please link the 4.5 upgrade document from the main page, or alternatively link it from the 4.6 upgrade document.

**Comment by JohnLCaron** [comment]
How much would it mess with you if we restored the ncss/grid URL in 4.6.1 ?

**Comment by shane-axiom** [comment]
Not at all as long as the `grid`-less version still works!

**Comment by JohnLCaron** [comment]
it will work in 4.6 but we will remove it in 5.0

**Comment by kwilcox** [comment]
@JohnLCaron Bare with me here...

* < 4.5 `/ncss/grid`
* 4.5, 4.6 `/ncss`
* 4.6.1 `/ncss` and `/ncss/grid`
* >= 5.0 `/ncss`

Is this correct?

**Comment by JohnLCaron** [comment]
Hi Kyle:

We are going back to /ncss/grid as the standard. So we have reenabled
/ncss/grid in 4.6.1, in the hopes that people who have skipped 4.5 and
4.6.0 wont have anything to do. Its possible we can map /ncss to /ncss/grid
in 5.0 also, but not sure.

so everything as above except

   - >= 5.0 /ncss/grid

John
