### ISSUE TITLE
HDF5 readHeapString error

### ISSUE THREAD

**Issue by msdsoftware** [Unidata/thredds#1204]
I'm having trouble using NJ to open an HDF dataset, as the `HDheader` class is throwing an exception "Cant find Heap Object,heapId= nelems=0 heapAddress=0 index=0". Can someone explain what this might mean? The file in question was, I'm told, created using IDL. There's no trouble opening it up using HDFView.

I've queried the person who provided the file to see it's okay to share with NJ developers, in case it's needed in order to figure out the issue.

**Comment by DennisHeimbigner** [comment]
Yes, we will probably need to see the file. But first, can you find out what library
was used by IDL to create the file? Was it created with IDL+netcdf-c library or
was it created with IDL+libhdf5?

**Comment by DennisHeimbigner** [comment]
Ok, I looked at the file you sent and it was created using netcdf-c library.
The_NCProperties value is "version=1|netcdflibversion=4.4.1.1|hdf5libversion=1.8.18"
It appears to be readable with the ncdump from the netcdf-c library.

**Comment by DennisHeimbigner** [comment]
I notice that the superblock version is 2, which is pretty uncommon. It is possible
(probable) that the H5Iosp we only lightly tested for this case.

**Comment by msdsoftware** [comment]
@DennisHeimbigner, This problem may be something in IDL itself. The user who provided the sample HDF5 file reported Wednesday that:

> Engineers in Harris discovered that there is a problem on IDL library that results in an invalid HDF5 file (the header message blocks do not adhere to the 8-byte padding requirement).
> 
> The error happens only in the following condition: when one of the attribute is an empty string, that of course is really uncommon.
> 
> Harris has already fixed the problem and the fix will be included in next release IDL 8.7.2.

I take it that "Harris" = Harris Geospatial.

**Comment by DennisHeimbigner** [comment]
That would explain the problem except as near as I can tell, there is no 
attribute with an empty string. Of course it is possible that their error can 
occur in other circumstances.

**Comment by lesserwhirls** [comment]
Any word back? If not, I'll close out this particular issue. Thanks!

**Comment by DennisHeimbigner** [comment]
I have heard nothing. Give a day or two to see if we get a response to your comment.

**Comment by msdsoftware** [comment]
@lesserwhirls, @DennisHeimbigner, Haven't heard a peep from the user who originally queried about this.
