### ISSUE TITLE
NcISO is not computing the ISO fileIdentifier correctly from the id and naming_authority

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/thredds#121]
According to the [ACDD Mappings](http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery_%28ACDD%29_Mappings), the ISO 19115-2 `fileIdentifier` is supposed to be computed from the combination of the netcdf attributes `id` and `naming_authority`. 

Yet if we look at a [dataset where both `naming_authority` and `id` are specified](http://oos.soest.hawaii.edu/thredds/catalog/hioos/roms_forec/hiog/catalog.html?dataset=roms_hiog_forecast/ROMS_Oahu_Regional_Ocean_Model_best.ncd), we find that currently this is not working:

While the [OPeNDAP Dataset Access Form](http://oos.soest.hawaii.edu/thredds/dodsC/hioos/roms_forec/hiog/ROMS_Oahu_Regional_Ocean_Model_best.ncd.html) specifies:

```
id: roms_hiog_forecast
naming_authority: org.pacioos
```

when we look at the [ISO record](http://oos.soest.hawaii.edu/thredds/iso/hioos/roms_forec/hiog/ROMS_Oahu_Regional_Ocean_Model_best.ncd?catalog=http%3A%2F%2Foos.soest.hawaii.edu%2Fthredds%2Fcatalog%2Fhioos%2Froms_forec%2Fhiog%2Fcatalog.html&dataset=roms_hiog_forecast%2FROMS_Oahu_Regional_Ocean_Model_best.ncd) we see

```
  <gmd:fileIdentifier>
      <gco:CharacterString>roms_hiog_forecast/ROMS_Oahu_Regional_Ocean_Model_best.ncd</gco:CharacterString>
   </gmd:fileIdentifier>
```

which is just the THREDDS path, with no naming authority information.

It looks like there are two problems with the [UnidataDD2MI.xsl](https://github.com/Unidata/thredds/blob/5be05b196a3efb7a3772460ccbe80cfa964f64ff/tds/src/main/webapp/WEB-INF/classes/resources/xsl/nciso/UnidataDD2MI.xsl) file. 
1. The `id` first checks to see if there is a THREDDS ID, and then checks to see if there is a netcdf `id` attribute.   It should be the other way around, because there will always be THREDDS ID (the pathname), and therefore the netcdf `id`, if present, will never be used.  See [these lines](https://github.com/Unidata/thredds/blob/5be05b196a3efb7a3772460ccbe80cfa964f64ff/tds/src/main/webapp/WEB-INF/classes/resources/xsl/nciso/UnidataDD2MI.xsl#L25-L26)
2. The `fileIdentifier` is being constructed using the `id` only, without the `naming_authority` information.  See [these lines](https://github.com/Unidata/thredds/blob/5be05b196a3efb7a3772460ccbe80cfa964f64ff/tds/src/main/webapp/WEB-INF/classes/resources/xsl/nciso/UnidataDD2MI.xsl#L201-L205)

**Comment by ethanrd** [comment]
I believe this issue (and PR 122) should be on Unidata/threddsIso

**Comment by ethanrd** [comment]
... Or at least on both?

**Comment by rsignell-usgs** [comment]
@ethanrd, Last time we fixed Unidata/threddsIso  it didn't make it into the next THREDDS version, so I figured I'd make the change here this time. It seems kind of crazy doing PRs for both, but if that's what it takes I'm willing to do that.  Do you want two issues also?

**Comment by ethanrd** [comment]
@rsignell-usgs Yes, it is crazy. And it shouldn't be necessary. But until the THREDDS release engineering process is more fully automated (and lots of work has been happening around this lately) there is some level of work to get threddsIso changes into thredds. Which leaves it open for being missed. When the change is only the threddsIso XSLT files, making a PR to each repository decreases the risk of it being missed. Yes, its an ugly kludge, but its what we have at the moment.

Perhaps @cwardgar or @lesserwhirls has more thoughts on the automation of pulling threddsIso (and ncWMS) into the thredds build/release.

**Comment by lesserwhirls** [comment]
We need to have a plugin layer for TDS services which would allow us to
completely remove any ncIso or ncWms specific code from the THREDDS
codebase. This is something I'm eyeballing for THREDDS 5.0.

**Comment by rsignell-usgs** [comment]
Fixed by https://github.com/Unidata/thredds/pull/122
