### ISSUE TITLE
Tutorial link is broken.

### ISSUE THREAD

**Issue by hdfeos** [Unidata/thredds#1249]
> To build the software yourself, follow this tutorial.

https://github.com/Unidata/thredds/blob/5.0.0/docs/website/netcdf-java/tutorial/SourceCodeBuild.adoc

GitHub reports 404 for the link.

**Comment by lesserwhirls** [comment]
Thanks for pointing that out - I'll get that updated! The raw markdown doc can be found [here](https://github.com/Unidata/thredds/blob/5.0.0/docs/src/public/userguide/pages/netcdfJava_tutorial/overview/BuildingFromSource.md), and the doc rendered by Jekyll can be found [here](https://docs.unidata.ucar.edu/thredds/5.0.0-SNAPSHOT/userguide/building_from_source.html).
