### ISSUE TITLE
Outdated references to TDS5 docs and release

### ISSUE THREAD

**Issue by cofinoa** [Unidata/thredds#1257]
The link to the documentation for thredds 5.0 that it's been referenced here:
https://www.unidata.ucar.edu/software/thredds/current/tds/
and it points to:
https://docs.unidata.ucar.edu/thredds/5.0.0-SNAPSHOT/userguide/tds_tutorial_index.html
it's not working (HTTP ERROR CODE 503: service unavailable)

Also update to latest release beta6 would good to be updated:
https://www.unidata.ucar.edu/downloads/thredds/index.jsp

**Comment by lesserwhirls** [comment]
Thanks for your report @cofinoa! The doc server was down while our artifacts server was being updated and moved, but should be good to go again, and I've updated the links to beta6.
