### ISSUE TITLE
Massive session creation in Threads

### ISSUE THREAD

**Issue by vegasm** [Unidata/thredds#129]
Hi,

I would like to expose a problem we have getting datasets data from our Thredds instance using netcdf-all. 

We have tools developed in R to execute netcdf-all and to download data with our tool we define the following:

HTTPBasicProvider bp = new HTTPBasicProvider("user", "password");
HTTPSession.setGlobalCredentialsProvider(bp);

Then, we open the dataset:

GridDataset gd = GridDataset.open("URL_TO_DATASET");

and after doing that, we execute GeoGrid.makeSubset and GridDataType.readDataSlice many times which create new requests to Thredds.

The problem is the way requests are developed forces Thredds to create a new session and re-authenticate in each request because the cookie store reference is lost. This behavior floods our Tomcat creating up to 200 sessions per user at the same time to download the data. I checked the code deeply in order to find what was happening:

For example, each time DConnect2.openConnection is called, a new session is generated and the cookies from the last session are lost because you get cookies from SessionClient which is redefined in each new session.

As you know, there are so much code deprecated in the classes I mentioned and in my opinion the client must be replaced by the new CloseableHttpClient and created through its builder. Another thing is the amount of code these clases have makes them difficult to maintain.

**Comment by vegasm** [comment]
I implemented a solution to our problem which allows to do the process using only one session. The approach makes use of a new HttpSession class (HttpCloseableSession) which has CookieStore, HttpContext, CredentialsProvider and CloseableHttpClient. 
This CloseableHttpClient is built by using the builder which allows you to set the proxy and the configs you’ve done in the HTTPSession setting area. I also created a new HTTPCloseableMethod class which has a similar approach to the original one but using the new features. 

Finally, I added two new methods to HTTPFactory to use a custom GET and HEAD. The new methods only need the URL because the HTTPCloseableSession is static. The new HTTPCloseableMethod accepts a HTTPSession.Methods and contains the execute method. When the opendap calls to this get, it is able to call execute and close the client (you can take a look to DConnect2.java

How can we make a request now?

It is very simple:

HTTPCloseableSession.setCredentials("username", "password");
HTTPCloseableMethod method = HTTPFactory.GET(urlString);
int statusCode = method.execute();
is = method.getResponseAsStream();
method.close();

You can see my approach is ready to basic authentication but can be used with others. I've tried not to modify so much of your code, only the esential part to make it work but I think it can be a good way to start. 

Please take a look

**Comment by DennisHeimbigner** [comment]
The deprecations are because we were forced to switch to Apache httpclient 4.4.x
before we were ready. The existing code is based on Apache httpclient 4.3.x.
The 4.4 code is substantially refactored compared to 4.3. The 4.3 API is supported,
but deprecated, so that is why you are seeing them.
The complete conversion of the code to 4.4 is underway, but probably will not
be available until version 5 of thredds.
BTW, you say "my approach is ready to basic authentication but can be used with others."
Can you give specifics, say for URS. We already or plan to support a wide variety of authorization mechanisms: Basic, ESG (client-side certificates), URS (redirection) and soon to be others.
