### ISSUE TITLE
variable attributes showing up in OPeNDAP global attributes!

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/thredds#1294]
This is pretty crazy, but if you take [this netcdf file](https://rsignell-test.whoi.edu/thredds/fileServer/silt/usgs/Projects/stellwagen/CF-1.6new/MATANZAS_18/11102sigs_burst-cal.nc) and put it on THREDDS (I've tried the most recent version 4.6.13 (latest) and 4.6.11 (circa 2017)), the variable attributes from the variable called `error` show up in the global attributes on OPeNDAP (as well as in the variable attributes)!   

It's pretty goofy to have `_FillValue` and `long_name` showing up in the global attributes!

https://rsignell-test.whoi.edu/thredds/dodsC/silt/usgs/Projects/stellwagen/CF-1.6new/MATANZAS_18/11102sigs_burst-cal.nc.html

![2019-06-18_13-52-14](https://user-images.githubusercontent.com/1872600/59707524-cd979800-91d0-11e9-8da5-9771dfe47ffc.png)

**Comment by DennisHeimbigner** [comment]
Can you post the .dds and .das that opendap generates for this file?

**Comment by rsignell-usgs** [comment]
I'm guessing you mean more than putting the .das and .dds on the end of the URL, right?
 https://rsignell-test.whoi.edu/thredds/dodsC/silt/usgs/Projects/stellwagen/CF-1.6new/MATANZAS_18/11102sigs_burst-cal.nc.das
https://rsignell-test.whoi.edu/thredds/dodsC/silt/usgs/Projects/stellwagen/CF-1.6new/MATANZAS_18/11102sigs_burst-cal.nc.dds

**Comment by DennisHeimbigner** [comment]
Actually no, I just meant what you sent, thanks. My hypothesis is that
the problem is occurring in the translation from .nc to .dds and .das.
So I thought I would start by looking at those.

**Comment by DennisHeimbigner** [comment]
When I look at that url with the netcdf-c ncdump, it looks ok to me.
What are you using to view it?  ToolsUI?

**Comment by rsignell-usgs** [comment]
I'm just looking at 
https://rsignell-test.whoi.edu/thredds/dodsC/silt/usgs/Projects/stellwagen/CF-1.6new/MATANZAS_18/11102sigs_burst-cal.nc.html

**Comment by rsignell-usgs** [comment]
The problem was caused by the variable called `error` in the NetCDF file.  If we rename that to something else, the problem goes away.

**Comment by DennisHeimbigner** [comment]
I was looking at that. The opendap code has a number of reserved names that
it uses to pass non-standard information. Apparently "error" is one one of those,
but I had had no luck finding it yet.

**Comment by rsignell-usgs** [comment]
https://www.unidata.ucar.edu/mailing_lists/archives/thredds/2016/msg00180.html
