### ISSUE TITLE
Grib2Gds.getEarth: Error in parsing earth information 

### ISSUE THREAD

**Issue by dromagnoli** [Unidata/thredds#133]
Hi,
In reference to [this](http://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_table3-2.shtml) document 
code 7 for earth shape states:
*code 7: Earth assumed oblate spheroid with major and minor axes specified (in m) by data producer*

Current code does this:
case 7:
        if (majorAxis < 6000000) majorAxis * = 1000.0; // bad units
        if (minorAxis < 6000000) minorAxis * = 1000.0; // bad units
        return new EarthEllipsoid("Grib2 Type 37", -1, majorAxis\*1000, minorAxis\*1000, 0);

I think that the code already checks whether values are in meter:
if (majorAxis < 6000000) majorAxis * = 1000.0; // bad units
if (minorAxis < 6000000) minorAxis * = 1000.0; // bad units

So, I also think that the additional pre-multiplication in the EarthEllipsoid creation isn't needed:
return new EarthEllipsoid("Grib2 Type 37", -1, majorAxis\*1000, minorAxis\*1000, 0);

Should be 
return new EarthEllipsoid("Grib2 Type 7", -1, majorAxis, minorAxis, 0);
in my opinion (Indeed, I'm getting earthRadius of 6.3\*10^9 which is too big).

You should also probably check case number 3.
*code 3:	Earth assumed oblate spheriod with major and minor axes specified (in km) by data producer*

What do you think about it?
I can create a pull request for case 7 fix.

**Comment by dopplershift** [comment]
Good catch. I don't think a PR is necessary, since the code fixes are quick enough to do. Can you point me to where you found some offending data? I want to make sure we get some tests in.

**Comment by dromagnoli** [comment]
Hi Ryan,
thanks for your feedbacks.
Not sure I can share the sample data. I will ask the customer to check if I can do that.
Cheers,
Daniele

**Comment by dopplershift** [comment]
Even if you can't share the full file, just having a single GDS record with the projection information would be critical. It's really important that we can create an automated test from sample data to ensure this doesn't break in the future.

**Comment by dromagnoli** [comment]
Hi,
I have sent a small sample. Please, let me know if you received it.

Cheers, Daniele

**Comment by dopplershift** [comment]
I got the sample. Thanks a lot!

**Comment by dopplershift** [comment]
Thanks for the test data. We now have tests for all codes but 4, 8, and 9.

Turns out code 3 was fine, but the comments were incorrect. There was a minor problem with code 1 (for bad valeus) that the testing revealed.
