### ISSUE TITLE
LayerLimit

### ISSUE THREAD

**Issue by murdav** [Unidata/thredds#134]
Dear All,

Original message from https://www.unidata.ucar.edu/mailing_lists/archives/thredds/2014/msg00135.html.

A TDS WMS GetMap request returns at most 1 WMS layer per request. If one requests more, by specifying a comma-separate list form layers= and styles=, TDS returns an error message

xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"; version="1.3.0" 
xsi:schemaLocation="http://www.opengis.net/ogc 
http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd";>

You may only create a map from 1 layer(s) at a time

However, the WMS 1.3.0 standard prescribes that in this case TDS should explicitly mention a element in the GetCapabilities:

"The optional element in the service metadata is a positive integer indicating the maximum number of layers a client is permitted to include in a single GetMap request. If this element is absent, the server imposes no limit." (page 23, OpenGIS(r) Web Map Server Implementation Specification)

This means that THREDDS should add this element to the GetCapabilities 
(LayerLimit=1) (or return more maps to be OGC compliant).

In our workflow we would like to create a single netCDF with multiple variables, doing so we load 8 tiles per WMS call independently from the number of variables within the parameter layers=rain,scov,*.
Instead as it is now we are loading 8 tiles (320x320 pixels) per each variable per WMS call.

Checking the code this implementation is a TODO. 
https://github.com/Unidata/ncWMS/search?utf8=%E2%9C%93&q=LAYER_LIMIT

Did you plan to add this in the future?

Thanks,

D

**Comment by murdav** [comment]
Checking the ncWMS code it seems the layerLimit is set to 1 and it's not possible to change it, am I right?

https://github.com/Unidata/ncWMS/search?utf8=%E2%9C%93&q=LAYER_LIMIT

**Comment by lesserwhirls** [comment]
Discussion moved to duplicate issue at Unidata/ncWMS#11
