### ISSUE TITLE
Recent Versions (>4.5) seem not properly reading some GRIB2 files

### ISSUE THREAD

**Issue by dromagnoli** [Unidata/thredds#135]
Hi,
I have issues in opening the attached GRIB file in ToolsUI (4.5.x, 4.6.x) viewer tab.

I get a:
NetCDFDataset open can't open fileX
java.io.exception: Can't read fileX: not a valid CDM file.

However, I can successfully open with ToolsUI 4.3.x and 4.4.x so I think something has been changed in the meantime in the underlying GRIB management libs.
I'm also sending a sample file to be tested.

I didn't take a look at the code to investigate on it myself, yet.

Sample file has been sent by email to the NetCDF java distribution list

**Comment by JohnLCaron** [comment]
answered on the email list
