### ISSUE TITLE
AWIPSsatConvention apparently incomplete

### ISSUE THREAD

**Issue by msdsoftware** [Unidata/thredds#136]
I've just encountered a netCDF dataset that when opened is claimed by the AWIPSsatConvention class when building the coordinate system. AWIPSsatConvention includes code written for handling the grid projections LAMBERT_CONFORMAL and MERCATOR, but the dataset uses projection CYLINDRICAL_EQUIDISTANT. If I understand the format, there is also a possibility that the projection attribute might be STEREOGRAPHIC or LATLON.

The result of the AWIPSsatConvention class not having code to examine the CYLINDRICAL_EQUIDISTANT projection is that when methods are called to construct the X and Y coordinate variables, the arrays end up being filled with 0s.

**Comment by JohnLCaron** [comment]
Hi Robert: Can you send a sample file? thanks

**Comment by msdsoftware** [comment]
Sample file link sent via e-mail.

**Comment by msdsoftware** [comment]
Closing this issue as John's commit "Grib2RecordScanning infinite loop on repeating sections" on June 4 seems to have fixed the problem amongst other changes.
