### ISSUE TITLE
namespaces/thredds/InvCatalog/v1.0 doesn't point to the latest xsd

### ISSUE THREAD

**Issue by meliezer** [Unidata/thredds#139]
Hello,
It's a website issue, but connected to the product:
http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0
includes:
An XML Schema is available at http://www.unidata.ucar.edu/schemas/thredds/InvCatalog.1.0.6.xsd.

instead of the latest version, currently: InvCatalog.1.0.7.xsd

Thanks,
Menashè

**Comment by lesserwhirls** [comment]
@ethanrd - can you updated the xsd link? I do not have proper permissions on the fileserver to do this. Thanks!

**Comment by ethanrd** [comment]
I have updated the file at the THREDDS InvCatalog v1.0 namespace URL to point to the 1.0.7 schema.
