### ISSUE TITLE
WMS service broken in 4.6.19+

### ISSUE THREAD

**Issue by gaellafond** [Unidata/thredds#1398]
THREDDS version:
**4.6.15**: WMS service works as expected
**4.6.18**: WMS service works as expected
**4.6.19**: WMS service is **broken**
**4.6.20**: WMS service is **broken**
**4.6.20-SNAPSHOT**: WMS service is **broken**

I'm using Docker THREDDS:
https://hub.docker.com/r/unidata/thredds-docker

Host is running Ubuntu.

When visiting the WMS service page from THREDDS, the server returns a **404**.

I'm happy to try other versions of THREDDS or modify my THREDDS config if that can help diagnose the issue.

**NOTE**: I also tried THREDDS version **5.3**. The WMS service is also broken on that version. It returns a broken (incomplete) XML document. It outputs the services, edal capabilites, then it tried to output the layers and it crashes after the "title" of the first layer. The title is `No dataset title found.`. Then it just stops there, with a lot of missing info and a lot of XML elements left opened (not closed, aka invalid XML).
THREDDS version **5.4-SNAPSHOT** is broken in the same way as 5.3, except that it actually print the title of the layer instead of `No dataset title found.`.

**Comment by haileyajohnson** [comment]
Hello @gaellafond , just double-checking, have you updated you config to point to the new schema, following the instructions [here](https://www.unidata.ucar.edu/blogs/news/entry/tds-users-update-your-configuration)?

**Comment by gaellafond** [comment]
@haileyajohnson Thank you!
That fixed my issue. It's strange that WMS was still working with THREDDS older than 4.6.19

For anyone reading this, if the link is broken, the fix is:

--------

Change the <!DOCTYPE> declaration in the `$tds.content.root.path/thredds/wmsConfig.xml` file of your TDS installation to replace the following string:

```http://www.unidata.ucar.edu/schemas/thredds/dtd/ncwms/wmsConfig.dtd```

with:

```https://schemas.unidata.ucar.edu/thredds/dtd/ncwms/wmsConfig.dtd```
