### ISSUE TITLE
Outdated message: "Tested on Netscape 4.61 and Internet Explorer 5.00"

### ISSUE THREAD

**Issue by meliezer** [Unidata/thredds#145]
Hello,
OPeNDAP Dataset Access Form includes the above very outdated message.
Code:
https://github.com/Unidata/thredds/blob/144f779cc20058581c660719f768fe396cd1a9c2/opendap/src/main/java/opendap/servlet/GetHTMLInterfaceHandler.java
https://github.com/Unidata/thredds/blob/144f779cc20058581c660719f768fe396cd1a9c2/tds/src/main/java/thredds/server/opendap/GetHTMLInterfaceHandler2.java

Cheers,
Menashè

**Comment by cwardgar** [comment]
Outdated? Pfah! You'll pry Netscape 4.61 out of my cold dead hands!

But yeah, fixed: a650e94e3b8b5c03b9b4d5ecf030b84f57eea685

Thanks for the heads-up!
