### ISSUE TITLE
Time string from PointFeatureCollections CSV requests are different than GridAsPoint CSV requests

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#158]
The time string returned from Grid as Point from NCSS looks like this: 

2015-05-25T00:00:00Z 

However, the time string returned from a PointFeatureCollection from NCSS looks like this: 

2015-05-20 00:35:00Z 

Small difference, but I think we should add the "T" between the date and time to make things consistent.

Will need to update documentation to make this time format clearly spelled out.

**Comment by lesserwhirls** [comment]
Could probably be addressed at same time as Unidata/thredds#159

**Comment by JohnLCaron** [comment]
I think i fixed this in latest 5.0
