### ISSUE TITLE
NCSS CSV return header consistency

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#159]
Let's make sure that csv requests from a point feature collection and csv requests from a grid as point request are consistent.

PointFeatureCollection (PFC) header: time,station,latitude[unit="degrees_north"],longitude[unit="degrees_east"],air_temperature[unit="Celsius"]

GridAsPoint (GaP) header: date,lat[unit="degrees_north"],lon[unit="degrees_east"],vertCoord[unit="m"],Temperature_height_above_ground[unit="K"]

Have GaP return the PFC type of header.

**Comment by JohnLCaron** [comment]
in 5.0, GridAsPoint and Point sharing most of the code, much more that 4.6. So mostly? should be done.
