### ISSUE TITLE
Copy/paste in toolsUI on Mac OSX

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#163]
On MacOSX, the default key combination for copy/paste is CMD+C/CMD+V. In order to use copy/paste in toolsUI (and likely TdsMonitor), you must use Ctrl+C/Ctrl+V.

**Comment by msdsoftware** [comment]
If you alter the createUI method in ToolsUI to _not_ install Nimbus L&F if it detects the user is on OS X, but instead install no UI at all, then you will get the default OS X L&F. In that case the editing keystrokes will be as expected by the Mac user.

Thus, to get something that looks slightly more Mac-like, that method might instead start

  private static void createGui() {
    if (System.getProperty ("os.name").contains ("Mac"))
    {
        System.setProperty ("apple.laf.useScreenMenuBar", "true");
    }
    else
    {
        try {
          // Switch to Nimbus Look and Feel, if it's available.
          for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
              UIManager.setLookAndFeel(info.getClassName());
              break;
            }
          }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                UnsupportedLookAndFeelException e) {
          log.warn("Found Nimbus Look and Feel, but couldn't install it.", e);
        }
    }

  // etc...

There are plenty of other things I would also alter in the makeMenu method to make the ToolsUI package look more Mac-like when running on OS X, but that's too much to get into here.

**Comment by lesserwhirls** [comment]
Thank you @msdsoftware for the pointers!

We would really like to make toolsUI a "first class" utility. It was originally developed as a helper tool for internal development, and thus the lack of "polish", so to say, but we recognize that many people are using it for their own purposes. I'm personally stuck on whether or not we try to fix things as is in the Swing framework, or if we try to port the most useful parts to JavaFX. Honestly, both would be a lot of work.

I'll give this a stab later today and see what I can come up with. Also, we are very open to suggestions, so please feel free to create an issue with your toolsUI suggestions. We are testing the waters for using github issues as our unified issue/bug/feature request/etc. tracking system, as it's open to all.

Thanks again!

**Comment by msdsoftware** [comment]
@esserwhirls, I could see myself diving in and recoding ToolsUI.java to make it look a bit more polished. However, the way it's structured now is so different from the way I have become accustomed to doing things that it could turn into a gut reno. Unfortunately, all my experience has been with using Swing, so I can't comment on the Swing vs JavaFX debate.

**Comment by lesserwhirls** [comment]
Ok, I have a fix for this: Unidata/thredds#202

Thanks @msdsoftware!
