### ISSUE TITLE
datasetScan links to catalog.xml instead of catalog.html if subdirectory contains spaces

### ISSUE THREAD

**Issue by shane-axiom** [Unidata/thredds#206]
When a datasetScan scans a directory containing subdirectories, if a subdirectory filename contains a space a link is created to that subdirectory's catalog.xml instead of catalog.html.

To test:

* Install [thredds.war](https://github.com/Unidata/thredds/releases/download/v4.6.3/thredds.war) 4.6.3
* Open `content/thredds/public/testdata`
* Create two subdirectories: `testnospace` and `"test with spaces"`
* Copy `testgrid1.nc` into both subdirectories
* Restart application container
* Open thredds/catalog/testAll/catalog.html in a browser and exmaine generated links for `testnospace` (catalog.html) and `"test with spaces"` (catalog.xml)

**Comment by dopplershift** [comment]
Confirmed on master. This should be fun to dig up...

**Comment by dopplershift** [comment]
Turns out we're creating a URI directly from the path with the spaces included; this raises an exception that we swallow. PR coming...
