### ISSUE TITLE
Replace `HTMLWriter`

### ISSUE THREAD

**Issue by dopplershift** [Unidata/thredds#250]
There's got to be a better way than adding hand-coded tags to `StringBuilder`.

**Comment by JohnLCaron** [comment]
Been some changes in 5.0, but still hand-coded.
Could try thymeleaf template...

**Comment by dopplershift** [comment]
Ideas from 4/21/2016 rant session:
- Move current catalog format to a thymeleaf template, preferably outside WAR and in content directory so that downstream users can modify easily (5.0)
- Investigate using modern HTML5 + JS + CSS frontend development with template (5.1)

**Comment by lesserwhirls** [comment]
Added in Unidata/thredds#1109 and Unidata/thredds#1110
