### ISSUE TITLE
Test TDS with Apache Proxy running NASA URS module

### ISSUE THREAD

**Issue by ethanrd** [Unidata/thredds#251]
The question of whether TDS access can be authenticated through the NASA URS user authentication system has come up a number of times from several NASA groups. The Hyrax server has [documentation](http://docs.opendap.org/index.php/Hyrax_-_User_Identification_%28Authentication%29#URS_OAuth2_.28mod_auth_urs.29) on authenticating users with NASA URS through an Apache server proxying to a Hyrax and running a NASA URS module.

Test out this basic configuration with a TDS so we can respond to these inquiries.

**Comment by ethanrd** [comment]
Once someone registers for an account on the  [test NASA URS system](https://uat.urs.earthdata.nasa.gov/), I can contact the NASA URS admin that I've been in touch with to get the proper permissions.

**Comment by lesserwhirls** [comment]
@ethanrd - I just registered an account. Let me know where we go from here!

**Comment by DennisHeimbigner** [comment]
I am in the process of building some docker containers to allow us to
test vsupport for various authentication schemes (URS, client-side certs, etc).
It may take a while since I am having to learn docker.

**Comment by ethanrd** [comment]
@lesserwhirls - Let me know your user id and I will get in touch with the NASA URS folks to get you the needed permissions

**Comment by lesserwhirls** [comment]
@lesserwhirls likes to keep it simple and cool - user id: lesserwhirls

![@lesserwhirls - one sly guy](http://rs89.pbsrc.com/albums/k231/Cajun89/breakfast-club-sunglasses_zps247024b1.gif~c200)

**Comment by ethanrd** [comment]
@lesserwhirls, @DennisHeimbigner, @oxelson Where does this stand? Did we ever try out a TDS with the Apache mod for NASA URS setup? I remember it didn't appear to be a great solution (only re-routing after authentication to a single URL?) but can't remember if we ever actually tried it out.

**Comment by lesserwhirls** [comment]
We did, it worked but not useful (re-routing to a single url). Will need to investigate adding code to the TDS to do the authentication.

**Comment by oxelson** [comment]
BTW, that module is still installed/running.  I'd rather get rid of it if
we are not planning to use it.

Let me know.

**Comment by ethanrd** [comment]
@oxelson It is no longer being used. Feel free to get rid of it.

**Comment by ethanrd** [comment]
Since it works (though a bit kludgy?), I'm closing this issue.

**Comment by ethanrd** [comment]
PS Anything more sophisticated would require some development work.

**Comment by oxelson** [comment]
Great.  Will do.  Thanks.
