### ISSUE TITLE
S3 crawlabledataset temporary file issue

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#255]
@cwardgar - @dopplershift and I ran into a few issues on the Amazon instance of the TDS interfacing the Level 2 Radar data on S3. The disk space filled up pretty quickly (13GB) due to temporary files that are created by the S3URI class. Bare with me here, and apologies upfront for the long message :-)

When serving data that lives on Amazon S3, the data is first pulled from the S3 bucket to local disk and saved to a temporary file. The temporary file contains a random string of characters, which isn't too big of a deal in and of itself. The code that does this is located in S3URI:

https://github.com/Unidata/thredds/blob/master/cdm/src/main/java/thredds/crawlabledataset/s3/S3URI.java#L198-L202

First issue: somewhere, there is a potential "bug" in the code such that the file is re-downloaded from S3 for every request - maybe related to an issue in checking the cache to see if the file already exists? This isn't an 'in your face' kind of thing, because the temporary file gets cleaned up once a new request is made. While this would make sense if we were downloading only part of a file in S3 using a getByteRange kind of request, we were told by Amazon to download the whole file and that requesting byte ranges from S3 is not the way to go. ***Is there a way we can do better at checking the cache to reduce multiple downloads of the same S3 resource?***

Now, let's suppose we have a compressed file in S3. In this situation, a user makes a request to the TDS, the temporary file is created and filled with the contents from the bucket in S3, and then the file gets decompressed. Let's also say the first request was to read the metadata of the file via opendap.

Now, the if user makes a further request, say, to actually request data from the file, the code as it stands will delete the old compressed file, will create a new temporary file (with a new name differing only in the random string part of the filename), re-download the gzip file from S3, and then uncompresses the file,

***The end result is that the temporary file directory will contain one compressed file and `n` number of uncompressed raw files, all with the same hashcode, where `n` is the number of requests made to that S3 resource.***

As an example of how this can get out of control, let's use the example of the IDV loading one volume (i.e. one file) using the TDS RadarServer. Behind the scenes, the IDV requests a lot of metadata for each variable, in which it actually makes 18 requests to the sever via opendap. This results in 19 temporary files being stored on disk: 1 gzip file from the S3 bucket (downloaded from S3 a total of 18 times), and 18 uncompressed raw files in which only the name is different (just the random string part of the filename). So, just having the IDV "open" a radar file, without reading data, results in nearly 500 MB of data on disk and 18 downloads of the same resource. It would seem that adding the random part to the temporary file, combined with the first potential bug from above, is what is causing this issue. Do the temporary files need that random string portion of the file name?

Thanks!

**Comment by dopplershift** [comment]
Here's the bucket we're hitting that reveals this: http://noaa-nexrad-level2.s3.amazonaws.com/

**Comment by JohnLCaron** [comment]
Im assuming this is in S3 stuff, not NetcdfFile.

It doesnt seem right that you create an arbitrary name for the "temporary" file if you want to find it again.

**Comment by cwardgar** [comment]
I wasn't able to reproduce multiple downloads of the same file (do you have a threddsServlet.log that shows this?), but I did see the downloaded file being uncompressed and saved on each Opendap request. I fixed that in #256 by returning a stable file name from S3URI.

I'm pretty sure there's nothing left to do for this issue, but let me know if I am wrong.

**Comment by dopplershift** [comment]
We didn't actually document repeated downloads; it was just kind of assumed based on the fact that the file kept changing its name. Either way it looks like #256 fixes our problems. Thanks!
