### ISSUE TITLE
Unintuitive behavior of NetcdfFileWriter.setRedefineMode()

### ISSUE THREAD

**Issue by dopplershift** [Unidata/thredds#287]
While calling `setRedefineMode(true)` allows one to modify attributes, groups, etc., it isn't until `setRedefineMode(false)` is called that changes are actually saved to disk. The fact that calling `close()` on the file isn't sufficient is very unintuitive.

At a minimum, we need to document this fact (the docs only mention that the function mimics `nc_redef` and `nc_enddef`); it would also be *really* helpful to issue a warning if the file is closed while redefine mode is set.

The other option is to go ahead and serialize any pending changes when the file is closed (i.e. just call `setRedefineMode(false)`) when closing the file; this would seem clearly to be what the user wanted.

**Comment by lesserwhirls** [comment]
@Unidata/team-thredds @JohnLCaron - any thoughts on this? I agree with @dopplershift that calling .close() isn't sufficient to save modification of attributes and whatnot to disk seems very unintuitive.

On a related note, we should really start making example java code to show how to do common tasks in netcdf-java (using 5.0) and really beef up our cookbook. I will open a standing issue to hold a running list of ideas on what examples we should create.

**Comment by DennisHeimbigner** [comment]
This code seems way to complicated; what is the intended behavior for an arbitrary
file?

**Comment by JohnLCaron** [comment]
The whole redefineMode thing is a dinosaur, mimicing C lib. seems fine to check on close and generally mitigate the complexity. 

cookbook examples +1
