### ISSUE TITLE
Bad Netcdf4 array data from GINI file on NCSS

### ISSUE THREAD

**Issue by dopplershift** [Unidata/thredds#301]
From esupport IQR-260651.

Some combination of a western boundary east of -140 longitude and requesting NetCDF4 data results in a "corrupted" array in the resulting netcdf file. The result almost looks like a mismatched stride.

Broken (NetCDF4 and west > -140):
http://thredds.ucar.edu/thredds/ncss/satellite/IR/WEST-CONUS_4km/20151109/WEST-CONUS_4km_IR_20151109_0630.gini?var=IR&north=60&west=-139&east=-100&south=30&horizStride=1&time_start=2015-11-09T06%3A30%3A20Z&time_end=2015-11-09T06%3A30%3A20Z&timeStride=1&accept=netcdf4

![gjbeggag](https://cloud.githubusercontent.com/assets/221526/11342424/9b9b85a6-91c4-11e5-8f1b-93aac2d28327.png)

Works (NetCDF4 and west <= -140):
http://thredds.ucar.edu/thredds/ncss/satellite/IR/WEST-CONUS_4km/20151109/WEST-CONUS_4km_IR_20151109_0630.gini?var=IR&north=60&west=-140&east=-90&south=30&horizStride=1&time_start=2015-11-09T06%3A30%3A20Z&time_end=2015-11-09T06%3A30%3A20Z&timeStride=1&accept=netcdf4

![bbfeidaa](https://cloud.githubusercontent.com/assets/221526/11342392/71666260-91c4-11e5-8061-825a556afb19.png)

Works (NetCDF3):
http://thredds.ucar.edu/thredds/ncss/satellite/IR/WEST-CONUS_4km/20151109/WEST-CONUS_4km_IR_20151109_0630.gini?var=IR&north=60&west=-139&east=-100&south=30&horizStride=1&time_start=2015-11-09T06%3A30%3A20Z&time_end=2015-11-09T06%3A30%3A20Z&timeStride=1&accept=netcdf

![ebdgbhcc](https://cloud.githubusercontent.com/assets/221526/11342422/99989848-91c4-11e5-85bd-ae329e158964.png)

I can see the bad data if I look at the basic netCDF output using Python; the problem occurs somewhere on the side of creating the NetCDF4 file or reading/subsetting the data.

**Comment by dopplershift** [comment]
@JohnLCaron I'm a bit over my depth here. Running locally with exceptions enabled, I hit the following assert in `Nc4Iosp.java:2842`:

```java
      case Nc4prototypes.NC_BYTE:
      case Nc4prototypes.NC_UBYTE:
        byte[] valb = (byte[]) data;
        assert valb.length == sectionLen;
        int ret = isUnsigned ? nc4.nc_put_vars_uchar(grpid, varid, origin, shape, stride, valb) : nc4.nc_put_vars_schar(grpid, varid, origin, shape, stride, valb);
        if (ret != 0)
          throw new IOException(ret + ": " + nc4.nc_strerror(ret));
        break;
```

Now, from tracing the code, as far as I can tell this is the actual code that's supposed to be doing the subset....so what's going on here exactly?

**Comment by dopplershift** [comment]
Example file attached.
[WEST-CONUS_4km_IR_20151109_0630.gini](https://files.zenhub.io/5654ecef5b75e1023f093acc)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by JohnLCaron** [comment]
So in 5.0 (can also use 4.6, probably hasnt changed) put breakpoint at
Giniiosp line 321:

Array array = Array.factory(DataType.BYTE, v2.getShape(), uncomp);

where for that file, uncmp has length 1413,100, not matching the shape (1,
1280, 1100) = 1408,000

probably should throw an exception in Array.factory to look for such
problems. as it is, we just happen to check that in Nc4Iosp.

 so, ill let you grapple with why Gini data doesnt match header info...

**Comment by JohnLCaron** [comment]
add unit test for that file in cdm-test to ucar.nc2.iosp.gini.TestGini when
you get a chance...

**Comment by dopplershift** [comment]
The "too many bytes" problem is a red herring: see #325 .  The way the zlib code in the GINI IOSP was working, it was always handing `Array.factory()` too much data. Plenty of our existing test cases exhibited this problem, and it's resolved in #325.

Still trying to find a good automatic test case for the problem here, but at least this resolves the assertion. (And drastically cleans up GINI!)

**Comment by dopplershift** [comment]
@JohnLCaron The assert in `Nc4Iosp.java` is still bogus. Again it fails here:
```java
      case Nc4prototypes.NC_BYTE:
      case Nc4prototypes.NC_UBYTE:
        byte[] valb = (byte[]) data;
        assert valb.length == sectionLen;
        int ret = isUnsigned ? nc4.nc_put_vars_uchar(grpid, varid, origin, shape, stride, valb) : nc4.nc_put_vars_schar(grpid, varid, origin, shape, stride, valb);
        if (ret != 0)
          throw new IOException(ret + ": " + nc4.nc_strerror(ret));
        break;
```
In this case `valb.length` is 140800 (which matches the 1100 x 1280 original data array) and `sectionLen` is 1030700 (which matches the size of the requested section). The problem here is that `Array` is just referencing the underlying data, not copying it, so it's not *supposed* to match the section size. I think these asserts are just wrong--can you prove me wrong on why we should keep these?

For now I'm going to comment out and keep trying to figure out the cause of the corrupted data.

**Comment by dopplershift** [comment]
Actually, I think the assertion is fine. The problem is that **nowhere** has the `Array` returned by the GINI IOSP, which is a properly `Section`-ed view of the full grid of data, been copied or reduced such that the underlying storage for the `Array` is 1D contiguous. Therefore, it can't be passed as is to NC4 JNI code. @cwardgar and I have our suspicions on where this should be, but I'd really like @JohnLCaron's opinion.

**Comment by JohnLCaron** [comment]
From GiniIosp:

Array array = Array.factory(DataType.FLOAT, v2.getShape(), fdata);

return array.sectionNoReduce(origin, shape, stride);


the first line reads the entire array, the second logically subsets it.
typical when there isnt a big advantage to reading just the desired subset.

So the problem is here:

Object data = values.getStorage();


which ignores the logical subsetting, and is just plain wrong.

it should be:


Object data = values.copyTo1DJavaArray();


can you try that and see if it fixes problem?

**Comment by cwardgar** [comment]
Wow, Ryan, we got this right in our talk offline. *high five*

**Comment by JohnLCaron** [comment]
well done, mates

**Comment by dopplershift** [comment]
My only concern about that solution would be that it forces a copy even if the `Array` instance doesn't need subsetting--specifically, I'm thinking of arrays coming from GRIB, which work currently. Do you think this is worth worrying about?

**Comment by cwardgar** [comment]
`Array.get1DJavaArray(Class)` is the method you want to use; it determines if a copy is necessary and doesn't do one if it isn't.

**Comment by JohnLCaron** [comment]
yes, thats what i was thinking of. thanks for tracking it down
