### ISSUE TITLE
maven snapshots

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#303]
@cwardgar - would it be possible to upload nightly snapshot artifacts to our nexus using the aws jenkins? We have not pushed any snapshot artifacts to our nexus server since 4.5.6 (March 30th 2015), for example

https://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/edu/ucar/tds/

**Comment by lesserwhirls** [comment]
To be clear, this would be for 4.6.4-SNAPSHOT as well as 5.0.0-SNAPSHOT.

**Comment by cwardgar** [comment]
Done. The threddsMaster and thredds5.0 Jenkins jobs now publish Maven artifacts to our repo after running tests. This is done even if there are test failures.

I should point out that publishing the latest master produced 288 MB of artifacts:
18.1 MB of module jars (e.g. bufr, cdm, grib)
128.8 MB of fat jars (dap4, ncIdv, netcdfAll, tdmFat, toolsUI)
15.5 MB of source code jars
18.6 MB of javadoc jars
106.3 MB of wars (d4ts, d4tswar, dtswar, tds)

So publishing both master and 5.0.0, that's over half a gig a day. Are we going to run out of space?

**Comment by dopplershift** [comment]
Looks like we should be able to set up Nexus to delete old snapshots:
http://blog.sonatype.com/2009/09/nexus-scheduled-tasks/#.VlXfgzaDGko

On another note, is there utility in publishin the dap wars and nightly snapshots of the javadoc jars? Or the source code jars?

**Comment by lesserwhirls** [comment]
@cwardgar - sweet! Thanks for getting this setup!

@dopplershift - Not sure if there is or not. I think the current gradle build looks for all artifacts and publishes them. The JavaDoc jars may be useful if someone is just pulling in enough to use dap (?) in their code, but the war file? Not sure about that. Is there also a dap.jar artifact?

@oxelson - could we setup the nexus repository to keep, say, 7 days of snapshot artifacts generated by the THREDDS project?

**Comment by oxelson** [comment]
> @oxelson <https://github.com/oxelson> - could we setup the nexus
> repository to keep, say, 7 days of snapshot artifacts generated by the
> THREDDS project?
>

Of course.  What do you need?

**Comment by lesserwhirls** [comment]
@oxelson - @dopplershift pointed to a blog post about how to use the "Remove Snapshots From Repository" task as found in Nexus. Do you currently use this task anywhere on Nexus?

**Comment by DennisHeimbigner** [comment]
I should note that d4ts, d4tswar, dtswar
probably do not need to be constructed by jenkins
or travis because they are only needed when I plan to
upgrade those servlets on remotetest.
=Dennis


Christian W wrote:

**Comment by cwardgar** [comment]
#324 reduces the total size of the artifacts to 206 MB. Not bad. We should be okay if we're deleting snapshots that are over a week old.
