### ISSUE TITLE
WMS calendar 365_day bug

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#310]
From e-support FKT-5741388 "WMS bug in THREDDS 4.6.3":

The problem is related to a dataset with attribute of no-leap year (calendar: 365_day)

Here I present you a case:

http://dataserver2.nccs.nasa.gov/thredds/catalog/NEX-GDDP/IND/historical/day/atmos/tasmax/r1i1p1/v1.0/catalog.html?dataset=historical/day/atmos/tasmax/r1i1p1/v1.0/tasmax_day_BCSD_historical_r1i1p1_inmcm4_2005.nc

the netCDF subset service works fine with time range from Jan-1-2005 to
Dec-31-2005

but when you choose WMS service, the time range shifts to 2004-12-23 to 2005-12-22.

**Comment by lesserwhirls** [comment]
The WMS issue is apparent in the WMS GetCapabilities doc:

http://dataserver2.nccs.nasa.gov/thredds/wms/NEX-GDDP/IND/historical/day/atmos/tasmax/r1i1p1/v1.0/tasmax_day_BCSD_historical_r1i1p1_inmcm4_2005.nc?service=WMS&version=1.3.0&request=GetCapabilities

as seen in the element

```
<Dimension name="time" ...>
```

**Comment by tsanah** [comment]
the very same data works fine with THREDDS 4.2 WMS

**Comment by lesserwhirls** [comment]
The fix is in pull request Unidata/ncWMS#15. As soon as it is merged, I will create a PR to use the updated ncWMS artifact. This will get included in the next release (v4.6.4), which will hopefully be ready this month, or shortly after AMS (mid-January).

**Comment by tsanah** [comment]
Hi Sean,

  Many thanks...

**Comment by tsanah** [comment]
Would it be possible to have v4.6.4 included here, so I can also try to compile geoTIFF IOSP ?

https://artifacts.unidata.ucar.edu/content/repositories/unidata-releases/edu/ucar/thredds-parent/

**Comment by lesserwhirls** [comment]
When we release 4.6.4 it will show up there. However, we are publishing
nightly builds in the snapshot-repository:

https://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/edu/ucar/tds/

The artifact for the TDS is tds-...-.war.

Once the pull requests get merged, I can publish and snapshot so that you
can use it before our nightly builds. Will that work?

**Comment by tsanah** [comment]
that is great ?  thanks again

**Comment by lesserwhirls** [comment]
Sorry @tsanah - I see what you were asking for with regards to the thredds-parent artifact (the top level maven pom for the thredds project). We recently switched from maven to gradle, and I do not thing we have gradle generating a top level pom for the project to be published. @cwardgar - is this possible?

In the meantime, you could probably use the netCDFAll artifact to build the IOSP. If you include our snapshot repository in your pom file, 

```
<repositories>

    ....

    <repository>
        <id>unidata-snapshots</id>
        <name>UNIDATA Snapshots</name>
        <url>https://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/</url>
    </repository>
</repositories>
```

you can use the following dependency in you pom:

```
<dependency>
    <groupId>edu.ucar</groupId>
    <artifactId>netcdfAll</artifactId>
    <version>4.6.4-SNAPSHOT</version>
</dependency>
```

**Comment by cwardgar** [comment]
Maybe I'm missing something, but I can't imagine any possible reason that a library user would need that top-level POM. @tsanah, do the instructions [here](http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/BuildDependencies.html) not help you to do what you're trying to do?

**Comment by lesserwhirls** [comment]
Thanks @cwardgar - I totally forgot about that page!

**Comment by tsanah** [comment]
@cwardgar @lesserwhirls 

Thank you both, 

I am using 

https://github.com/USGS-CIDA/geotiff-iosp

to create thredds.war via mvn  -- I don't know other method to have geoTIFF IOSP compiled with THREDDS

**Comment by cwardgar** [comment]
Unfortunately, @tkunicki has it right in geotiff-iosp's README:

"Installation without the use of maven is difficult due to the number of required dependencies and caveats concerning their use in different projects and platforms."

As you know, geotiff-iosp is being built against TDS v4.5.5, and it's difficult to guess what it would take to build it against v4.6, especially since TDS is assembled with Gradle instead of Maven.

NetCDF-Java's poor pluggability is a known problem. We've been hoping that Project Jigsaw in JDK9 will be the silver bullet we need. Otherwise, we'll have to look into OSGi.

**Comment by tkunicki** [comment]
@cwardgar the top-level pom is used as a bom type pom (bill of materials)., it's simply needed to guarantee that the IOSP is using the same depedendcy versions as the rests of thredds and the cdm (using dependency management with scope of import).  If there's an alternate pom that could suit this need I could migrate the IOSP to it.

If you could produce a pom with a master set of dependencies (and versions) amongst the tds/cdm projects for a given release that would be beneficial.  I know of other projects that rely on this when compiling against thredds and netcdf-java and w/o a bom-type pom migration to 4.6 will be very tedious and complicated.

**Comment by cwardgar** [comment]
@tkunicki We do have a file that defines a master set of dependencies but it's for Gradle, not Maven ([link](https://github.com/Unidata/thredds/blob/master/gradle/dependencies.gradle)). That said, it probably wouldn't be too much work to write a task that creates a Maven BOM using that info.

Is that BOM all you need to get your project working with v4.6, given that we're already producing Maven artifacts for the modules? It doesn't matter for your purposes that we're now using Gradle to generate thredds.war?

**Comment by tkunicki** [comment]
The bom pom is a critical requirement for developing plugins with the current TDS architecture.

1. The bom pom is required to automatically synchronize dependencies w/ TDS for plugin development (with dependencyManagement and scope import)
2. Additionally, the TDS war should be available in a publicly accessible maven repo so that a maven war overlay project can successfully inject the plugin and its dependencies into the TDS war.

@jiwalker-usgs and @isuftin pinged as the might have interest in this for TDS/CDM migrations for other projects that rely on bom poms

**Comment by cwardgar** [comment]
Ah, I wasn't aware of the Maven war overlay feature. So you don't actually care how we're building tds.war, as long as its available as an artifact in a repo (which it is).

Okay, I've created a new issue for the BOM: #323. I'm gonna close this one as we've veered way off the original topic.

**Comment by cwardgar** [comment]
Actually, it looks like @lesserwhirls still has a little bit of work to do on this before we close it. I've gone ahead and merged your ncWMS PR though.

**Comment by lesserwhirls** [comment]
Oops - what error/issue is still there? Did I miss a message somewhere?

**Comment by cwardgar** [comment]
Nevermind, I see #311 now.
