### ISSUE TITLE
Possible Issue when running the TDS/TDM when port 80 is not available

### ISSUE THREAD

**Issue by julienchastang** [Unidata/thredds#313]
John suggested I submit this issue on github so here goes:

We have been running the TDS/TDM on the Azure cloud successfully here:

[http://unidata-server-2.cloudapp.net/thredds/catalog.html](http://unidata-server-2.cloudapp.net/thredds/catalog.html)

We are using the TDS configuration with these resources.

[https://github.com/Unidata/TdsConfig](https://github.com/Unidata/TdsConfig)
[https://github.com/Unidata/Unidata-Dockerfiles/tree/master/tds-base](https://github.com/Unidata/Unidata-Dockerfiles/tree/master/tds-base)
[https://github.com/Unidata/Unidata-Dockerfiles/tree/master/ams2016](https://github.com/Unidata/Unidata-Dockerfiles/tree/master/ams2016)

This is being done with Tomcat running on port 8080 within the TDS docker container and docker forwarding the port from 80 to 8080.

However, when we eliminate the 80 to 8080 forwarding, the TDM can no longer trigger the TDS to refresh the catalog view for a given dataset (e.g., 13 KM RR). This refresh problem is the only observable issue. All other aspects of this TDS/TDM combination work as expected including:

- creation on the grib index files (gx9, etc.)
- the rendering of the web page at 
[http://unidata-server-2.cloudapp.net:8080/thredds/catalog.html](http://unidata-server-2.cloudapp.net:8080/thredds/catalog.html)

In addition, we do not detect any issues connecting the Tomcat TDS SSL port 8443. 

The conclusion of John and I’s analysis is that it may be a TDS issue, but could also be an issue with Docker or the Azure cloud. (One simple test would be to try this experiment on the Amazon cloud — something I hope to do soon).

**Comment by lesserwhirls** [comment]
Hi @julienchastang - just wondering if you were able to figure this one out. Last I recall, you have a fully working docker container for tds and tdm, so maybe?

**Comment by julienchastang** [comment]
Thanks @lesserwhirls. I am going to have to study this issue again to see if it is still relevant (I think it may be). The good news is I will be looking into this with the dockerization of the TDS/TDM work I am about to revisit. I have assigned this issued to me for the time being since I am the blocker on this one as of right now.

**Comment by lesserwhirls** [comment]
Sounds good @julienchastang - thanks!

**Comment by julienchastang** [comment]
I finally got around to trying to reproduce this issue on Azure, and can't. Let's chalk it up to my lack of familiarity with running the TDS/TDM in Docker/Cloud environments 6 months ago. I've refactored my approach and I am no longer running into this problem.
