### ISSUE TITLE
Error on ToolsUI when config file is passed as argument

### ISSUE THREAD

**Issue by cofinoa** [Unidata/thredds#333]
Hi, 
When ToolsUI is started from command line with `-nj22Config miConfig.xml` argument, an error is fired indicating that `-nj22Config miConfig.xml` dataset can't be open.

**Comment by lesserwhirls** [comment]
Needs to be updated to use jCommander - see the classes from here for an example: http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/manPages.html
