### ISSUE TITLE
Should legacy still be in 5.0 build, test ?

### ISSUE THREAD

**Issue by JohnLCaron** [Unidata/thredds#335]
Or if leaving in, make it work without a fail message

from Travis:

thredds.crawlabledataset.s3.CachingThreddsS3ClientSpec > getObjectMetadata STANDARD_ERROR
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Gradle Test Executor 6 finished executing tests.
Finished generating test XML results (0.0 secs) into: /home/travis/build/JohnLCaron/thredds/legacy/build/test-results
Generating HTML test report...
Finished generating test html results (0.002 secs) into: /home/travis/build/JohnLCaron/thredds/legacy/build/reports/tests
:legacy:test (Thread[main,5,main]) completed. Took 6.599 secs.
:netcdf4:compileTestJava (Thread[main,5,main]) started.
:netcdf4:compileTestJava
file or directory '/home/travis/build/JohnLCaron/thredds/netcdf4/src/test/java', not found
Skipping task ':netcdf4:compileTestJava' as it has no source files.
:netcdf4:compileTestJava UP-TO-DATE

**Comment by JohnLCaron** [comment]
waterml test has same issue, should add a log implementation to dependencies

ucar.nc2.ogc.waterml.NcCollectionTypeTest > testCreateCollection STANDARD_ERROR
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Gradle Test Executor 11 finished executing tests.

**Comment by cwardgar** [comment]
Fixed in #336. I already had logic that added a testRuntime dependency on "slf4j-jdk14", but only if the subproject had an existing *non-transitive* dependency on "slf4j-api". :legacy and :waterml were pulling in "slf4j-api" transitively.

Isn't legacy intended as a transition aid from v4 to 5? If so, we should still be building it and testing it. I wouldn't mind nuking it for the next major version though.

**Comment by JohnLCaron** [comment]
i suppose we still need to build and test it.
