### ISSUE TITLE
Out of range Lon normalized incorrectly for grib file.

### ISSUE THREAD

**Issue by rgaskill** [Unidata/thredds#340]
Outputting the stats of the file in question with wgrib I get the following:

```
rec 1:0:date 2015120900 TMPA kpds5=25 kpds6=105 kpds7=2 levels=(0,2) grid=211 2 m above gnd valid 30-30d: bitmap: 55047 undef
  TMPA=Temp. anomaly [K]
  timerange 2 P1 30 P2 30 TimeU 2  nx 360 ny 179 GDS grid 0 num_in_ave 0 missing 0
  center 250 subcenter 1 process 255 Table 2 scan: WE:SN winds(grid) 
  latlon: lat  -89.001000 to 88.998000 by 0.000000  nxny 64440
          long -180.000000 to 179.000000 by 0.000000, (360 x 179) scan 64 mode 8 bdsgrid 1
  min/max data -0.7 3.7  num bits 6  BDS_Ref -7  DecScale 1 BinScale 0
```

but when I read in the same file via GridDataset (`GridDataset gridDataset = GridDataset.open(filename);`) the lon range is wrong.

```
lat -> min: -89.00100708007812 max: 88.99800872802734
lon -> min: 179.99998474121094 max: 539.0
```

I tracked the issue down to [this](https://github.com/Unidata/thredds/blob/5612f5ff64823b8bd36513887236df48748c4290/cdm/src/main/java/ucar/unidata/geoloc/LatLonPointImpl.java#L121)

```
  static public double lonNormal(double lon) {
    if ((lon < -180.) || (lon > 180.)) {
      return Math.IEEEremainder(lon, 360.0);
    } else {
      return lon;
    }
  }
```

Which normalizes the value `-180.00001525878906` to the positive value of  `179.99998474121094`.

I just naively updated the `lonNormal` function to:

```
static public double lonNormal(double lon) {
    if (lon < -180.) {
      return -180.;
    } else if (lon > 180.) {
      return 180.;
    } else {
      return lon;
    }
  }
```

Which is similar to what `latNormal` does, but this breaks a number of tests.  So I think I may be fixing this in the wrong place.

**Comment by rgaskill** [comment]
@tkunicki thoughts?

**Comment by rgaskill** [comment]
The root of the issues in my example appears to be floating point precision.

In the `Grib1Gds` class it is reading out of the file the int `-180000` then multiplying it by the float `.001` which results in `-180.00002` then when this value is passed to `LatLonPointImpl` where it is implicitly converted to the double `-180.00001525878906` which is less than `-180.` which causes it to be normalized to '179.99998474121094'.

**Comment by JohnLCaron** [comment]
is there a sample file?

**Comment by rgaskill** [comment]
@JohnLCaron not one that I can share. It is a grib1 file that is reading `180000` from [here](https://github.com/Unidata/thredds/blob/9aaadaacc35889e5c5eb94f06252b7173e632140/grib/src/main/java/ucar/nc2/grib/grib1/Grib1Gds.java#L394).  I spent some time trying to find a publicly available grib1 file that had la1 defined as `180000` in the gds but couldn't find one.  

I was actually able to fix my scenario with the updates I made [here](https://github.com/rgaskill/thredds/tree/bd).  Though, I am not sure this is the approach you guys want to take.

**Comment by JohnLCaron** [comment]
Possibly we could change to double precision for the internal params. Or skip normalization. Probably dont want BigDecimal, i would assume too slow.

But we really need a sample record to make much progress.

**Comment by rgaskill** [comment]
[This](https://drive.google.com/file/d/0B2VFox1bvA8bTEFuWFlSLVhHbFk/view?usp=sharing) file reproduces the error.

**Comment by rgaskill** [comment]
There are a number of ways to jockey around the floating point error.  The real issue here is the lack of control of precision.  BigDecimal maintains the precision along with the value for you (at a performance cost :)).  In the context of reading the GDS from the grib file I am not sure the performance hit is significant?  

We can avoid the use of BigDecimal by maintaining the precision on our own (in this case 3dp).  For example:  

```
la1 = Math.round(la1*1000) /1000
lo1 = Math.round(lo1*1000) /1000
ProjectionPoint startP = proj.latLonToProj(new LatLonPointImpl(la1, lo1));
```
This is just a brute force example.  We need to maintain the precision for each math operation to be precise.

**Comment by JohnLCaron** [comment]
not sure what this does:

la1 = Math.round(la1*1000) /1000
lo1 = Math.round(lo1*1000) /1000

**Comment by JohnLCaron** [comment]
I think the root of the problem is the unneeded normalization. Replacing this method in Grib1Gds.LatLon seems to solve the problem:

    public GdsHorizCoordSys makeHorizCoordSys() {
      LatLonProjection proj = new LatLonProjection(getEarth());
      //ProjectionPoint startP = proj.latLonToProj(new LatLonPointImpl(la1, lo1));
      double startx = lo1; // startP.getX();
      double starty = la1; // startP.getY();
      return new GdsHorizCoordSys(getNameShort(), template, 0, scanMode, proj, startx, getDx(), starty, getDy(), getNx(), getNy(), null);
    }

It will take some time to get this into our unit tests etc, but if you want to try it and let us know, that would help.

**Comment by JohnLCaron** [comment]
I am also experimenting with using double precision, though i think thats not really going to change anything. Note that these number are truly (limited precision) floating point, not integers.
