### ISSUE TITLE
Orthogonal timeSeriesProfile times are incorrect in toolsUI's PointFeature viewer

### ISSUE THREAD

**Issue by shane-axiom** [Unidata/thredds#37]
Times are showing up incorrectly in the toolsUI's PointFeature viewer for orthogonal timeSeriesProfiles. For example:

http://data.nodc.noaa.gov/thredds/fileServer/testdata/netCDFTemplateExamples/timeSeriesProfile/usgs_internal_wave_timeSeries.nc

The profileName, obsDate, and nomDate all show the time of the first profile in the dataset. The incomplete/ragged variants of timeSeriesProfile seem to work fine.

**Comment by lesserwhirls** [comment]
@JohnLCaron @cwardgar - has this been address?

**Comment by cwardgar** [comment]
@lesserwhirls - No, not yet, but it's on my TODO list.

**Comment by lesserwhirls** [comment]
Ok, that's cool. Is it in Jira? If so, can we add a link for @shane-axiom to track and close out this issue on github?

**Comment by dopplershift** [comment]
Isn't there some way to link jira and github?

**Comment by cwardgar** [comment]
I can't reproduce this in 4.6.2-SNAPSHOT:

![usgs_internal_wave_timeSeries.png](https://lh3.googleusercontent.com/7xffx7yZgDzineY3M3onmaA9YxxB8XyrJmiGVzbdm0c=w718-h734-no)

The profileName, obsDate, and nomDate all show the time of the profile they're associated with, *not* the first profile in the dataset. Am I missing something? Maybe we fixed this?

**Comment by lesserwhirls** [comment]
@shane-axiom - does the screenshot @cwardgar posted above look right?

**Comment by shane-axiom** [comment]
Yes, I verified that this was broken in toolsUI-4.3.23.jar and fixed in toolsUI-4.6.jar. Thanks!
