### ISSUE TITLE
5.x errors with National Blend grib2 files

### ISSUE THREAD

**Issue by dopplershift** [Unidata/thredds#375]
So the 5.x branch throws:
```java.lang.RuntimeException: TimeInterval(2) has different units```
when reading [National_Blend_min_temp.grib2](https://files.zenhub.io/569ed287bb5ef2e60394ae79)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

(I pulled out only the relevant field that causes problems.) It looks like they didn't encode any kind of interval (a bunch of 255's) to go with the minimum/maximum temps, even though they're supposed to be daily values.

@JohnLCaron want to take a look and see if there's something more sensible lurking somewhere? Right now I can fix the error and get things to read in without error, but then it calls values "Minimum temperature (255_Hour Minimum)" which seems sub-optimal, but could (horribly) be the best we can do.

**Comment by JohnLCaron** [comment]
I will have a look at it.

**Comment by JohnLCaron** [comment]
Can one of you domain experts look at this file and decide what correct value is? And/or contact them and/or run wgrib2.

see more notes in pull request.

**Comment by dopplershift** [comment]
Have seen comments, just not gotten around to bothering with wgrib2 on my mac (ugh). I can tell you that the ranges in question are max/min for a given day. Not sure if that clarifies Grib2 encoding.

**Comment by JohnLCaron** [comment]
File=0 D:/work/grib/National_Blend_min_temp.grib2 

```
Grib2IdentificationSection
 Center        = (7) US National Weather Service, National Centres for Environmental Prediction (NCEP)
 SubCenter     = (14) NWS Meteorological Development Laboratory
 Master Table  = 1
 Local Table   = 0
 RefTimeSignif = 1 (Start of forecast)
 RefTime       = 2016-01-19T12:00:00Z
 RefTime Fields = 2016-1-19 12:0:0

18:                                                            Indicator of unit of time range == 1 (table 4.4: Hour) 
 19:                                                 Forecast time in units defined by octet 18 == 36 
 
 35:                                                Year - time of end of overall time interval == 2016 
 37:                                               Month - time of end of overall time interval == 1 
 38:                                                 Day - time of end of overall time interval == 21 
 39:                                                Hour - time of end of overall time interval == 12 
 40:                                              Minute - time of end of overall time interval == 0 
 41:                                              Second - time of end of overall time interval == 0 

 47: Statistical process used to calculate the processed field from the field at each time increment during the time range == 3 (table 4.10: Minimum) 
```

So:

reftime: 2016-01-19T12:00:00Z
forecast : 36 hours

end time: 2016-01-21T12:00:00Z

so interval is start: 2016-01-21T00:00:00Z end: 2016-01-21T12:00:00Z 

?? what think @dopplershift ??

**Comment by dopplershift** [comment]
Here's what wgrib2 has to say:
```
./wgrib2 ~/National_Blend_min_temp.grib2
1:0:d=2016011912:TMIN:2 m above ground:CodeTable 4.11=missing,missing=0:
2:781281:d=2016011912:TMIN:2 m above ground:CodeTable 4.11=missing,missing=0:
3:1537716:d=2016011912:TMIN:2 m above ground:CodeTable 4.11=missing,missing=0:
4:2317010:d=2016011912:TMIN:2 m above ground:CodeTable 4.11=missing,missing=0:
5:3081947:d=2016011912:TMIN:2 m above ground:CodeTable 4.11=missing,missing=0:
6:3844101:d=2016011912:TMIN:2 m above ground:CodeTable 4.11=missing,missing=0:
7:4632634:d=2016011912:TMIN:2 m above ground:CodeTable 4.11=missing,missing=0:
8:5416064:d=2016011912:TMIN:2 m above ground:CodeTable 4.11=missing,missing=0:
```
I can see that the 12 hour interval makes sense. My question would be: Does it exist for the 48 hour forecast? (I'm trying to dig there with ToolsUI)

**Comment by dopplershift** [comment]
I think what they're trying to encode is that this is the overnight low (0Z -> 12Z). I think it makes sense--I'm not sure if there's a better way for them to encode. In toolsUI I do see this though:

```
Grib2ProductDefinitionSection
 Interval     = (2016-01-10T21:00:00Z,2016-01-21T12:00:00Z)
```

Which is definitely is incorrect.

**Comment by dopplershift** [comment]
Or maybe this is useful from wgrib2 (I'm really just guessing):
```
./wgrib2 -RT -start_ft -vt -ftime ~/National_Blend_min_temp.grib2
1:0:RT=Start of fcst:start_ft=2016012100:vt=2016012112:CodeTable 4.11=missing,missing=0
2:781281:RT=Start of fcst:start_ft=2016012700:vt=2016012712:CodeTable 4.11=missing,missing=0
3:1537716:RT=Start of fcst:start_ft=2016012400:vt=2016012412:CodeTable 4.11=missing,missing=0
4:2317010:RT=Start of fcst:start_ft=2016012500:vt=2016012512:CodeTable 4.11=missing,missing=0
5:3081947:RT=Start of fcst:start_ft=2016012600:vt=2016012612:CodeTable 4.11=missing,missing=0
6:3844101:RT=Start of fcst:start_ft=2016012300:vt=2016012312:CodeTable 4.11=missing,missing=0
7:4632634:RT=Start of fcst:start_ft=2016012000:vt=2016012012:CodeTable 4.11=missing,missing=0
8:5416064:RT=Start of fcst:start_ft=2016012200:vt=2016012212:CodeTable 4.11=missing,missing=0
```

**Comment by dopplershift** [comment]
Interesting, here's some relevant ToolsUI dump for some NDFD grids (for which the new National Blend is supposed to be an analog):
```
 42: n - number of time range specifications describing the time intervals used to calculate the statistically processed field == 1 
 43:                                 Total number of data values missing in statistical process == 0 
 47: Statistical process used to calculate the processed field from the field at each time increment during the time range == 3 (table 4.10: Minimum) 
 48:        Type of time increment between successive fields used in the statistical processing == 255 (table 4.11: Missing) 
 49:         Indicator of unit of time for time range over which statistical processing is done == 1 (table 4.4: Hour) 
 50: Length of the time range over which statistical processing is done, in units defined by the previous octet == 12 
 54:             Indicator of unit of time for the increment between the successive fields used == 1 (table 4.4: Hour) 
 55:           Time increment between successive fields, in units defined by the previous octet == 0 
```
And here's the same for the blend:
```
 42: n - number of time range specifications describing the time intervals used to calculate the statistically processed field == 1 
 43:                                 Total number of data values missing in statistical process == 0 
 47: Statistical process used to calculate the processed field from the field at each time increment during the time range == 3 (table 4.10: Minimum) 
 48:        Type of time increment between successive fields used in the statistical processing == 255 (table 4.11: Missing) 
 49:         Indicator of unit of time for time range over which statistical processing is done == 255 (table 4.4: Missing) 
 50: Length of the time range over which statistical processing is done, in units defined by the previous octet == 255 
 54:             Indicator of unit of time for the increment between the successive fields used == 255 (table 4.4: Missing) 
 55:           Time increment between successive fields, in units defined by the previous octet == 255 
```

**Comment by JohnLCaron** [comment]
ok these assumptions match the wgrib2 output:
```
./wgrib2 -RT -start_ft -vt -ftime ~/National_Blend_min_temp.grib2
1:0:RT=Start of fcst:start_ft=      20160121 00:vt=20160121 12:CodeTable 4.11=missing,missing=0
2:781281:RT=Start of fcst:start_ft= 20160127 00:vt=20160127 12:CodeTable 4.11=missing,missing=0
3:1537716:RT=Start of fcst:start_ft=20160124 00:vt=20160124 12:CodeTable 4.11=missing,missing=0
4:2317010:RT=Start of fcst:start_ft=20160125 00:vt=20160125 12:CodeTable 4.11=missing,missing=0
5:3081947:RT=Start of fcst:start_ft=20160126 00:vt=20160126 12:CodeTable 4.11=missing,missing=0
6:3844101:RT=Start of fcst:start_ft=20160123 00:vt=20160123 12:CodeTable 4.11=missing,missing=0
7:4632634:RT=Start of fcst:start_ft=20160120 00:vt=20160120 12:CodeTable 4.11=missing,missing=0
8:5416064:RT=Start of fcst:start_ft=20160122 00:vt=20160122 12:CodeTable 4.11=missing,missing=0
```

Ive committed to my branch:

https://github.com/JohnLCaron/thredds/commit/4c9cae6a317492919fd432749ff41b01720bf2af

you might want to look it over to see how these kinds of non-standard encodings can be overridden.

still some issues, esp cust.getForecastTimeIntervalSizeInHours(Grib2Pds pds) doesnt work if the interval depends on knowing the forecast time. probably have to change the API.

**Comment by JohnLCaron** [comment]
good to know about NDFD. perhaps NwsDevLocalTables should override NdfdLocalTables, which adds some nonstandard fields.

or combine them. seems likely if ndfd is also using 255 time intervals that it is wrong. that could explain some of the trouble we have with ndfd.

**Comment by JohnLCaron** [comment]
can we track down non-standard fields used by National Blend ?

**Comment by dopplershift** [comment]
So MDL is fixing their files--will be operational in September. Here's a sample:

[grib2.blend.t00z.maxt.008-450.conus](https://files.zenhub.io/56c7877a16c1bcfd629413ee)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by JohnLCaron** [comment]
previous:

```
 48:        Type of time increment between successive fields used in the statistical processing == 255 (table 4.11: Missing) 
 49:         Indicator of unit of time for time range over which statistical processing is done == 255 (table 4.4: Missing) 
 50: Length of the time range over which statistical processing is done, in units defined by the previous octet == 255 
 54:             Indicator of unit of time for the increment between the successive fields used == 255 (table 4.4: Missing) 
 55:           Time increment between successive fields, in units defined by the previous octet == 255 
```
"fixed" version:

48:        Type of time increment between successive fields used in the statistical processing == 255 (table 4.11: Missing) 
 49:         Indicator of unit of time for time range over which statistical processing is done == 1 (table 4.4: Hour) 
 50: Length of the time range over which statistical processing is done, in units defined by the previous octet == 12 
 54:             Indicator of unit of time for the increment between the successive fields used == 1 (table 4.4: Hour) 
 55:           Time increment between successive fields, in units defined by the previous octet == 0 

seems ok in that now can use standard time interval processsing, which seems to agree with what we were doing in the override.

so i think we can assume the override is correct, and the previous PR can be ignored.
