### ISSUE TITLE
Add GeoCSV to NCSS output

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#389]
From @ethanrd 

The EarthCube GeoWS project developed a [GeoCSV text format](http://data.geows.org/documents/GeoCSV-2.0.4.pdf) that builds on the fairly recent [W3C CSV recommendation](http://www.w3.org/2013/csvw/wiki/Main_Page). It isn't (of course) a whole lot different than the "standard" NCSS text output. It would be good to get this into the TDS as an CSV output from NCSS.

**Comment by lesserwhirls** [comment]
What do you think, @dopplershift - will this make it in today or should we just put it on 5.0?

**Comment by dopplershift** [comment]
5.0.

**Comment by lesserwhirls** [comment]
Fixed in Unidata/thredds#685 for 4.6.x.

**Comment by cwardgar** [comment]
We're already tracking this in #742.
