### ISSUE TITLE
EnhanceScaleMissing getFillValue

### ISSUE THREAD

**Issue by msdsoftware** [Unidata/thredds#406]
This may well be be more of a question than an issue...

In the EnhanceScaleMissing class, there are two methods for getFillValue. The getFillValue() method returns the fill value that is explicitly specified via a variable's _FillValue attribute. The getFillValue(DataType) method, however, either returns that value or if it is not set then returns the default fill value for the data type (e.g., NC_FILL_FLOAT for floats). There seems to be an inconsistency here, although perhaps it's just that the latter method could be better named,

The question then is how should one handle data values which equal the default fill value in the case that _FillValue has not been specified? EnhanceScaleMissing returns the actual value rather than convert it to NaN.

I've had a query from a software user who argues that the netCDF user's guide implies that in the absence of an explicit _FillValue, the default fill value should still be treated as missing data. The CF convention on the other hand seems pretty clear that the _FillValue attribute is necessary.

**Comment by JohnLCaron** [comment]
> perhaps it's just that the latter method could be better named

agree

I think EnhanceScaleMissing.isMissing_() returns true under a number of possible ways for missing values to be indicated (including if FIllValue matches), and EnhanceScaleMissing.convertScaleOffset() should convert to NaN if useNaNs = true.

> in the absence of an explicit _FillValue, the default fill value should still be treated as missing data

I think you are right that its not matching on the default _FillValue, however. and I tend to think it should. What do you think?

**Comment by msdsoftware** [comment]
Personally, I don't have any great feeling either way on this aside from a preference that any documentation agree with the reality. Also, documentation needs to be a little more clear about the potential difference between "fill value" and "_FillValue", as the latter can exist without the latter.

The person who originally queried me about this pointed out that in the absence of the _FillValue attribute, some other software does report the default file value as "missing". Examples he gave were ncdump and also a Python netCDF library.

**Comment by JohnLCaron** [comment]
I think im going to implement this, but only when the underlying file is netcdf.

specifically, in a netcdf file, if a value is the default fill value, and _FillValue is not set, it will be recognized as a missing value.

**Comment by JohnLCaron** [comment]
commit 9cb23209e5545912958b301835c050392a9b3cf1

should fix
