### ISSUE TITLE
GRIB Multiple Runtime Unique Time Collection

### ISSUE THREAD

**Issue by JohnLCaron** [Unidata/thredds#409]
We've emphasized distinguishing the reference times of the collection, perhaps unduly, because we were trying to solve the problem of overlapping forecasts. This is only a real requirement when the valid times are duplicate. 

When the (valid) times are unique, one can use the time as the independent coordinate, and the reference time as the dependent. Climate models and reanalysis and observational records may not be putting so much importance on the encoded reference time in any case.

So GribCollectionImmutable.Type.MRUTC requires unique time coordinates, and use a single time coordinate. 

This is a bit laxer than MRSTC Multiple Runtime Single Time Collection, which requires that each reference time have only 1 time. in issue #357, we have unique time coordinates, but not MRSTC.

I would guess that MRUTC would be the common case, and might supplant MRSTC to the point where its not needed, and often replace MRC also.

**Comment by JohnLCaron** [comment]
A MRUTP (partition of MRUTC) may have problems making sure the partition doesnt split in a way that violate unique times??

**Comment by JohnLCaron** [comment]
MRUTX (unique times) supplants MRSTC (single times).
SRC uses same strategy (independent time, dependent runtime). I think that will be more betterer.
PR submitted

**Comment by cwardgar** [comment]
Fixed by #417
