### ISSUE TITLE
obsTime and nomTime problem for CF point netCDF file

### ISSUE THREAD

**Issue by julienchastang** [Unidata/thredds#410]
I have the following [CF point netCDF file](https://motherlode.ucar.edu/repository/entry/show/RAMADDA/Unidata/Staff/Julien+Chastang/hydro.nc?entryid=716db928-1b53-4320-97cc-e7505bb6f290) ([OpenDAP link](https://motherlode.ucar.edu/repository/opendap/716db928-1b53-4320-97cc-e7505bb6f290/entry.das)). It loads in OK into
the FeatureType API, but I notice this error message in the log.

    Error on time string = degrees_north == Can't convert from unit \"0.017453292519943295 rad\" to unit \"s\"\n

In addition to that, I see

    PointFeatureImpl {
       location=
          lat=46.16044998168945 
          lon=-96.28771209716797 
          alt=0.0, 
       obsTime=46.16044998168945, 
       nomTime=46.16044998168945, 
       timeUnit=0.0 
       seconds since 1970-01-01}

Do you see how the `lat` bleeds into the `obsTime` and `nomTime`?

This is not a show stopper since I can still get the data, but it does seem a
little odd.

**Comment by lesserwhirls** [comment]
Hi @julienchastang - which version of netCDF-Java are you using, and are you using featureType tab in toolsUI or your own java code?

**Comment by julienchastang** [comment]
@lesserwhirls Indeed this would have been useful information to supply: `4.6.3`

My own Java code, but I was hoping to capture this in a unit test hopefully today.

**Comment by lesserwhirls** [comment]
Would you mind giving 4.6.4-snapshot a try? We are hoping to release today and it would be good to see how it goes:

https://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/edu/ucar/netcdfAll/4.6.4-SNAPSHOT/netcdfAll-4.6.4-20160209.161656-44.jar

**Comment by julienchastang** [comment]
Same result. Here is a unit test to demonstrate the problem:

    @Test
    public void pointFTypeTest() throws IOException {
        Formatter errlog = new Formatter(new StringBuilder(), Locale.US);
        // You'll find the CDL at the bottom 
        String PF_DAP_URL =
            "https://motherlode.ucar.edu/repository/opendap/716db928-1b53-4320-97cc-e7505bb6f290/entry.das";
        FeatureDatasetPoint fdp =
            (FeatureDatasetPoint) FeatureDatasetFactoryManager.open(
                FeatureType.POINT, PF_DAP_URL, null, errlog);
        System.out.println(errlog);
        // Huh?
        // Error on time string = degrees_north == Can't convert from unit
        // "0.017453292519943295 rad" to unit "s"
        List<FeatureCollection> pointFeatureCollList =
            fdp.getPointFeatureCollectionList();
        PointFeatureCollection featureColl =
            (PointFeatureCollection) pointFeatureCollList.stream().findFirst()
                .get();
        // nc-java could benefit from having true iterators to take advantage of
        // Java 8 features, but I digress
        while (featureColl.hasNext()) {
            PointFeature pf = featureColl.next();
            // java.lang.AssertionError: expected:<0.0> but was:<46.22584915161133>
            Assert.assertEquals(0.0, pf.getNominalTime(), 0.0001);
        }
    }

```
netcdf dods\://motherlode\.ucar\.edu/repository/opendap/716db928-1b53-4320-97cc-e7505bb6f290/entry\.das {
dimensions:
  obs = 10;
variables:
  double streamflow(obs);
    streamflow:fill_value = 0;
    streamflow:standard_name = "River Flow";
    streamflow:coordinates = "latitude longitude time altitude";
    streamflow:units = "m^3/sec";

  float altitude(obs);
    altitude:fill_value = 0;
    altitude:standard_name = "altitude";
    altitude:axis = "Z";
    altitude:positive = "up";
    altitude:units = "m";

  float longitude(obs);
    longitude:standard_name = "longitude";
    longitude:units = "degrees_east";
    longitude:axis = "X";
    longitude:long_name = "longitude of the observation";
    longitude:fill_value = 0;

  float latitude(obs);
    latitude:standard_name = "latitude";
    latitude:units = "degrees_north";
    latitude:long_name = "latitude of the observation";
    latitude:axis = "Y";
    latitude:fill_value = 0;

  double time(obs);
    time:standard_name = "time";
    time:units = "days since 1970-01-01 00:00:00";
    time:calendar = "julian";
    time:long_name = "time of measurement";
    time:axis = "T";
    time:fill_value = 0;

// global attributes:
:Conventions = "CF-1.6";
:Metadata_Conventions = "Unidata Dataset Discovery v1.0";
:cdm_data_type = "Point";
:featureType = "station";
:nodc_template_version = "NODC_NetCDF_Grid_Template_v1.1";
data:
streamflow =
{5.165988695807755E-4, 9.78793905233033E-5, 0.01733524352312088, 0.056477807462215424, 0.005832814611494541, 4.161571996519342E-5, 2.4128601944539696E-4, 0.004659316502511501, 5.376061308197677E-4, 2.3537117522209883E-4}
altitude =
{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}
longitude =
{-96.534904, -96.531296, -96.514854, -96.61524, -96.65766, -96.38939, -96.38777, -96.60506, -96.52925, -96.28771}
latitude =
{46.22585, 46.216797, 46.209972, 46.205326, 46.195614, 46.193188, 46.17902, 46.174908, 46.167233, 46.16045}
time =
{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}
}
```

**Comment by julienchastang** [comment]
As @lesserwhirls pointed out over a lunch time conversation, the netCDF described above is not CF compliant with respect to the `featureType` with an incorrectly labeled  `station` global attribute. It should be `point` though the [NODC template](https://www.nodc.noaa.gov/data/formats/netcdf/v1.1/point.cdl), which in most cases is a valuable resource, is apparently giving incorrect advice in this area by recommending a `station` `featureType`. Also what is "REQUIRED" by the NODC template is not totally clear in practice. The [CF documentation](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#_point_data), recommends a `featureType` of `point` and does not mention anything about the `cdm_data_type`. For the record, I include an [updated and corrected DAP URL](https://motherlode.ucar.edu/repository/opendap/c745488e-6739-40c3-ae75-9d94d1513a6b/entry.das) with the CDL below. Thanks @lesserwhirls for the informative discussion! Closing, as I see no further issues here.

    netcdf hydro {
    dimensions:
      obs = 5 ;
    variables:
      double time(obs) ;
        time:standard_name = "time" ;
        time:units = "days since 1970-01-01 00:00:00" ;
        time:calendar = "julian" ;
        time:long_name = "time of measurement" ;
        time:axis = "T" ;
        time:fill_value = 0 ;
      float latitude(obs) ;
        latitude:standard_name = "latitude" ;
        latitude:units = "degrees_north" ;
        latitude:long_name = "latitude of the observation" ;
        latitude:axis = "Y" ;
        latitude:fill_value = 0 ;
      float longitude(obs) ;
        longitude:standard_name = "longitude" ;
        longitude:units = "degrees_east" ;
        longitude:long_name = "longitude of the observation" ;
        longitude:axis = "X" ;
        longitude:fill_value = 0 ;
      float altitude(obs) ;
        altitude:units = "m" ;
        altitude:standard_name = "altitude" ;
        altitude:axis = "Z" ;
        altitude:positive = "up" ;
        altitude:fill_value = 0 ;
      double streamflow(obs) ;
        streamflow:units = "m^3/sec" ;
        streamflow:standard_name = "River Flow" ;
        streamflow:coordinates = "time latitude longitude altitude" ;
        streamflow:fill_value = 0 ;
      double qlateral(obs) ;
        qlateral:units = "m^3/sec" ;
        qlateral:standard_name = "Runoff" ;
        qlateral:coordinates = "time latitude longitude altitude" ;
        qlateral:fill_value = 0 ;
    
    // global attributes:
        :Conventions = "CF-1.6" ;
        :Metadata_Conventions = "Unidata Dataset Discovery v1.0" ;
        :cdm_data_type = "Point" ;
        :featureType = "point" ;
        :nodc_template_version = "NODC_NetCDF_Grid_Template_v1.1" ;
    data:
    
     time = 0, 0, 0, 0, 0 ;
    
     latitude = 46.22585, 46.2168, 46.20997, 46.20533, 46.19561 ;
    
     longitude = -96.5349, -96.5313, -96.51485, -96.61524, -96.65766 ;
    
     altitude = 0, 0, 0, 0, 0 ;
    
     streamflow = 0.000516598869580775, 9.78793905233033e-05, 0.0173352435231209, 
        0.0564778074622154, 0.00583281461149454 ;
    
     qlateral = 0.000516598869580775, 9.78776515694335e-05, 0.0173297505825758, 
        0.0564712174236774, 0.00583280017599463 ;
    }

**Comment by julienchastang** [comment]
For the record, here is the [updated v2.0 NODC point template cdl](https://www.nodc.noaa.gov/data/formats/netcdf/v2.0/point.cdl) with the corrected `featureType` of `point`.

**Comment by lesserwhirls** [comment]
Do they still include the cdm_data_type attribute?

**Comment by julienchastang** [comment]
Apparently, yes  `:cdm_data_type = "Point"` though it is only "SUGGESTED".
