### ISSUE TITLE
Unknown Unit from GRIB - degree.true

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#449]
NDFD grids have a variable with units of degree.true. This unit should be cleaned up to be udunits compatible. Possible place to clean this would be `cleanUnit` method in `ucar.nc2.wmo.Util.`

See [here](http://thredds.ucar.edu/thredds/catalog/grib/NCEP/NDFD/NWS/CONUS/NOAAPORT/catalog.html) for an example.

**Comment by dopplershift** [comment]
Well, for starters we should stop putting the period in there. This is the actual code in `cleanUnit`:
```java
  static public String cleanUnit(String unit) {
    if (unit == null) return null;
    if (unit.equalsIgnoreCase("-")) unit = "";
    else {
      if (unit.startsWith("/")) unit = "1" + unit;
      unit = unit.trim();
      unit = StringUtil2.remove(unit, "**");
      StringBuilder sb = new StringBuilder(unit);
      StringUtil2.remove(sb, "^[]");
      StringUtil2.replace(sb, ' ', ".");
      StringUtil2.replace(sb, '*', ".");
      unit = sb.toString();
    }
    return unit;
  }
```
Note the `StringUtil2.replace(sb, ' ', ".");`. Easy fix would be to use `_` instead of `.` for space replacement, as I don't think the latter will ever help us get a udunits compatible unit. It should also be noted that this comes from the WMO table, which overrides NCEP's unit of "true".

@JohnLCaron any comment here?

**Comment by JohnLCaron** [comment]
Lets see. What we dont want to do is to "hand correct" tables, which have
to be done each time we update tables. But its ok to have some
automatically applied cleaning algorithm.

Now, whats our goal of cleaning?

1. Mostly to reduce cruft. The WMO tables have crap in them, notes,
subjunctive clauses, grocery lists, table scraps, etc. These have mostly
slowly been getting better over the years.

2. Secondarily to transform to udunit notation when it can be done
correctly. Which requires human supervision in some cases, but shit, life
it short. We do not rely on units being udunits. I think a reasonable
alternative is to have a different algorithm try to make udunits out of the
units, and some tooling for a human to review that periodically. Then
generate a seperate udunits attribute. F*k CF compliance.

3. the "." is udunits for multiplication, so "*" get converted to "."

There are numerous inconsistencies in how this cleanup is applied to
various tables, which could be reviewed and standardized. But the human
review of dozens of tables from different sources is a time sink.

**Comment by JohnLCaron** [comment]
"F*k CF compliance." is coded message meaning, "do this right in CF-2.0",
which is a coded message meaning "dont let any of the original CF authors
have anything to do with CF-2.0". Probably including me in that "do not
include" ;^)

**Comment by dopplershift** [comment]
I see. Converting space to '.' allows units like "kg m-2" to become "kg / m^2" (or whatever udunits does).

Currently in the wmo xml tables (including latest version I just grabbed), units seem with spaces seem to be:
- multiplicative (e.g. "kg m-2")
- "degree true"
- "Code table a.bbb"
and a few other odds and ends.

In the name of expediency, call it "we won't prematurely generalize" :grin:, how about we just whitelist (i.e. specifically handle) "degree true"? To me this is the only case that is unhandled by the current code and is clear what the correct answer is.
