### ISSUE TITLE
Get threddsIso into TDS 5.0.0

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#495]
I've updated threddsIso to use the new 5.0 API. See here:

Unidata/threddsIso#16

The next step is to hook threddsIso back up to the TDS and see if things still work as intended. The tests in the threddsIso reop pass at this point, but I'll be happier to see it in action without any 500s :-)

**Comment by lesserwhirls** [comment]
https://github.com/Unidata/thredds/issues/526#issuecomment-231434403

**Comment by rsignell-usgs** [comment]
We deployed the TDS artifact 
http://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/edu/ucar/tds/5.0.0-SNAPSHOT/tds-5.0.0-20160708.184540-12.war
which we thought was supposed to fix the ISO issue on 5.0, but we are still having the same bug/issue.

For example this dataset:
http://gamone.whoi.edu/thredds/catalog/coawst_4/use/fmrc/catalog.html?dataset=coawst_4/use/fmrc/coawst_4_use_best.ncd
returns 404 for the ISO link. 

@lesserwhirls, any ideas?

**Comment by lesserwhirls** [comment]
Hi @rsignell-usgs! Sorry for the delay, but I was out all last week in the land of no internet. The snapshot was only intended to address the wms issue, and so far I do not have the ISO service working in 5 (going to try to get it working this week).

**Comment by rsignell-usgs** [comment]
@lesserwhirls , just checked today and ISO service still not working on TDS5.0, correct?
http://thredds-jumbo.unidata.ucar.edu/thredds/iso/grib/NCEP/GFS/Global_2p5deg/Best?catalog=http%3A%2F%2Fthredds-jumbo.unidata.ucar.edu%2Fthredds%2Fcatalog%2Fgrib%2FNCEP%2FGFS%2FGlobal_2p5deg%2Fcatalog.html&dataset=grib%2FNCEP%2FGFS%2FGlobal_2p5deg%2FBest

**Comment by lesserwhirls** [comment]
Hi @rsignell-usgs - that's correct. My surgery really kicked my butt, and I am just now getting back into things. I am finishing up work on getting godiva3 working, and ncIso is next on the list. Apologies that this is taking so long, and we appreciate your willingness to test and provide feedback!

**Comment by rsignell-usgs** [comment]
> My surgery really kicked my butt
So hemorrhoid surgery?  :laughing: 

Seriously though, I'm excited about these enhancements getting into TDS5.0.   The ncWMS2 guys, when they release the new version, will have both UGRID and SGRID support, which will be HUGE!   :trumpet:

**Comment by lesserwhirls** [comment]
Nah, no hemorrhoid surgery...I did [this](https://en.wikipedia.org/wiki/Uvulopalatopharyngoplasty) as well as a septoplasty and nasal turbinate reduction.

But, on a happier and much less painful note, the ISO services are added in PR Unidata/thredds#619. Once the tests pass (fingers crossed) and the PR is merged, I'll deploy new artifacts and update thredds-test.

**Comment by lesserwhirls** [comment]
Ok, the latest artifact can be found here:

https://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/edu/ucar/tds/5.0.0-SNAPSHOT/tds-5.0.0-20160825.211516-18.war

However, I'm guessing things will still not work with your catalogs @rsignell-usgs - not sure why, but I'm digging into it. Also, thredds-test is updated with the latest artifact now.

**Comment by rsignell-usgs** [comment]
I deployed this artifact and can confirm that ISO is working! 
http://gamone.whoi.edu/thredds/iso/bathy/etopo2_v2c.nc?catalog=file%3A%2Fopt%2Ftomcat%2Fcontent%2Fthredds%2Fglobal_bathy.xml&dataset=bathy%2Fetopo2_v2c.nc

Unfortunately, as you suspected, WMS is not:
http://gamone.whoi.edu/thredds/wms/bathy/etopo2_v2c.nc?service=WMS&version=1.3.0&request=GetCapabilities

returning:
`The location bathy/etopo2_v2c.nc doesn't refer to any existing files.`
