### ISSUE TITLE
Long global attributes skipped by toolsUI-4.3.jar

### ISSUE THREAD

**Issue by ggalibert** [Unidata/thredds#50]
It looks like global attributes which reaches a certain length are not well processed by toolsUI-4.3.jar.

This file for example 

http://thredds.aodn.org.au/thredds/fileServer/IMOS/ANMN/NSW/PH100/Velocity/IMOS_ANMN-NSW_AETVZ_20131127T230000Z_PH100_FV01_PH100-1311-Workhorse-ADCP-109.5_END-20140306T010000Z_C-20140521T053527Z.nc  

has a quality_control_log global attribute which is not provided, although a simple 

ncdump -h IMOS_ANMN-NSW_AETVZ_20131127T230000Z_PH100_FV01_PH100-1311-Workhorse-ADCP-109.5_END-20140306T010000Z_C-20140521T053527Z.nc | grep "quality_control_log"

can show it.

ncdump -h http://thredds.aodn.org.au/thredds/dodsC/IMOS/ANMN/NSW/PH100/Velocity/IMOS_ANMN-NSW_AETVZ_20131127T230000Z_PH100_FV01_PH100-1311-Workhorse-ADCP-109.5_END-20140306T010000Z_C-20140521T053527Z.nc | grep "quality_control_log"

doesn't show anything via OPeNDAP, so I'm guessing OPeNDAP might be using toolsUI or similar code to render the global attributes.

**Comment by JohnLCaron** [comment]
should be fixed in 4.5.4, commit d7d9327aed766f68bcbbd364acfbd3677f568eaf
