### ISSUE TITLE
Java write data error : -57

### ISSUE THREAD

**Issue by r0perice** [Unidata/thredds#516]
Hello,

I have troubles writting an Array of unsigned short to a variable.

* My variable is :
```bash
short effective_radiance(rows=344, columns=22272);
_Unsigned = "true";
```

*  To write the Array I'm doing :
```java
 arr = MAMath.convert(Array.factory(value), DataType.SHORT);
                    arr.setUnsigned(true);
                    try {
                        writer.write(var, arr);
                    } catch (IOException | InvalidRangeException e) {
                        e.printStackTrace();
                    }
```
Where `value` is a Array of type `int` (in my processing chain I have converted the input array of unsigned short into array of int).

* I have the following error :  

>java.io.IOException: -57: NetCDF: Start+count exceeds dimension bound   
at ucar.nc2.jni.netcdf.Nc4Iosp.writeData(Nc4Iosp.java:2915)
	at ucar.nc2.jni.netcdf.Nc4Iosp.writeData(Nc4Iosp.java:2823)

From documentation : [link](http://www.unidata.ucar.edu/software/netcdf/docs/netcdf_8h.html#a5441fb87f6d34a4b84eafcec089d18e4)

I really don't understand the problem because `arr.size()`  is `7661568`. That match with dimension of my Variable (`344 * 22272 = 7661568`).

Any help appreciated.

Regards,

Robin

**Comment by DennisHeimbigner** [comment]
Assuming it is not too big, can you send me the whole program?

**Comment by r0perice** [comment]
I can't give you the entire code but I can provide some extracts :  
* [**NetcdfReadSnippet.java**](https://gist.github.com/r0perice/bebd9f0c46ad006151d5eff324594b84) contains the functions for reading Variable data and convert unsigned type to corresponding java type.  
* [**NetcdfWriteSnippet.java**](https://gist.github.com/r0perice/f85603724ed093f5da3cc8e150da9045)  contains the part of my writting wich cause troubles.

**Comment by r0perice** [comment]
I think my problem is :  
* In input I have converted the multidimensional array to 1D array using `copyTo1DJavaArray`.
* For the moment I haven't converted my 1D Array to nD array when I try to write the file so I'm out of thebounds of  dimension.

I'm looking on how to do that.

**Comment by r0perice** [comment]
So I solved the problem using :

```java
 final Array arrIntD2 = MAMath.convert(Array.factory(value), DataType.SHORT);
                        final ArrayShort.D2 arrID2 = new ArrayShort.D2(var.getDimension(0).getLength(),
                                var.getDimension(1).getLength());
                        Array.arraycopy(arrIntD2, 0, arrID2, 0, (int) arrIntD2.getSize());
                        arrID2.setUnsigned(true);

                        try {
                            writer.write(var, arrID2);
                        } catch (IOException | InvalidRangeException e) {
                            e.printStackTrace();
                        }
```

Not sure it's the good way to do that but it works for the moment.

**Comment by r0perice** [comment]
Sorry for bad referenced issue. I think you can close this issue.

Regards.

Robin
