### ISSUE TITLE
RDA time coordinates incorrectly mapped to GRIB records

### ISSUE THREAD

**Issue by JohnLCaron** [Unidata/thredds#576]
Report on ds628.0_fcst_surf from RDA user:

Hi Dave, hope life is treating you well and you got through the el nino winter alright. DOwn here in Perth, it's starting off  quite wet with a very stormy may.

I have been using  the RDA data quite a lot in my work, in particular the JRA55 data to drive storm surge models. We are finding it does quite well for Australia and it's particularly good in the way that tropical  cyclones are in the correct location, which is not the case for ERA-I.

For the earlier cases I just did the data subset requests through the web brower as i didn't realise that  I had access to the thredds/opendap server. We are planning on doing a multi-year run and I was happy to find the server and the ncss functionality and that I can download with wget. Very useful!

However, I downloaded a year of data  from the 3-hourly  0.5 deg instantaneous 2d  and Best datasets (see ncss request below). But we are having trouble deciphering what has happened to the time dimension organisation of the files.

If I load the time variable (best) and convert I get nicely ordered times (2010-12-31 21:00z to 2012-01-01 00:00z)

But the corresponding data appears to be mixed up in the time dimension so when i plot each timestep or  the mslp for example, the storms move back and forth in time - ie. it appears to be in the order    6hr  3hr  12h 9hr r etc.

As a workaround I have tried to reorder the data so that the it looks nice and doesn't shift back and forth as you move forward in time.  But then I have an issue of the second (and last)  timesteps being NaN's .

I think i can resolve this by eliminating those and cutting the first and last of the time variable which leaves me with data (i think) corresponding to 2011-01-01 00:00z to 2011-12-31 21:00z.

I have tested for a know storm event, but  I am wary of messing this up and getting the wrong times.

Am I missing something?  Do you know what's going on here?

I also tried with the other (non-best) version with has an extra dimension  Pressure_reduced_to_MSL_msl(reftime, time, lat, lon)  and got  got the same results.

Hopefully this isn't too confusing and my question makes sense.  I was very confused!

Thanks for your time.

Cheers
yasha

ncss request:

http://rda.ucar.edu/thredds/ncss/aggregations/JRA55/ds628.0/27/Best?var=Pressure_reduced_to_MSL_msl&var=u-component_of_wind_height_above_ground&var=v-component_of_wind_height_above_ground&disableProjSubset=on&horizStride=1&time_start=2010-12-31T21%3A00%3A00Z&time_end=2012-01-01T00%3A00%3A00Z&timeStride=1&vertCoord=&addLatLon=true&accept=netcdf

Yasha Hetzel 
Research Assistant Professor

The University of Western Australia
School of Civil, Environmental, and Mining Engineering  & UWA Oceans Institute
M470          
35 Stirling Highway
Crawley, WA 6009 
AUSTRALIA

Email: yasha.hetzel@uwa.edu.au

**Comment by JohnLCaron** [comment]
MRUTC, 1485 runtimes (~365 x 4)

   2011-12-31T18:00:00Z (0.000000)
   2012-01-01T00:00:00Z (6.000000)
   2012-01-01T06:00:00Z (12.000000)
   2012-01-01T12:00:00Z (18.000000)
   ...
   2012-12-31T00:00:00Z (8766.000000)
   2012-12-31T06:00:00Z (8772.000000)
   2012-12-31T12:00:00Z (8778.000000)
   2012-12-31T18:00:00Z (8784.000000)

they've written the 12-31T18:00:00Z twice

offsets are 0 and 3.

time Starts at 2011-12-31T18:00:00Z, 3 hour forecast ( 0 is missing)
  udunits = "Hour since 2011-12-31T18:00:00Z"
  npts: 2930 [3.000000,8790.000000] spacing=regularPoint resolution=3.000000

reftime: CoordAxis 'reftime' (ucar.nc2.ft2.coverage.CoverageCoordAxis1D) dependent : time
  units = "Hour since 2011-12-31T18:00:00Z"
  npts: 2930 [0.000000,8784.000000] spacing=irregularPoint
  contiguous values (2930)=0.000000,0.000000,6.000000,6.000000,12.000000,12.000000,18.000000,18.000000,24.000000,24.000000,30.000000,30.000000,36.000000,36.000000,...

Note we have 0, 0. Which means time should have been 0, 3... but instead starts at 3....

**Comment by JohnLCaron** [comment]
overall index is TwoD, Best, instead of MRUTC.

offsets are 3, 6

 2992930 Jun 17 23:44 ds628.0_fcst_surf.ncx4

get 2013 and try running indexer locally? ie why does it create a 2D?
Possible because of the single time overlap, which sucks.

**Comment by JohnLCaron** [comment]
TestGrib1CoordsMatchGbx (not checked in yet)

Time coord = 3.000000 date = 2011-12-31T21:00:00Z
 doesnt exist
Time coord = 6.000000 date = 2012-01-01T00:00:00Z
 reference=2011-12-31T18:00:00Z forecast = 2012-01-01T00:00:00Z
Time coord = 9.000000 date = 2012-01-01T03:00:00Z
 reference=2012-01-01T00:00:00Z forecast = 2012-01-01T06:00:00Z
Time coord = 12.000000 date = 2012-01-01T06:00:00Z
 reference=2012-01-01T00:00:00Z forecast = 2012-01-01T03:00:00Z
Time coord = 15.000000 date = 2012-01-01T09:00:00Z
 reference=2012-01-01T06:00:00Z forecast = 2012-01-01T12:00:00Z
Time coord = 18.000000 date = 2012-01-01T12:00:00Z
 reference=2012-01-01T06:00:00Z forecast = 2012-01-01T09:00:00Z
...

**Comment by JohnLCaron** [comment]
Problem is in CoordinateND.reindex(), for time2D coordinates.

Preliminary testing with GribCoordsMatchGbx indicates it affects a bit less that 1% of all variables, across all dataset collections. Once fixed, all collections will need to be reindexed.

**Comment by JohnLCaron** [comment]
Have this fixed. Improving unit tests so we can detect any more problems.

**Comment by JohnLCaron** [comment]
https://github.com/Unidata/thredds/pull/603

**Comment by cwardgar** [comment]
#603 has been merged, but we haven't recreated the indexes for 5.0.0 yet nor deployed a new shapshot. I'm gonna leave this issue open until we do.

@lesserwhirls I can give this a shot using the notes I took from last time. However, I'm sure I'll run into a roadblock at some point. I'm probably not even in the sudoers file. Do you want to do it?

**Comment by lesserwhirls** [comment]
Sure think - I'll take care of this.

**Comment by lesserwhirls** [comment]
Should be about good to rock n roll on dev and test now...just waiting for the index files to be updated.

**Comment by cwardgar** [comment]
Great. Thanks, Sean!
