### ISSUE TITLE
Seg fault when using multi threading Netcdf-Java

### ISSUE THREAD

**Issue by LupusUmbrae** [Unidata/thredds#577]
Hello,

I was experimenting with trying to improve the write performance with the NetCDF-Java library (v4.6.5 & v4.6.6) by putting each file i write to in a new thread. This however did not end well.

I've attached a simple piece of code that can be used to replicate the error, just simple change the number of threads to 1 to see it work without crashing.

[NetcdfThreads.txt](https://github.com/Unidata/thredds/files/337091/NetcdfThreads.txt)
[hs_err_pid2499.txt](https://github.com/Unidata/thredds/files/337118/hs_err_pid2499.txt)

I had to compile the NetCDF library locally to get v4.4.0 so it's always possible I'm missing a flag needed at compile time, but couldn't see anything obvious in the compile docs.

```
NetCDF-4 C library loaded (jna_path='null', libname='netcdf').
NetCDF-4 C library loaded (jna_path='null', libname='netcdf').
NetCDF-4 C library loaded (jna_path='null', libname='netcdf').
NetCDF-4 C library loaded (jna_path='null', libname='netcdf').
Netcdf nc_inq_libvers='4.4.0 of Jun  2 2016 16:34:09 $' isProtected=false
Netcdf nc_inq_libvers='4.4.0 of Jun  2 2016 16:34:09 $' isProtected=false
Netcdf nc_inq_libvers='4.4.0 of Jun  2 2016 16:34:09 $' isProtected=false
Netcdf nc_inq_libvers='4.4.0 of Jun  2 2016 16:34:09 $' isProtected=false
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa583af967e, pid=16235, tid=140349870167808
#
# JRE version: OpenJDK Runtime Environment (8.0_91-b14) (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.91-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libnetcdf.so+0x3a67e]  NC_create+0x12e
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/robin/workspace/netcdf-threads/hs_err_pid16235.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**nc-config --all**
```
This netCDF 4.4.0 has been built with the following features: 

  --cc        -> gcc
  --cflags    ->  -I/usr/local/include -I/usr/local/include
  --libs      -> 

  --has-c++   -> no
  --cxx       -> 
  --has-c++4  -> no
  --cxx4      -> 

  --fc        -> 
  --fflags    -> 
  --flibs     -> 
  --has-f90   -> no

  --has-dap   -> no
  --has-nc2   -> yes
  --has-nc4   -> yes
  --has-hdf5  -> yes
  --has-hdf4  -> no
  --has-pnetcdf-> no

  --prefix    -> /usr/local
  --includedir-> /usr/local/include
  --version   -> netCDF 4.4.0
```

**Comment by lesserwhirls** [comment]
Hi @LupusUmbrae, unfortunately, HDF5 and netCDF-C are not threads safe,, so we can't do threaded netCDF4 writes. 😞

**Comment by LupusUmbrae** [comment]
Just to clarify, which (or both) is true:

1. NetCDF cannot write to the same file in multiple threads (i.e. Thread 1&2 writing to File1)
2. NetCDF cannot be used in more than one thread, even to write to separate files (i.e. Thread 1 writing to File1 & Thread 2 writing to File2)

As i was hoping the second was an option, but if its not never mind.. back to single threaded

**Comment by lesserwhirls** [comment]
Greetings @LupusUmbrae, unfortunately I think it is both 1 and 2. I think the netCDF-C layer has some shared global state which prevents both of these. @DennisHeimbigner, is that correct?

**Comment by DennisHeimbigner** [comment]
Case #1 is not likely to happen any time soon because of the complexity of the changes required.
We are working on #2; the (partial) solution being, of course, to isolate global state. Once complete,
it should be the case that for netcdf-3 (classic) files, #2 should work correctly.,
The problem for netcdf-4 files is that it depends on the HDF5 library. You can compile the HDF5 library
with thread-safetly enables, but it does so by a global lock serializing all calls into the HDF5 library.
This means that #2 will work, but there will be no performance gain. I encourage you to send a
request to the HDF group asking them to add finer-grain concurrency to their library.
In the meantime, if you do not need chunking, then you might consider using the pnetcdf
support in the netcdf-c library. This uses MPIO and can improve performance.

**Comment by LupusUmbrae** [comment]
Thanks for the clarifications @DennisHeimbigner @lesserwhirls, i'll stick with non-multithreaded for the time being and look at it again if/when i need to
