### ISSUE TITLE
Array support for Unlimited dimension

### ISSUE THREAD

**Issue by LupusUmbrae** [Unidata/thredds#581]
Hello,

I'd like to reduce the number of calls i have to [NetcdfFileWriter.write()](https://github.com/Unidata/thredds/blob/5.0.0/cdm/src/main/java/ucar/nc2/NetcdfFileWriter.java#L1038) as i'm seeing the [Nc4Iosp.writeData()](https://github.com/Unidata/thredds/blob/5.0.0/netcdf4/src/main/java/ucar/nc2/jni/netcdf/Nc4Iosp.java#L2789) taking a lot of my CPU time. It's averaging about >3000 nan-seconds, which isn't bad by itself but it looks like i'll have hundreds of thousands/millions of calls to writing.

I started looking at buffering on the Java side, by collecting all the data and converting them into an [Array](https://github.com/Unidata/thredds/blob/5.0.0/cdm/src/main/java/ucar/ma2/Array.java), however i hit a problem when i had variables with an Unlimited dimension, i could not see any way to create an Array that would support that.

Have i missed something in Array, or it's subclasses that allows me to store multiple rows of data for a variable that has an unlimited dimension (example NcML below).

```
 <dimension name="rows" length="45000"/>
 <dimension name="orphan_pixels" length="1" isUnlimited="true" />

<variable name="x_orphan_i${v}" shape="rows orphan_pixels" type="int">
    <attribute name="long_name" value="Geolocated x (across track) coordinate of detector FOV centre" />
    <attribute name="units" value="m" />
    <attribute name="scale_factor" type="double" value="0.01" />
    <attribute name="add_offset" type="double" value="0" />
    <attribute name="_FillValue" type="int" value="-1000000" />
  </variable>
```

Any suggestion of how to go forward would be appreciated,
Robin

**Comment by cwardgar** [comment]
Hi Robin,

I took your NcML sample and tried to write it out as a NetCDF-4 file using ToolsUI. I got an error:
```
Exception in thread "AWT-EventQueue-0" java.lang.AssertionError
	at ucar.nc2.jni.netcdf.Nc4Iosp.writeData(Nc4Iosp.java:2852)
	at ucar.nc2.jni.netcdf.Nc4Iosp.writeData(Nc4Iosp.java:2789)
	at ucar.nc2.NetcdfFileWriter.write(NetcdfFileWriter.java:954)
	at ucar.nc2.NetcdfFileWriter.write(NetcdfFileWriter.java:938)
	at ucar.nc2.FileWriter2.copyAll(FileWriter2.java:431)
	at ucar.nc2.FileWriter2.copyVarData(FileWriter2.java:384)
	at ucar.nc2.FileWriter2.write(FileWriter2.java:199)
	at ucar.nc2.FileWriter2.write(FileWriter2.java:176)
	at ucar.nc2.ncml.NcMLReader.writeNcMLToFile(NcMLReader.java:1652)
	at ucar.nc2.ui.NcmlEditor.writeNetcdf(NcmlEditor.java:289)
	at ucar.nc2.ui.NcmlEditor$5$1.propertyChange(NcmlEditor.java:159)
```
That's a bug, and I think I've already tracked it down. Is that what you're seeing or are you getting something different? Are you trying to create the `Array`s programmatically.?

**Comment by cwardgar** [comment]
Bug fixed in #587.

**Comment by LupusUmbrae** [comment]
Hi @cwardgar im talking more about this (pseudo code below):

I want to gather in memory a collection of different length arrays, then write them in one operation to a netcdf file. 

```
private ArrayDouble buffer = new ArrayDouble.D2(10, Unlimited); // No obvious support for unlimited here

private final NetcdfFileWriter netcdfFileWriter;

public void addRow(int rowIndex, double[] data){
   for(int i =0; i < data.length, i++){
      buffer.set(rowIndex, i, data[i]);
   }
}

public void flush() {
 ....
 this.netcdfFileWriter.write(var, origin, buffer );
 ....
}

```

So specifically in our situation we are processing a satellite image and re gridding the pixels onto the Earth, when we get a pixel that has a Lat/Lon that another pixel has already filled we call it an Orphan. This means that the specification calls for an unlimited length dimension.

The other issue we are seeing is that we have some performance issues, and one suggestion was to look at doing sequential writing of the data, but the only way for us to do that is by collecting the data and then writing it.

I write a very basic buffer (bit like the code above) but found that it just wouldn't work for a none fixed shape, i was then hoping that i just was missing a way to store data for a variable with an unlimited dimension.

Hope that clears it up

Robin

**Comment by cwardgar** [comment]
Here is some example code that writes to a variable whose *inner-most* (right-most) dimension is unlimited. This is only possible with NetCDF-4; NetCDF-3 requires that the unlimited dimension be *outer-most*.

```java
        File outFile = tempFolder.newFile("innermostUnlimitedDimension.nc4");

        try (NetcdfFileWriter writer = NetcdfFileWriter.createNew(
                NetcdfFileWriter.Version.netcdf4, outFile.getAbsolutePath())) {
            int numRows = 2;
            int numCols = 5;

            Dimension rowDim = writer.addDimension(null, "row", numRows, true, false, false);
            Dimension colDim = writer.addDimension(null, "col", 0, true, true, false);  // Start at 0 cols.
            Variable tableVar = writer.addVariable(null, "table", DataType.INT, "row col");
            writer.create();

            for (int iCol = 0; iCol < numCols; ++iCol) {  // Add columns.
                int[] origin = new int[] { 0, iCol };
                int[] shape  = new int[] { numRows, 1 };

                int[] data = new int[numRows];
                for (int iRow = 0; iRow < numRows; ++iRow) {
                    int val = numRows * iCol + iRow;
                    data[iRow] = val;
                }
                Array values = Array.factory(DataType.INT, shape, data);

                writer.write(tableVar, origin, values);
            }
        }
```
That'll create a file that looks like:
```
$ ncdump innermostUnlimitedDimension.nc4
netcdf innermostUnlimitedDimension {
dimensions:
	row = 2 ;
	col = UNLIMITED ; // (5 currently)
variables:
	int table(row, col) ;
data:

 table =
  {0, 2, 4, 6, 8},
  {1, 3, 5, 7, 9} ;
}
```
Your code mentions that you're trying to add rows instead of columns, but your `rows` dimension is not unlimited (in the NcML), so I was a bit confused about your intentions. Nonetheless, hopefully my code will help you do what you're trying to do.

**Comment by cwardgar** [comment]
I also added a test for writing a variable with multiple unlimited dimensions (#589). It's more complex than what you're trying to do, but could be useful.

**Comment by LupusUmbrae** [comment]
Taken me ages to realise it.. but i think the Issue is the NetCDF specification we've been given is using 'unlimited' as 'vlen'.. How ever I see NetCDF-Java doesn't support VLEN for NetCDF 4, which cold be the reason for the use of Unlimited.

It does concern me if this is the case as could this not potentially have a big performance impact? say if i wrote 10,000 lines and the max size is 10, then the 10,001 is 100 in size would this not force the previous 10,000 to be re-written to make them all the same size?

**Comment by JohnLCaron** [comment]
Would be helpful to see the C code that would do what you want. (And some timing on how fast that is. Not convinced vlens are a very good idea for large data, but i could be wrong) Anyway, if we see the C code, it will be clearer on how to emulate it in Java.

**Comment by cwardgar** [comment]
@LupusUmbrae Unlimited dimensions still require rectangular arrays. As you can see in my [expandUnlimitedDimensions() test](8acb5bc040cc9044c4059a30d09f3626b779ae98), whenever I add rows or columns to the array, fill values are also inserted automatically to keep the array rectangular. So yes, performance hits like the one you mentioned are a very real possibility.

VLEN dimensions can give you ragged arrays, which I think is what the specification is really calling for. But as you say, NetCDF-Java does not currently support them.

I'm gonna close this now, as the original bug concerning unlimited dimensions has been found and squashed. Feel free to re-open if you'd like to provide the C code that John mentioned. I think that would help us to add VLEN support in NetCDF-Java.
