### ISSUE TITLE
Fix dataset layer title on TDS5/ncWMS2 getCapabilities

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/thredds#608]
@lesserwhirls , the overall layer title on TDS5/ncWMS2 getCapabilities is coming back as "Dataset title" instead of the the dataset name (like "WW3-Global.ncx3", as it did in TDS4/ncWMS):  

Example:

TDS5/ncWMS2:
http://thredds-jumbo.unidata.ucar.edu/thredds/wms/grib/NCEP/WW3/Global/Best?service=WMS&version=1.3.0&request=GetCapabilities

```
<Layer>
<Title>Dataset title</Title>
```

TDS4/ncWMS:
http://thredds.ucar.edu/thredds/wms/grib/NCEP/WW3/Global/Best?service=WMS&version=1.3.0&request=GetCapabilities

```
<Layer>
<Title>WW3-Global.ncx3</Title>
```

**Comment by lesserwhirls** [comment]
Thanks for the heads-up @rsignell-usgs.
