### ISSUE TITLE
Null Earth object passed to CylindricalEqualAreaProjection

### ISSUE THREAD

**Issue by msdsoftware** [Unidata/thredds#611]
@lesserwhirls has seen some e-mail flying about related to this query, but I'll post here in case anyone else has any thoughts.

The second constructor for `CylindricalEqualAreaProjection` accepts as its final parameter an object of class `Earth`. If this object is null, then several lines down when there is a query for the Earth's eccentricity there will be a NullPointerException.

The constructor for `CylindricalEqualAreaProjection` is invoked in `LambertCylindricalEqualArea`, which extends `AbstractCoordTransBuilder`. The `Earth` object is created in `AbstractCoordTransBuilder`, but _only if_ the grid mapping variable has defined both the semi_major_axis and semi_minor_axis attributes or if the inverse_flattening attributed is defined. Otherwise, the object is not created.

A user of my Panoply software has been working with a dataset in which the cylindrical equal-area grid mapping variable is somewhat under-defined in its attributes. This means that when one tries to open the dataset in enhanced-mode, the dataset cannot be opened because the analysis of the dataset's coordinate system(s) is failing with the above NullPointerException.

Patching this seems easy enough — just modify `AbstractCoordTransBuilder` to create a default `Earth` object using the no-parameter constructor if the necessary attributes aren't present — but I am wondering if this is the best place to check that. Several other classes that extend `AbstractCoordTransBuilder` have their own invocations of the `Earth` constructor, so perhaps it should instead be done in `LambertCylindricalEqualArea`?

**Comment by msdsoftware** [comment]
This particular issue is fixed by pull request #614.

But speaking of projection handling, does anyone have a sample Polyconic gridded file? The `PolyconicProejction` code could use some cleaning up, but it would be good to have a test file to work with when doing so.

**Comment by lesserwhirls** [comment]
Thank you so much @msdsoftware for the report and PR.

It is possible we have a Polyconic gridded file in our extended test datasets. I'll dig around and see - if not, it may be useful to post a request to the netCDF-Java and THREDDS users list.
