### ISSUE TITLE
Debug output of H5header is always printed to console

### ISSUE THREAD

**Issue by marpet** [Unidata/thredds#612]
In the H5header class the field debugOut is used to print debug information.
At some locations the messages are printed even if debug information is not wanted.
For example:
[H5header.java#L1325](https://github.com/Unidata/thredds/blob/4c3d30702108253c7f8e4480970a7608f611d6ed/cdm/src/main/java/ucar/nc2/iosp/hdf5/H5header.java#L1325)
[H5header.java#L1333](https://github.com/Unidata/thredds/blob/4c3d30702108253c7f8e4480970a7608f611d6ed/cdm/src/main/java/ucar/nc2/iosp/hdf5/H5header.java#L1333)

This leads to unwanted output on the console and can make our users feel insecure about the correctness of the software.

**Comment by msdsoftware** [comment]
Last year when I made a bug fix in `H5header`, there was some discussion of cleaning up the logging there and elsewhere. Looks like no one actually got on it.

**Comment by lesserwhirls** [comment]
There are quiet a bit of places in the codebase that print out debug messages, and we've been trying to move those over to using a logger when we come across them, but most of those are likely on the master branch. We'll take a look at the H5Header class specifically to make this happen.

If you run across any particularly verbose debugging statements like this, let us know here and we'll prioritize those to knock them out as quickly as we can. If you could label any of those issues with Area: Logging to make them easier for us to to find.

**Comment by msdsoftware** [comment]
Turns out the prior discussion was not when I posted an H5header bug fix but when I posted #pull request #426 last winter.

**Comment by cwardgar** [comment]
Fixed in #617.

**Comment by marpet** [comment]
Thanks for the quick reaction
