### ISSUE TITLE
netcdf-Java and ToolsUI Do Not Like the CF "Conventions" Global Attribute

### ISSUE THREAD

**Issue by julienchastang** [Unidata/thredds#620]
[According to CF 1.6, identification of the convention is recommended.](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#identification-of-conventions) 

Recently, there was a [discussion](http://mailman.unidata.ucar.edu/mailing_lists/archives/idvusers/2016/msg00027.html) on the `idvusers` mailing list where I was recommending a user supply `Conventions` global attribute metadata pertaining to CF.

`ncfile.Conventions = "CF-1.6"`

However, I have noticed when I add the `Conventions` global attribute to my netCDF data, ToolsUI will no longer recognize the coordinate axes and will not recognize any gridded data. This [folder on RAMADDA](https://motherlode.ucar.edu/repository/entry/show/RAMADDA/Unidata/Staff/Julien+Chastang/CF+Conventions+Global+Attribute?entryid=4d4d0fdb-52b9-42bf-b8f3-4fb01bbce9fe) contains a Jupyter Notebook along with a `grid.nc` file that does not specify a global `Conventions` attribute and a `grid2.nc` that has the `Conventions` global attribute, but is no longer recognized by ToolsUI as containing gridded data. The Jupyter notebook will create the netCDF files in question.

What's going on here? Is this a bug in netCDF-Java or am I not understanding something.

**Comment by lesserwhirls** [comment]
The `coordinates` attribute on the variable `temperature` is wrong. It should be:

```
coordinates = "time z latitude longitude"
```
not

```
coordinates = "time z lat lon"
```

Once you fix that, netCDF-Java will recognize the coordinates.

**Comment by julienchastang** [comment]
Ugh! Mea Culpa. Thanks @lesserwhirls for figuring that out. Indeed, I can confirm with the correct `coordinates` attribute on the `temperature` variable I can now read the data in question with the coordinate axes and the gridded data is recognized by ToolsUI. Thanks again.

**Comment by lesserwhirls** [comment]
No worries, I mess up the coordinates attribute quite often.
