### ISSUE TITLE
Transparency not working NCDF

### ISSUE THREAD

**Issue by codemonkeyneo** [Unidata/thredds#631]
Hi All,

I'm currently serving up NCDF via THREDDS 4.6.2 and would like the returned raster to have transparent pixels for values outside of the range. I did some reading and even tried altering the code on the ncWMS project https://sourceforge.net/p/ncwms/mailman/ncwms-users/thread/4DBAB7F5.1080603@tu-dresden.de/

to see if this was possible ( didnt work for me ), but it seems like it could be something that is posiible knowing the correct things to change.

I have tried updating a pallete to include an ALPHA for the low values hoping to achieve transparency. 

from reading the latest version of THREDDS now includes the ncWMS lib for the WMS service so is a code change required or should palletes alpha work ?

Cheers , any advice would be great.

**Comment by lesserwhirls** [comment]
Have you tried using the keywords ABOVEMAXCOLOR and BELOWMINCOLOR? Those are not part of the WMS standard, but are extensions to WMS that are enabled by ncWMS: http://www.resc.rdg.ac.uk/trac/ncWMS/wiki/WmsExtensions

**Comment by codemonkeyneo** [comment]
Thanks @lesserwhirls Boom! thanks for pointing me in that direction those parameters worked... simple after you said ... I think after hours of reading and then going down the Java path I gave up hope.

**Comment by lesserwhirls** [comment]
Glad we could help!
