### ISSUE TITLE
Single Character Directory Names Cause Issues with Catalog Scan

### ISSUE THREAD

**Issue by nathan-hook** [Unidata/thredds#632]
When using the <catalogScan> directive on a directory structure that has single character directory names there is unexpected behavior when browsing the tds.

To Replicate:

Update the catalog.xml file with the following directive:

&#60;catalogScan name="Catalog Scan Example" path="testDirectory" location="testDirectory" watch="true" /&#62;

Then there needs to be a directory structure like the following:

content home root directory/
|-- testDirectory/
|   |-- 1/
|   |   |-- test-thredds-file-1.xml
|   |-- 10/
|   |   |-- test-thredds-file-10.xml

When browsing the tds from the root catalog directory:
http://&#60;server_name&#62;/thredds/catalog/catalog.html

Click on the "Catalog Scan Example" link.

There should then be a listing of two directories:
1
10

If you click on the "1" directory you will be directed to the following url:
http://&#60;server_name&#62;/thredds/catalog/testDirectory/1/catalogScan.html

And it will show the same two directories again:
1
10

I was expecting to see the file listing for test-thredds-file-1.xml

Which if you then click on the 10 link under the http://&#60;server_name&#62;/thredds/catalog/catalog.html url then things work as expected.

I have tried this issue with the following named single character directories:  1, 2, 3, 4, etc...  a, b, etc...

**Comment by DennisHeimbigner** [comment]
I am unable to duplicate. Here is what I did.
1. created .../thredds/public/testdata/1  and .../thredds/public/testdata/10
2. placed a .nc file in each of those two directories.
3. started the server with -Dtds.content.path=D:/git/thredds/tds/src/test/content
   (obviously specific to my machine).
4. Looked in http://localhost:8081/thredds/catalog/scanLocal/catalog.html,
   saw the 1/ and 10/ directories
5. when into the 1/ directory (http://localhost:8081/thredds/catalog/scanLocal/1/catalog.html)
    saw the file I inserted, and was able to successfully access it.
So, the question is: what did I do different and that is important to the outcome?

**Comment by dopplershift** [comment]
Which version of TDS are we talking about?

**Comment by lesserwhirls** [comment]
Version 5

**Comment by nathan-hook** [comment]
Hi Dennis,

We had a thredds xml file instead of an .nc file.  Not sure if that will
make a difference or not.

I have attached the thredds xml file we used in the 1/ directory.

Regards,

Nathan

**Comment by DennisHeimbigner** [comment]
Cannot see the thredds.xml attachment; can you send again?

**Comment by lesserwhirls** [comment]
Actually, @nathan-hook - can you attach the file to this github issue? if you reply directly to the github email, I don't think it will automatically attach the file to the github issue.

**Comment by nathan-hook** [comment]
Hi Sean,

No problem.

The file should be attached here.

Please let me know if you need any more information from me.

Regards,

Nathan

**Comment by dopplershift** [comment]
@nathan-hook You'll have to come to the GitHub site and drag and drop the file (or select and upload) to a new comment.

**Comment by nathan-hook** [comment]
Come to find out Github doesn't allow .xml files to be attached to tickets.  The file has been renamed to a .txt file.

After you download the file, please rename it to a .xml extension.

Thank you for your time.

[cmip5.output1.NCAR.CCSM4.rcp26.mon.ocean.Omon.r5i1p1.v20121128.txt](https://github.com/Unidata/thredds/files/472370/cmip5.output1.NCAR.CCSM4.rcp26.mon.ocean.Omon.r5i1p1.v20121128.txt)

**Comment by DennisHeimbigner** [comment]
ok, I used that xml and it works ok for me. Attached is the html of the
page I saw from the catalog (in a zip file).
[1.zip](https://github.com/Unidata/thredds/files/473552/1.zip)

**Comment by nathan-hook** [comment]
Hi Dennis,

Thank you for the reply.

One small difference in the file you sent and what we're seeing...

The ending of the url for your example is

catalog.html


The ending of the url for our example is catalogScan.html

Does that help?

Thank you for your time,

Nathan

**Comment by cofinoa** [comment]
Dear @DennisHeimbigner, 

@nathan-hook it is using the new catalogScan element introduced in TDS 5.0.0 (an ESGF requirement). 

My guess is that the implementation 
https://github.com/Unidata/thredds/blob/5.0.0/tdcommon/src/main/java/thredds/server/catalog/CatalogScan.java

has an error on getting the remaining logical path  for mapping to the file system location
```
matchRemaining.length() > 1
```
and it should be used 
```
matchRemaining.length() > 0
```
but I'm not full confident that all references to that statement should be replaced. 

Regards

Antonio

**Comment by DennisHeimbigner** [comment]
I was using 5.0; is the catalogScan you mention
not yet integrated with our 5.0.0?

**Comment by dopplershift** [comment]
@DennisHeimbigner Are you sure you tested a url ending in `catalogScan.html`? The zip you posted seems to indicate it ended in `catalog.html`.

**Comment by cwardgar** [comment]
@DennisHeimbigner Does #662 fix this?

**Comment by DennisHeimbigner** [comment]
I do not know. I was never able to duplicate the problem.
Since the suggested solution seemed reasonable, I implemented
it and declared victory.

**Comment by DennisHeimbigner** [comment]
I do not know. I was never able to duplicate the problem.
Since the suggested solution seemed reasonable, I implemented
it and declared victory.

**Comment by cwardgar** [comment]
[Here](http://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/edu/ucar/tds/5.0.0-SNAPSHOT/tds-5.0.0-20161021.204352-28.war) is a new 5.0.0 build that includes the changes in #662. @nathan-hook, perhaps you can test whether it fixes your problem. Be sure to rename the file to "thredds.war" before deploying.

**Comment by nathan-hook** [comment]
Hi Christian,

Thank you for the reply.

I tried to deploy the listed war file and I got the following error at
startup.

I'm not positive if the problem is on my end or not.

Regards,

Nathan


2016-10-26T16:46:45.808-0600 [      7936][        ] WARN
 org.springframework.web.context.support.XmlWebApplicationContext:
Exception encountered during context initialization - cancelling refresh
attempt: org.springframework.beans.factory.BeanCreationException: Error
creating bean with name
'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping':
Invocation of init method failed; nested exception is
java.lang.NoSuchMethodError:
org.springframework.aop.support.AopUtils.selectInvocableMethod(Ljava/lang/reflect/Method;Ljava/lang/Class;)Ljava/lang/reflect/Method;
2016-10-26T16:46:45.809-0600 [      7937][        ] ERROR
org.springframework.web.context.ContextLoader: Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name
'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping':
Invocation of init method failed; nested exception is
java.lang.NoSuchMethodError:
org.springframework.aop.support.AopUtils.selectInvocableMethod(Ljava/lang/reflect/Method;Ljava/lang/Class;)Ljava/lang/reflect/Method;
at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
at
org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
at
org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
at
org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
at
org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
at
org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776)
~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
at
org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
~[spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
at
org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
~[spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
at
org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
at
org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
at
org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
at
org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
~[catalina.jar:8.0.32]
at
org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
~[catalina.jar:8.0.32]
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
~[catalina.jar:8.0.32]
at
org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
~[catalina.jar:8.0.32]
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
~[catalina.jar:8.0.32]
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
~[catalina.jar:8.0.32]
at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1692)
~[catalina.jar:8.0.32]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_102]
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
~[?:1.8.0_102]
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
~[?:1.8.0_102]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
at
org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
~[tomcat-coyote.jar:8.0.32]
at
com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
~[?:1.8.0_102]
at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
~[?:1.8.0_102]
at
org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:465)
~[catalina.jar:8.0.32]
at
org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:415)
~[catalina.jar:8.0.32]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_102]
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
~[?:1.8.0_102]
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
~[?:1.8.0_102]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
at
org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
~[tomcat-coyote.jar:8.0.32]
at
com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
~[?:1.8.0_102]
at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
~[?:1.8.0_102]
at
javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
~[?:1.8.0_102]
at
javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
~[?:1.8.0_102]
at
javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
~[?:1.8.0_102]
at
javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
~[?:1.8.0_102]
at
javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
~[?:1.8.0_102]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_102]
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
~[?:1.8.0_102]
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
~[?:1.8.0_102]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324)
~[?:1.8.0_102]
at sun.rmi.transport.Transport$1.run(Transport.java:200) ~[?:1.8.0_102]
at sun.rmi.transport.Transport$1.run(Transport.java:197) ~[?:1.8.0_102]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_102]
at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
~[?:1.8.0_102]
at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
~[?:1.8.0_102]
at
sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
~[?:1.8.0_102]
at
sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
~[?:1.8.0_102]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_102]
at
sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
[?:1.8.0_102]
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[?:1.8.0_102]
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[?:1.8.0_102]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.NoSuchMethodError:
org.springframework.aop.support.AopUtils.selectInvocableMethod(Ljava/lang/reflect/Method;Ljava/lang/Class;)Ljava/lang/reflect/Method;
at
org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.detectHandlerMethods(AbstractHandlerMethodMapping.java:248)
~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
at
org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:214)
~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
at
org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:184)
~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
at
org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:128)
~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
... 57 more

**Comment by cwardgar** [comment]
Hi Nathan,

When you deployed the new TDS 5.0.0 snapshot, did you make sure to delete ALL traces of the old one? This includes the `thredds/` directory that Tomcat creates when it first deploys TDS. For example, I did:
```bash
[cwardgar@lenny ~/dev/tools/apache-tomcat-8.0.29/webapps]
$ ls
total 292384
drwxr-xr-x  12 cwardgar  ustaff   408B Oct 19 12:04 .
drwxr-xr-x  14 cwardgar  ustaff   476B May 19 13:21 ..
drwxr-xr-x  19 cwardgar  ustaff   646B Nov 20  2015 ROOT
drwxr-xr-x  55 cwardgar  ustaff   1.8K Nov 20  2015 docs
drwxr-xr-x   7 cwardgar  ustaff   238B Nov 20  2015 examples
drwxr-xr-x   7 cwardgar  ustaff   238B Nov 20  2015 host-manager
drwxr-xr-x   8 cwardgar  ustaff   272B Nov 20  2015 manager
drwxr-xr-x  23 cwardgar  ustaff   782B Oct 19 12:04 thredds
-rw-r--r--@  1 cwardgar  ustaff    37M Oct 17 19:16 thredds.war
[cwardgar@lenny ~/dev/tools/apache-tomcat-8.0.29/webapps]
$ rm -r thredds*
[cwardgar@lenny ~/dev/tools/apache-tomcat-8.0.29/webapps]
$ mv ~/Downloads/tds-5.0.0-20161102.131506-36.war thredds.war
```

**Comment by nathan-hook** [comment]
Hi Christian,

We were able to successfully deploy the latest version of the tds 5 (the
build from last week I believe).

I'm not sure what we did differently this time, but it is up and running at
this time.

We will work on testing adding and removing single character directories
and let you know how all our tests work out.

Thank you for your time,

Nathan

**Comment by cwardgar** [comment]
@nathan-hook Okay, I'm going to close this issue for now because it looks like we may have solved it. Feel free to reopen if you see it again.
