### ISSUE TITLE
Update FNMOC grib tables

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#644]
[FNMOC_GRIB_TABLES.zip](https://github.com/Unidata/thredds/files/488454/FNMOC_GRIB_TABLES.zip)

**Comment by lesserwhirls** [comment]
So, having dug into this, it looks as though the new html files from FNMOC do not contain any updates for GRIB1 tables. They include info for GRIB2 tables, but as far as I can tell, we do not read GRIB2 files from FNMOC. Closing this issue.

**Comment by ethanrd** [comment]
@lesserwhirls What do you mean we do not read GRIB2 files from FNMOC? Does FNMOC produce GRIB2 files? If so, we want netCDF-Java/TDS to be able to read them. Yes?

**Comment by lesserwhirls** [comment]
@ethanrd - what I meant was that netcdf-java currently does not use any specific GRIB2 tables for FNMOC, only GRIB1. It's also the case that all of the data we at Unidata get from FNMOC is in GRIB1, but as far as I know, we haven't had any issues reported about FNMOC GRIB2 files. It could be that FNMOC is using NCEP tables for GRIB2, and that's why we haven't heard anything.
