### ISSUE TITLE
ToolsUI and Unsigned variables

### ISSUE THREAD

**Issue by LupusUmbrae** [Unidata/thredds#651]
It would be really appreciated if the ToolsUI could handle unsigned values as at the moment the results end up looking odd as it's just printing the signed version.

I know that Java 8 has the "toUnsignedString" which would work well for displaying the values, but also understand if the source is targeted to old java version.

An alternative may be to use [Gauva's unsigned int/long's](https://github.com/google/guava/wiki/PrimitivesExplained#unsigned-support) to handle it as it doesn't require java 8

**Comment by cwardgar** [comment]
Yep, I don't think we've tested this use case at all. Do you happen to have a small dataset with unsigned values that we can use for testing? If not, I'll just `ncgen` one.

**Comment by LupusUmbrae** [comment]
I have datasets, just not sure i have any small ones. However i could probably produce one as well if it would help
