### ISSUE TITLE
thredds.ucar.edu down

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/thredds#653]
production Unidata server seems down at 9:19am ET
http://thredds.ucar.edu/thredds/catalog.html

where is the best place to report?  
(not here, right?) :confused:

**Comment by rsignell-usgs** [comment]
okay, it's back up now, so closing, but just curious:  
* why did it crash?
* did it require someone to come in, find it crashed, and trigger the restart, or did it restart automagically?
* is there a service monitor running on this endpoint?

**Comment by lesserwhirls** [comment]
Hi @rsignell-usgs - the best place would be support-thredds@ucar.edu, but this works, too.

In terms of your specific questions, we do not know why it crashed. thredds.ucar.edu was moved to another server while the NCAR Mesa lab had its power down last weekend. There are some signs that the memory on the machine is starting to go (for example, a restart "fixed" tcsh from core-dumping upon invocation). We do have a monitor running on it, and our sys admin gets messages when it goes down.
