### ISSUE TITLE
how to change netcdf to grib

### ISSUE THREAD

**Issue by ElaineTaylor1213** [Unidata/thredds#656]
I'm learning the earth project which builds by cambee.Then I need the data in grib.I download the data from OSCAR.Its data is netcdf,and I need change it to grib.How I can use the toolUI.jar to change it...please  help me,thanks.

**Comment by cwardgar** [comment]
We cannot write GRIB data with our library; we can only read it.

However, [this post](http://stackoverflow.com/questions/15432587/converting-netcdf-to-grib2) discusses some possibilities.
