### ISSUE TITLE
Javascript in the TDS (re: Google Analytics)

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#661]
Rather than hardcoding the Google Analytics javascript into the TDS code, maybe we should allow users of the TDS to include custom javascript files in general. For example, perhaps the TDS could look in `<$CONTENT_ROOT>/thredds/public/js` and include any javascript files found in that directory in the `<HEAD>` element of the html files generated by the TDS...maybe with an appropriate `async` or `defer` tag (based on path, such as  `<$CONTENT_ROOT>/thredds/public/js/async` or `<$CONTENT_ROOT>/thredds/public/js/defer`). Thoughts?

**Comment by cwardgar** [comment]
If we move to HTML templates as described in #444, users will be able to add any content they wish to them, which will then be included in the generated HTML. A potential problem there if the user is modifying the base templates is that their changes will be lost when they upgrade to a new TDS.

Thymeleaf supports fragments: http://www.thymeleaf.org/doc/articles/layouts.html
We could define several such as `custom-body.html`, `custom-footer.html`, `custom-head.html`. Those fragments, if present, would then be included in the base template.

**Comment by lesserwhirls** [comment]
Added in Unidata/thredds#1109 and Unidata/thredds#1110
