### ISSUE TITLE
TDS Beautification

### ISSUE THREAD

**Issue by cwardgar** [Unidata/thredds#669]
Let's admit: the pages that TDS generates look like ass. None of us on staff have great front-end design skills, but that doesn't mean that we can't do any better. There's a billion CSS frameworks out there that do most of the work for you; [Bootstrap](http://getbootstrap.com/) is the most popular one right now. It doesn't look too tough to learn. Furthermore, we can get a good head start–as well as plenty of design ideas–from the many [freely available themes](https://startbootstrap.com/).

To me, this issue depends on #444. Trying to apply Bootstrap to our current within-Java HTML generation is a non-starter.

**Comment by adamsteer** [comment]
+1000 - my reason for #444  was that would rather see development focussed on a templating engine  - for example, someplace in the TDS framework sits a (set of) template files which, by default, render TDS pages in plain HTML.

UX/UI folks can go to town on these - add hooks for bootstrap or whatever styling system they like, but all the developers need to do is make sure that the required page elements are all there. Like Jinja2 templating for Flask apps.

That way Java developers don't need to care about styles, or choosing a styling framework, and the UI/UX folks don't need to care about Java. (although maybe bootstrap styles by default would be nice.. and easy). Also get in touch if you need a hand to build templates once an engine is decided upon - HTML used to be my second language.

**Comment by ccarleton-noaa** [comment]
Whatever you do make sure that it doesn't break in an HTTPS-only
environment with HSTS.

**Comment by kwilcox** [comment]
FWIW: it is possible to make TDS look a __bit__ better using the CSS that the existing HTML pages already reference:

* http://thredds.cencoos.org
* http://thredds.axiomdatascience.com/

**Comment by julienchastang** [comment]
I took the liberty of reusing the styling work of Axiom here: http://jetstream.unidata.ucar.edu/thredds/catalog.html

BTW, this is our TDS on the XSEDE Jetstream Cloud. It makes use of the docker work we did recently. IMO the Axiom CSS could be the default CSS of the TDS, minus the logo. That would at least be a step up over what we have now.

**Comment by dopplershift** [comment]
Why for the love of all that is holy is TDS by default using a monospace font for 90% of the content on the page?

<snark>All that's missing is an image of some orange cones, an "under construction banner", and some links to a geocities web ring</snark>

😈 

(Sorry, I couldn't help myself.)

**Comment by lesserwhirls** [comment]
Added in Unidata/thredds#1109 and Unidata/thredds#1110 - yay @haileyajohnson !
