### ISSUE TITLE
Access to AWS through McIDAS-V Catalogs

### ISSUE THREAD

**Issue by joleenf** [Unidata/thredds#677]
I was trying to access the following thredds catalog, but get an error
(Error: Could not load url: http://thredds-aws.unidata.ucar.edu/thredds/catalog.xml)

http://thredds-aws.unidata.ucar.edu/thredds/catalog.xml <http://thredds-aws.unidata.ucar.edu/thredds/catalog.xml>

Has the url changed for radar data from amazon web services?

Thanks,
Joleen

**Comment by dopplershift** [comment]
It hasn't moved--the machine just got stuck somehow. I restarted TDS and everything seems to be working. Feel free to reach out again if you run into more problems.
