### ISSUE TITLE
Output from NCSS webform in CDM

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#686]
Why is the code that controls what appears in the the output selection list of the NCSS Station/Point forms live in the CDM module?

[cdm/src/main/java/ucar/nc2/ft/point/writer/FeatureDatasetPointXML.java](https://github.com/Unidata/thredds/blob/master/cdm/src/main/java/ucar/nc2/ft/point/writer/FeatureDatasetPointXML.java#L206)

This appears to have been addressed in 5.0 (at least this file is gone), but we should make sure.

**Comment by cwardgar** [comment]
Looks like all of that stuff is done in [tds/src/main/java/thredds/server/ncss/format/](https://github.com/Unidata/thredds/tree/5.0.0/tds/src/main/java/thredds/server/ncss/format) now.
