### ISSUE TITLE
readDataSlice(int rt, int e, int t, int z, int y, int x) in the geogrid.java doesnot check the unsigned attribute

### ISSUE THREAD

**Issue by yuanho** [Unidata/thredds#695]
you can find the dataset here:

The data is at ftp ftp.ssec.wisc.edu in
pub/incoming/A2015145.210[0-3].nc.

**Comment by lesserwhirls** [comment]
Hi @yuanho - it looks like this didn't make it in 4.6.7. However, I'll get a fix in today, but I'll need an example file. The data file is no longer available on the ssec ftp server - do you have a copy?

**Comment by dopplershift** [comment]
FYI, you can zip/gzip netcdf files and attach them to issues--that way they're always available in the matching issue.

**Comment by lesserwhirls** [comment]
test data and ncml agg can be found in [data.zip](https://github.com/Unidata/thredds/files/686292/data.zip)
