### ISSUE TITLE
simple time aggregation for dataset with unsigned byte variable not working in 5.0

### ISSUE THREAD

**Issue by yuanho** [Unidata/thredds#696]
it is working in the 4.6, I am guessing the unsinged byte causes the problem.

same dataset as previous ticket.

**Comment by cwardgar** [comment]
This appears to work in 5.0.0 now, possibly because of #934. Give it a shot in the new build, if you want:
https://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/edu/ucar/toolsUI/5.0.0-SNAPSHOT/

Closing for now. Reopen if you find something.
