### ISSUE TITLE
NCSS GridAsPoint form not working in 5.0

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#702]
...because it's not there.

The grid form has been migrated to use a thymeleaf template:

https://github.com/Unidata/thredds/blob/5.0.0/tds/src/main/webapp/WEB-INF/templates/ncssGridth.html

Something similar needs to be created for the grid-as-point form, which can then be hooked up in the `getDatasetDescription` method of `NcssGridController`. Also, will need to create an analogous method to `showGridFormTh` in `NcssShowFeatureDatasetInfo`.

**Comment by cwardgar** [comment]
Fixed in #1026.
