### ISSUE TITLE
Empty FMRC produces odd error message

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#705]
When the FMRC does not find any files, the behavior is odd. First, a general skeleton catalog is produces (links to best, 2D time, files, forecast model run), but when you try to access catalogs/files under those, TDS produces the error message:

FileNotFound: /Users/sarms/dev/unidata/content/5.0/thredds/GFS/0p25/runs/catalog.xml

when really the issue is that the collection is empty.

**Comment by cwardgar** [comment]
I believe this is what we were seeing in #664.
