### ISSUE TITLE
DAP4 NPE

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#708]
DAP4 Requests throwing a 500 due to NPE on some datasets on thredds-test/thredds-dev:

http://thredds-dev.unidata.ucar.edu/thredds/dap4/grib/NCEP/RAP/CONUS_13km/RR_CONUS_13km_20161208_0000.grib2.dmr.xml

```
HTTP Status 500 - <Error httpcode="500"> <Message>java.lang.NullPointerException at
dap4.cdm.dsp.CDMDSP.isdeclfor(CDMDSP.java:912) at
dap4.cdm.dsp.CDMDSP.finddimdecl(CDMDSP.java:903) at
dap4.cdm.dsp.CDMDSP.builddimrefs(CDMDSP.java:747) at
dap4.cdm.dsp.CDMDSP.buildvariable(CDMDSP.java:502) at
dap4.cdm.dsp.CDMDSP.buildvariable(CDMDSP.java:441) at
dap4.cdm.dsp.CDMDSP.fillgroup(CDMDSP.java:356) at
dap4.cdm.dsp.CDMDSP.buildDMR(CDMDSP.java:317) at
dap4.cdm.dsp.CDMDSP.open(CDMDSP.java:155) at dap4.cdm.dsp.CDMDSP.open(CDMDSP.java:135)
at dap4.servlet.DapCache.open(DapCache.java:93) at
dap4.servlet.DapController.doDMR(DapController.java:311) at
dap4.servlet.DapController.handleRequest(DapController.java:237) at
thredds.server.dap4.Dap4Controller.handleRequest(Dap4Controller.java:95)
...
```

Appears to work in other situation:

http://thredds-dev.unidata.ucar.edu/thredds/dap4/satellite/3.9/WEST-CONUS_4km/current/WEST-CONUS_4km_3.9_20161207_2315.gini.dmr.xml

Maybe this is something specific to `Grib` `FeatureCollections`?

This is with the latest artifacts from Unidata/thredds branch 5.0.0:

http://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/edu/ucar/tds/5.0.0-SNAPSHOT/tds-5.0.0-20161208.015202-56.war

**Comment by DennisHeimbigner** [comment]
Dataset no longer exists
