### ISSUE TITLE
Attribute values of type long are treated incorrectly

### ISSUE THREAD

**Issue by TomBlock** [Unidata/thredds#715]
When creating an Attribute class of type long using the CF Conventions default _FillValue (N3iosp.NC_FILL_LONG), the Attribute class returns a wrong value when asked to return the numeric value. This is caused by internally mapping the Number value to a Double.

Line 356 in Attribute.java (1264353 of 5 Dec 2015):
vala.setDouble(ima.set0(0), val.doubleValue());

example:

Attribute att = new Attribute("name", N3iosp.NC_FILL_LONG) // which is -9223372036854775806L
long result = att.getNumericValue().longValue(); // returns -9223372036854775808L

We are using version 4.6.6:
<dependency>
    <groupId>edu.ucar</groupId>
    <artifactId>netcdf4</artifactId>
    <version>4.6.6</version>
</dependency>

**Comment by cwardgar** [comment]
@TomBlock Thank you for the excellent bug report! It's not often that we get one that identifies the issue precisely and tells us exactly how to fix it. I've made the change in #717. It'll appear in v4.6.6 (as well as v5.0.0).
