### ISSUE TITLE
How to download data subset via CdmRemote 

### ISSUE THREAD

**Issue by Sammers21** [Unidata/thredds#738]
Hello.
I know, that i can get whole file via CdmRemote and save it in my computer's file system.
Java:
`import ucar.nc2.stream.CdmRemote;`
`CdmRemote cdmRemote = new CdmRemote(url);`
`cdmRemote.writeToFile(path);`

 But i have no idea how to access to subset of data file. For example instead of getting data for  entire year, i want to get data for first 6 hours of year.

**Comment by cwardgar** [comment]
I suspect that you want to use the [NetCDF Subset Service](http://www.unidata.ucar.edu/software/thredds/current/tds/reference/NetcdfSubsetServiceReference.html) instead. [Here](http://thredds.ucar.edu/thredds/ncss/grib/NCEP/GFS/Global_0p25deg/Best/dataset.html) is an example from our production server. Does that seem useful to you?
