### ISSUE TITLE
TDS does not import "incomplete" CF DSG TimeSeries

### ISSUE THREAD

**Issue by pacioos** [Unidata/thredds#747]
Hi TDS folks,
One of the recommended formats for a CF DSG TimeSeries is to have two dimensions: one for the various stations in the file (e.g., "timeseries" or "station") and another dimension to hold the data for each station (e.g., "obs"). The variable "time" then has both dimensions, timeseries and obs. When attempting to import such a file in TDS, however, it fails with this error:

    "Dimension not found= time"

If I rename the "obs" dimension to "time" so that the "time" variable becomes a coordinate variable, the error goes away in TDS and the data import successfully. However, this is not the only recommended CF DSG TimeSeries format; having time as a coordinate variable matches the "[orthogonal](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#_orthogonal_multidimensional_array_representation_of_time_series)" TimeSeries format, but TDS also needs to support the "incomplete" (non-orthogonal multidimensional array) format (timeseries, obs) outlined in the [CF spec](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#_incomplete_multidimensional_array_representation_of_time_series) and [NODC/NCEI "gold standard"](https://www.nodc.noaa.gov/data/formats/netcdf/v2.0/timeSeriesIncomplete.cdl) (@mbiddle-nodc) templates and the ncCFMA output from ERDDAP (@BobSimons). As an aside, the [IOOS CF compliance checker](https://github.com/ioos/compliance-checker) (@lukecampbell) also throws an error when time is a coordinate variable in our DSG TimeSeries files:

    time shares the same name as one of its dimensions

Why is it that TDS cannot import the "incomplete" CF DSG TimeSeries format (timeseries, obs)?
Thanks!,
John Maurer
Data System Engineer
Pacific Islands Ocean Observing System (PacIOOS)
University of Hawaii at Manoa

**Comment by lukecampbell** [comment]
Under [CF 1.6 Chapter 5](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#coordinate-system)

> We recommend that the name of a multidimensional coordinate variable should not match the name of any of its dimensions because that precludes supplying a coordinate variable for the dimension. This practice also avoids potential bugs in applications that determine coordinate variables by only checking for a name match between a dimension and a variable and not checking that the variable is one dimensional.

This is why the CF checker will flag a variable for having a dimension that shares the same name as the variable. Under CF, dimensions _should only_ have the same name as a variable if they are coordinate variables.

**Comment by cwardgar** [comment]
Hi John,

Here is an NcML version of the CF example you linked to that we have in our test suite:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- See http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#Example%20H.2.2.1 -->
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
    <dimension name="station" length="10" isUnlimited="true"/>
    <dimension name="obs" length="13"/>
    <dimension name="name_strlen" length="3"/>

    <variable name="lon" shape="station" type="float">
        <attribute name="standard_name" value="longitude"/>
        <attribute name="long_name" value="station longitude"/>
        <attribute name="units" value="degrees_east"/>
        <values start="1" increment="1"/>
    </variable>

    <variable name="lat" shape="station" type="float">
        <attribute name="standard_name" value="latitude"/>
        <attribute name="long_name" value="station latitude"/>
        <attribute name="units" value="degrees_north"/>
        <values start="2" increment="2"/>
    </variable>

    <variable name="alt" shape="station" type="float">
        <attribute name="long_name" value="vertical distance above the surface"/>
        <attribute name="standard_name" value="height"/>
        <attribute name="units" value="m"/>
        <attribute name="positive" value="up"/>
        <attribute name="axis" value="Z"/>
        <values start="3" increment="3"/>
    </variable>
    
    <variable name="station_name" shape="station name_strlen" type="char">
        <attribute name="long_name" value="station name"/>
        <attribute name="cf_role" value="timeseries_id"/>
        <values>AAABBBCCCDDDEEEFFFGGGHHHIIIJJJ</values>
    </variable>
    
    <variable name="station_info" shape="station" type="int">
        <attribute name="long_name" value="any kind of station info"/>
        <values start="4" increment="4"/>
    </variable>
    
    <variable name="station_elevation" shape="station" type="float">
        <attribute name="long_name" value="height above the geoid"/>
        <attribute name="standard_name" value="surface_altitude"/>
        <attribute name="units" value="m"/>
        <values start="5" increment="5"/>
    </variable>
    
    <variable name="time" shape="station obs" type="double">
        <attribute name="standard_name" value="time"/>
        <attribute name="long_name" value="time of measurement"/>
        <attribute name="units" value="days since 1970-01-01 00:00:00"/>
        <attribute name="missing_value" value="-999.9"/>
        <values start="6" increment="6"/>
    </variable>
    
    <variable name="humidity" shape="station obs" type="float">
        <attribute name="standard_name" value="specific_humidity"/>
        <attribute name="coordinates" value="time lat lon alt"/>
        <attribute name="_FillValue" value="-999.9"/>
        <values start="7" increment="7"/>
    </variable>
    
    <variable name="temp" shape="station obs" type="float">
        <attribute name="standard_name" value="air_temperature"/>
        <attribute name="units" value="Celsius"/>
        <attribute name="coordinates" value="time lat lon alt"/>
        <attribute name="_FillValue" value="-999.9"/>
        <values start="8" increment="8"/>
    </variable>

    <attribute name="featureType" value="timeSeries"/>
    <attribute name="Conventions" value="CF-1.6"/>
</netcdf>
```
I've verified that NetCDF-Java correctly imports and interprets the file. Do you have a specific example that demonstrates the error?

**Comment by pacioos** [comment]
Thanks, Christian. Hmm, I'm not sure what's wrong with our example, then.
Here is a file to test with:

http://www.pacioos.hawaii.edu/archive/WQB04agg/WQB04agg.2016.nc

I'm trying to serve this example file in this TDS catalog here. Clicking on
the OPeNDAP link gives me the error message that the time dimension is not
found:

http://oos.soest.hawaii.edu/thredds/idd/wqb.html?dataset=WQB04agg

Cheers,
John

**Comment by cofinoa** [comment]
Hi John @pacioos , 

We also need the definition of the WQB04agg aggregation dataset on the `wqb.xml`. 

My guess (at risk been wrong, because I need exactly how you are aggregating) is that you are doing a **JoinExistingAggregation** like this:
`<aggregation dimName="time" type="joinExisting">`

but the join must be done on the **`dimension`** `timeseries` not in the **`variable`** `time`:
`<aggregation dimName="timeseries" type="joinExisting">`

Regards

Antonio

**Comment by pacioos** [comment]
Yes! Thanks for catching my error, Antonio. When we changed our "time"
dimension to be named "obs", I didn't think to update the dimName in our
joinExisting aggregation. It now works.
Many thanks,
John Maurer

On Wed, Feb 1, 2017 at 12:10 AM, Antonio S. Cofiño <notifications@github.com

**Comment by cwardgar** [comment]
So is this issue resolved?

**Comment by pacioos** [comment]
Yes, thank you!
