### ISSUE TITLE
WRF Mercator Projection Not Always correct

### ISSUE THREAD

**Issue by barronh** [Unidata/thredds#752]
WRF Mercator uses the TRUELAT1 property to define the true scale latitude[1], but currently WRFConvention.java uses the MOAD_CEN_LAT via the "standardLat" variable. This is only true when the mother of all domains (MOAD) is centered on the true scale latitude, which while desirable is not required.

Below is a suggested update.

    thredds/cdm/src/main/java/ucar/nc2/dataset/conv/WRFConvention.java:262
    <          proj = new Mercator(standardLon, standardLat); // thanks to Robert Schmunk
    >          proj = new Mercator(standardLon, lat1);

I will open a separate issue for the earth radius updates that are required and are not specific to Mercator.

[1]http://www2.mmm.ucar.edu/wrf/users/docs/user_guide_V3/users_guide_chap3.htm

**Comment by barronh** [comment]
References issue #753

**Comment by lesserwhirls** [comment]
Closed by Unidata/thredds#757 (4.6) and Unidata/thredds#759 (5.0)
