### ISSUE TITLE
WRF Earth Radius

### ISSUE THREAD

**Issue by barronh** [Unidata/thredds#753]
Right now all projections for WRF are initialized without a specified earth radius. WRF uses a spherical earth with a fixed radius of 6370000m.[1] Each of the projections in the WRFConvention can be updated to use that radius.

    cdm/src/main/java/ucar/nc2/dataset/conv/WRFConvention.java:248
    <          proj = new LambertConformal(standardLat, standardLon, lat1, lat2);
    >          proj = new LambertConformal(standardLat, standardLon, lat1, lat2, 0.0, 0.0, 6370);

    cdm/src/main/java/ucar/nc2/dataset/conv/WRFConvention.java:258
    <          proj = new Stereographic(lat0, lon0, scaleFactor);
    >          proj = new Stereographic(lat0, lon0, scaleFactor, 0.0, 0.0, 6370);

    cdm/src/main/java/ucar/nc2/dataset/conv/WRFConvention.java:262
    <          proj = new Mercator(standardLon, standardLat); // thanks to Robert Schmunk
    >          proj = new Mercator(standardLon, lat1, 0.0, 0.0, 6370); // this update also include a fix to the true latitude in issue #752

[1] http://www2.mmm.ucar.edu/wrf/users/docs/user_guide_V3/users_guide_chap5.htm

**Comment by lesserwhirls** [comment]
Closed by Unidata/thredds#757 (4.6) and Unidata/thredds#759 (5.0)
