### ISSUE TITLE
Old ehcache dependency

### ISSUE THREAD

**Issue by jonenst** [Unidata/thredds#755]
Hi,
with ehcache 2.7 in Mar, 2013, the ehcache artifact has moved from "net.sf.ehcache » ehcache-core" to "net.sf.ehcache.internal » ehcache-core"

Would you consider upgrading to the most recent artifactId ?
Also, ehcache-core is now "internal", could you go back to the "net.sf.ehcache » ehcache" artifact ? (it was switched in c26a2332b)

Doing these 2 things would allow automatic transitive dependencies version conflict resolutions for projects using the latest versions, ie avoid duplicate classes in the class path (for exemple using maven).

Or I saw that you might switch to guava caches, do you intend to remove ehcache as a dependency? If so the issue would disappear.

Regards,
Jon

**Comment by cwardgar** [comment]
Hi Jon,

ehcache is commented out [in 5.0.0](https://github.com/Unidata/thredds/blob/5.0.0/gradle/any/dependencies.gradle#L258), and therefore not used. So, there shouldn't be any conflict in that version.

**Comment by jonenst** [comment]
Hi,
thanks great.
I was looking at "edu.ucar » cdm » 4.5.5" from maven central ( https://mvnrepository.com/artifact/edu.ucar/cdm/4.5.5 ) which is a transitive dependency of tika-parsers.

To be honest, I don't know much about your project, except for this transitive dependency. Is there a public roadmap for 5.0.0 and a planned release date so that I can go and ask tika-parsers to update their dependency ?

Also, I noticed that your last stable release is 4.6.8 on your maven repo, but it's not in maven central. Do you plan on continuing to upload your artifacts on maven central ?

If this information is available somewhere, feel free to redirect me to the correct place, I couldn't find it in the mailing lists ( http://www.unidata.ucar.edu/support/help/MailArchives/thredds/threads.html ? ) or website

Also, thanks a lot for the very quick reply!

**Comment by cwardgar** [comment]
> Is there a public roadmap for 5.0.0 and a planned release date so that I can go and ask tika-
> parsers to update their dependency ?

We expect to have a beta for NetCDF-Java available "soon". If I had to guess, some time next month.

> Do you plan on continuing to upload your artifacts on maven central ?

AFAIK, those Maven Central uploads were handled by a contributor, who long ago stopped posting new versions. The process is a big pain, so we never pursued it ourselves. I think we'll probably publish to [JCenter](https://bintray.com/bintray/jcenter) in the future instead.
