### ISSUE TITLE
Grib1Record.readDataRaw() expands Quasi Grid

### ISSUE THREAD

**Issue by gwlucastrig** [Unidata/thredds#758]
I am integrating the thredds GRIB API into a legacy application that used a much older version of the library. One of the things that the application does is to expand a GRIB edition 1 thinned grid into a regular grid.  Unfortunately, this action is in conflict with the thredds Grib1Record.readData() method because the API already this action built in.  Rather than modifying the legacy code,  I thought I'd use the Grib1Record.readDataRaw() method which carries the comment "dont convertQuasiGrid".  However, that method is just a pass-through to the readData method.   It was easy enough to hack the code to make it not convert the quasi GRID, but I was wondering if the existing behavior should be viewed as a bug and if it would be changed in future releases.  

The version 4.8.6 code is shown below.  In my hack, I simply copied up the body of readData and removed the quasi-regular conversion.

~~~~
 // dont convertQuasiGrid
  public float[] readDataRaw(RandomAccessFile raf, GribData.InterpolationMethod method) throws IOException {
    return readData(raf, method);
  }

  // isolate dependencies here - in case we have a minimal I/O mode where not all fields are available
  private float[] readData(RandomAccessFile raf, GribData.InterpolationMethod method) throws IOException {
    Grib1Gds gds = getGDS();
    Grib1DataReader reader = new Grib1DataReader(pdss.getDecimalScale(), gds.getScanMode(), gds.getNxRaw(), gds.getNyRaw(), gds.getNpts(), dataSection.getStartingPosition());
    byte[] bm = (bitmap == null) ? null : bitmap.getBitmap(raf);
    float[] data = reader.getData(raf, bm);

    if (gdss.isThin()) {
      data = QuasiRegular.convertQuasiGrid(data, gds.getNptsInLine(), gds.getNxRaw(), gds.getNyRaw(), method);
    }

    lastRecordRead = this;
    return data;
  }
 
~~~~

**Comment by cwardgar** [comment]
> I was wondering if the existing behavior should be viewed as a bug

Well, `readDataRaw()` doesn't actually do what it claims, so that's definitely a bug! I've submitted a PR (#760) that will be included in v5.0.0 of NetCDF-Java. Until then, you can actually do something like:
```java
gr.readDataRaw(raf, GribData.InterpolationMethod.none);  // Will break when you upgrade to 5.0.
```
OR
```java
GribData.setInterpolationMethod(GribData.InterpolationMethod.none);
// ...
gr.readData(raf);  // Should still work in 5.0.
```
to get the behavior you're looking for. Thanks for the report!
