### ISSUE TITLE
OPeNDAP Dataset Access Form - Indices for variables with more than 1 dimension

### ISSUE THREAD

**Issue by ggalibert** [Unidata/thredds#76]
On the OPeNDAP Dataset Access Form, when I tick a variable, I can see that the indices for its relevant dimension are well set by default to cover the full extent of that dimension, but only when this variable (try with DEPTH) has only one dimension like here : 

http://thredds.aodn.org.au/thredds/dodsC/IMOS/ANFOG/REALTIME/seaglider/GAB20140916/IMOS_ANFOG_BCEOPSTUV_20140924T041707Z_SG516_FV01_timeseries_END-20140924T044331Z.nc.html

When it has more than 1 dimension, it doesn't seem to behave successfully and suggests a default [0:1:0] extent for each of the dimensions :

http://thredds.aodn.org.au/thredds/dodsC/IMOS/ANMN/NSW/PH100/Velocity/IMOS_ANMN-NSW_AETVZ_20130306T011500Z_PH100_FV01_PH100-1303-Workhorse-ADCP-109.5_END-20130430T105500Z_C-20140314T025236Z.nc.html

**Comment by lesserwhirls** [comment]
Greetings @ggalbert,

I just ran across this issue (we are still getting the hang of managing multiple feedback mechanisms). 

I am not 100% certain why this choice was made, but this is the intended behaviour. The issue, I think, is that there is a data size limit on OPeNDAP requests returning ascii (50 MB), and while you are not likely to hit it requesting data from a variable with one dimension, you are much more likely to hit it if you request all of the data for a multidimensional variable.

**Comment by DennisHeimbigner** [comment]
See what the proper dimension values are by looking at the DDS
(i.e. http://thredds.aodn.org.au/thredds/dodsC/IMOS/ANMN/NSW/PH100/Velocity/IMOS_ANMN-NSW_AETVZ_20130306T011500Z_PH100_FV01_PH100-1303-Workhorse-ADCP-109.5_END-20130430T105500Z_C-20140314T025236Z.nc.dds)
