### ISSUE TITLE
Closing NetcdfFileWriter after redefine

### ISSUE THREAD

**Issue by TomBlock** [Unidata/thredds#761]
When closing a NetcdfFileWriter that has been set to redefine mode and back, some internal filestream is kept open. Example:

@Test
public void testCloseFileWriter() throws IOException {
    final File theFile = new File("somewhere.nc");

    final NetcdfFileWriter netcdfFileWriter = NetcdfFileWriter.openExisting(theFile.getAbsolutePath());

    netcdfFileWriter.setRedefineMode(true);
    netcdfFileWriter.setRedefineMode(false);

    netcdfFileWriter.close();

    if (!theFile.delete()) {
        fail();
    }
}

This test fails on Windows OS, on Linux the FS just deletes, no matter if there are streams open.

Has been verified with netcdf4 version 4.6.7 and 4.6.8.

**Comment by cwardgar** [comment]
I've reproduced this issue on Windows 10 with a NetCDF-4 file. It doesn't occur with a NetCDF-3 file. Nor does it occur at all on OSX.

**Comment by cwardgar** [comment]
Fixed in https://github.com/Unidata/thredds/pull/790/commits/f34df70f9e6094612c201a817c4e46cf5e0a7ce5

Thanks for the report, Tom!
