### ISSUE TITLE
GOES-16 issues

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#766]
There are two issues with the new GOES-16 data and netCDF-Java that I have found.

1) the attribute `cdm_data_type` is set to `Image`
2) the data variables have scalar `coordinates` variables listed in the `coordinates` attribute

The first issue is a problem because, well, netCDF-Java does not have `cdm_data_type` of `Image`. That is, there isn't a Scientific Feature Type for Image that's documented, and I'm not sure that was every fully thought out or implemented anywhere (see this [comment](https://github.com/Unidata/thredds/issues/660#issuecomment-255258401) from @ethanrd). When reading the data from disk using `ToolsUI` `FeatureType -> Grids`, everything appears to be ok. So, while I say this is a "problem", it does not appear that netCDF-Java cares all that much and just says "ah, heck, you can be a grid." So forgiving, it is.

The second issue isn't actually a problem wth the data itself, as scalar coordinates in general are ok. The problem is that when reading through `OPeNDAP`, a  `_CoordinateAxis` attribute is added containing the values of the `coordinates` attribute. On its own, this is no big deal I suppose. However, there is a special case in `ucar.nc2.dataset.CoordSysBuilder` that ends up identifying the GOES-16 data variables as coordinate variables because of the scalar coordinates listed in `_CoordinateAxis`...and of course this special case was put in to handle `grib` data. 🤢 Note that this exists in both 4.6.x and 5.0.

Here is the coresponding comment in the code from @JohnLCaron:

~~~java
      /* WTF? JC 7/15/2010
      /* Old GRIB code basically has a bug in it for lat/lon coordinates
         String latLonCoordSys;
            :_CoordinateAxes = "time lat lon";
         this is a Coordinate System Variable getting misidentified as a data variable, because its doesnt qualify as a CoordinateSystem
           see http://www.unidata.ucar.edu/software/netcdf-java/reference/CoordinateAttributes.html
         but it must be a CoordinateSystem because the  _CoordinateAxes dont fit the variable.

         Problem:
         For some data, some axes are being constructed with anon dimensions, so that isCoordinateAxisForVariable is failing and
         so the data value is being tagged as a CoordinateSystem. Could insist that all variable fail ??
         */
~~~

In order to support the GOES-16 datasets, I am in favor of getting rid of the special case, especially since this was put in to support GRIB1 output from the FNMOC NOGAPS model, which isn't in use anymore. The model that replaced it, NAVGEM, does not trigger this special case. However, if we can salvage the special case, then I think we should try.

There is another comment in the code that indicates there is a file in our bag of test data that will trigger this, but I'm not sure it is around anymore. @cwardgar - can you see if we have something along the lines of `/testdata2/grid/grib/grib1/data/NOGAPS-Temp-Regional.grib` in our test data?

**Comment by cwardgar** [comment]
Yep, it's at `cdmUnitTest/formats/grib1/NOGAPS-Temp-Regional.grib`

**Comment by lesserwhirls** [comment]
How big is it? Is there a way you could get me a copy. I don't have any of the test data locally, and I don't think I have access to the VM where the test data live.

**Comment by cwardgar** [comment]
2.7 KB. I've attached it. I can also give you access to Jenkins if you give me your SSH public key.

[NOGAPS-Temp-Regional.zip](https://github.com/Unidata/thredds/files/819009/NOGAPS-Temp-Regional.zip)

**Comment by lesserwhirls** [comment]
Awesome, thanks! I'll send you a key here after bit.

**Comment by lesserwhirls** [comment]
So the file does not even trigger that block of code anymore. I am in favor of nuking it and seeing how the rest of the tests do. Any objections?

**Comment by cwardgar** [comment]
I'm all for nuking special cases, if possible.

**Comment by julienchastang** [comment]
@lesserwhirls Out of curiosity, can the fact the data are not CF compliant (i.e., `cdm_data_type` of `Image`) be communicated back to the data provider? And possibly give them guidance on what it should be? Especially given the fact that GOES-16 is still experimental?

**Comment by lesserwhirls** [comment]
@julienchastang The data are CF compliant. `cdm_data_type` isn't a CF thing, but an Attribute Convention for Data Discovery (ACDD)[ACDD](http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery_1-3#cdm_data_type).

**Comment by lesserwhirls** [comment]
Should be good to go with GOES-16 now.
