### ISSUE TITLE
ncWMS failing with featureCollection on TDS Version 4.5.4-SNAPSHOT - 20141008.1804

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/thredds#78]
ncWMS failing with FMRC featureCollection on TDS Version 4.5.4-SNAPSHOT - 20141008.1804, giving this error:
```
2014-11-13T15:30:15.753 +0100 [    280992][      27] ERROR - thredds.server.wms.ThreddsWmsController - dispatchWmsRequest(): Exception:
java.lang.IllegalArgumentException: The calendar system proleptic_gregorian cannot be handled
        at uk.ac.rdg.resc.edal.cdm.CdmUtils.getTimesteps(CdmUtils.java:409) ~[CdmUtils.class:1.0.tds.4.4.0]
```
is this the same problem described here:
http://sourceforge.net/p/ncwms/mailman/message/32618474/

**Comment by lesserwhirls** [comment]
Hi Rich,

I wanted to let you know that this has been fixed in both the 4.5.4 and 4.6.0 branches.

Cheers!

Sean

**Comment by rsignell-usgs** [comment]
So this release has it?
https://github.com/Unidata/thredds/releases/tag/v4.5.4

**Comment by dopplershift** [comment]
It should.

**Comment by rsignell-usgs** [comment]
I just installed 4.5.4 and restarted, but my FMRC aggregations are not appearing.  This just hangs:

http://geoport-dev.whoi.edu/thredds/catalog/coawst_4/use/fmrc/catalog.html

Do I need to something other other than:
```
cd <tomcat>/webapps
../bin/shutdown.sh
rm -rf thredds
rm -rf ../content/thredds/cache
rm -rf ../content/thredds/logs
mv thredds.war thredds.bak
wget ftp://ftp.unidata.ucar.edu/pub/thredds/4.5/4.5.4/thredds.war
../bin/startup.sh
```

**Comment by dopplershift** [comment]
Unfortunately, FMRC is known to not be completely solid on 4.5.x. @JohnLCaron anything to add?

**Comment by rsignell-usgs** [comment]
Yeah, it's a mystery.   I can't see anything wrong in any of the logs.

**Comment by JohnLCaron** [comment]
They dont appear in the catalogs at all? Error message in catalogInit or
fc.<collection>.log ?? catalina.out?

**Comment by rsignell-usgs** [comment]
When I click on the FMRC, it spins for 5 minutes or so and then says:

```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /thredds/catalog/coawst_4/use/fmrc/catalog.html.

Reason: Error reading from remote server
```
could that perhaps mean that it's just not yet done building the metadata for the FMRC?
I reloaded, and now I'm waiting again...

**Comment by rsignell-usgs** [comment]
Whoa!  That was it!   After refreshing again and waiting another 3 minutes, the FMRC is now working, and ncWMS/Godiva are working with the 4.5.4 version.   Great!

But the most amazing thing is that the performance is *way* better than with 4.3.  

Try selecting "sea_water_potential_temperature" with 4.3, which takes about 20 seconds: 

http://geoport.whoi.edu/thredds/godiva2/godiva2.html?server=http://geoport.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd

And compare that with 4.5.4, which takes about 2 seconds!
http://geoport-dev.whoi.edu/thredds/godiva2/godiva2.html?server=http://geoport-dev.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd

Did you guys fix something or did I just have something misconfigured with 4.3?  This is an amazing performance increase.   ncWMS on THREDDSS was basically unusable for curvilinear grids before, but now it's not!

**Comment by JohnLCaron** [comment]
I talked to Jon Blower about it. We think the speedup is due to some
changes marcos made in caching the interpolations. Glad its working.
