### ISSUE TITLE
The featureCollection are not applying the RestrictAccess attribute

### ISSUE THREAD

**Issue by cofinoa** [Unidata/thredds#79]
The datasets that feature collections are generating are not applying the `restrictAccess` attribute
As example:
```xml
<dataset name="NCEP's CFSv2 Datasets" ID="cfsrrdatasets" restrictAccess="cfsrr">
    <featureCollection name="cfsAgg" featureType="FMRC" path="cfs/agg">
      <collection spec="/hiddendirectory/**/.+\.grb2$"
       dateFormatMark="yyyyMMddHH#.time.grb2#"/>
      <update startup="false" trigger="allow"/>
      <fmrcConfig regularize="true" datasetTypes="TwoD"/>
    </featureCollection>
    <dataset name="CFS File Dataset" ID="cfs/cfs.grib2" urlPath="cfs/tmax/198201/tmax.1982010106.time.grb2"/>
</dataset>
```
the dataset generated for the `featureCollection` has the property `RestrictAccess` but the redirection to restrictedAccess is not been made and therefore not restriction is applied. 
You can see this online:
[http://meteo.unican.es/tds5/catalog/cfs/agg/catalog.html]
But the `dataset` generated ad-hoc is applying the restriction and therfore the autentication challenge is made:
[http://meteo.unican.es/tds5/catalogs/cfs/cfsDatasets.html?dataset=cfs/cfs.grib2]

**Comment by JohnLCaron** [comment]
fixed
