### ISSUE TITLE
Problem accessing GOES-16 full disk on TDS 5

### ISSUE THREAD

**Issue by dopplershift** [Unidata/thredds#799]
So trying to hit some full disk data from NOAAPORT using NCSS:

http://thredds-test.unidata.ucar.edu/thredds/ncss/grid/satellite/goes16/GOES16/20170412/FullDisk/Channel01/GOES16_20170412_000037_0.47_1km_0.0S_89.5W.nc4/dataset.html

I get the following:
```
IllegalArgumentException: Must specify semi_minor_axis
```
Looking at the OPENDAP output, This would seem to be the problem:
```
grid_mapping_name: geostationary
latitude_of_projection_origin: 0.0
longitude_of_projection_origin: -89.5
semi_major: 6378137.0
semi_minor: 6356752.31414
perspective_point_height: 3.5785831E7
sweep_angle_axis: x
```
I have no idea if that's actually CF-compliant.

**Comment by lesserwhirls** [comment]
CF specifies that the attributes should be `semi_major_axis` and `semi_minor_axis`, according to the grid mapping attributes table:

http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#table-grid-mapping-attributes

**Comment by lesserwhirls** [comment]
Do you know who to contact to get that fixed? Same person you passed along the compression / shuffle info?

**Comment by dopplershift** [comment]
Sent it on...

**Comment by lesserwhirls** [comment]
Thanks @dopplershift!

**Comment by dopplershift** [comment]
Now the problem is NCSS complaining:
```
IllegalArgumentException: Must specify perspective_point_height
```
even though it's present. PR incoming....
