### ISSUE TITLE
Enable reading remote NcML files

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#800]
Currently the CDM, specifically NetcdfDataset, does not allow users to read NcML files that are hosted on remote servers and served via HTTP. For example, a user cannot pass in the following URL:

http://weather.rsmas.miami.edu/repository/entry/get/entryid:dab6c075-cf2a-45d5-bfa3-966e8a7ae38f/merra_aimcpasm.ncml

even though it only references other remote datasets (i.e. no local datasets need to be downloaded before the NcML file can be used).

If, in `NetcdfDataset` (specifically the `disambiguateHttp` method), the code is able to identify the file hosted at the URL as an NcML file, then netCDF-Java will read it without any issues. With a little modification of the code to detect that the hosted file is indeed an NcML file, things "just work" (™️)

PR on the way.

**Comment by lesserwhirls** [comment]
@yuanho - I hope to get it in our next 4.6 release (likely next week).

**Comment by cofinoa** [comment]
@lesserwhirls this is related also to issue #797 

Please take a look my last comment https://github.com/Unidata/thredds/issues/797#issuecomment-293881425

**Comment by lesserwhirls** [comment]
Hi @cofinoa, the issues are somewhat related. However, in this case, it's possible that the `NcML` file does not reference any local file at all (i.e. the `location` attribute of the `netcdf` element references an `OPeNDAP` URL). Given that `NcML` files are generally small and have this ability, it makes sense to at least give it a try. With something like a `GRIB` file, you need to index the file first, which requires scanning through the entire file. If you already have to read through the entire file once, you are probably better off downloading it locally one time (assuming you are not accessing the file through a webservice like `OPeNDAP` on the TDS).

**Comment by cofinoa** [comment]
You can enforce to read as ncml by adding the fragment `protocol=ncmdl` to the URL like this:
http://weather.rsmas.miami.edu/repository/entry/get/entryid:dab6c075-cf2a-45d5-bfa3-966e8a7ae38f/merra_aimcpasm.ncml#protocol=ncmdl
