### ISSUE TITLE
godiva2, https, and YUI

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#821]
Non-https resources included in godiva2.html (i.e. YUI js and css files) do not load when accessing godiva2.html over https. It looks like we will need to bundle the YUI resources with thredds.war and use the local copies, as yahoo does not serve these resources over https. Needs to be fixed in the next 4.6 release.

**Comment by tsanah** [comment]
Hi thanks for working on this problem.   Can I have the updated thredds.war to download ?

**Comment by cwardgar** [comment]
[Here](http://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/edu/ucar/tds/5.0.0-SNAPSHOT/tds-5.0.0-20170602.124159-358.war) is the latest build. Rename to `thredds.war` before deploying.

**Comment by tsanah** [comment]
Many thanks, Christian!
