### ISSUE TITLE
Update TDS DOI

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds#833]
We should update the TDS DOI:

TDS: doi:10.5065/D6N014KG http://doi.org/10.5065/D6N014KG

from:

http://www.unidata.ucar.edu/software/thredds/current/tds/

to:

http://www.unidata.ucar.edu/software/tds/

as this updated url is in line with other Unidata urls, and will serve as our stable TDS landing page, whereas the other URL will change when we move to the Unidata docs domain.

Not sure who is responsible for the DOI - @ethanrd - did you mint this DOI?

**Comment by dopplershift** [comment]
I have access and I've updated.

**Comment by lesserwhirls** [comment]
awesome - thanks @dopplershift!
