### ISSUE TITLE
Aggregated dataset where there is a `scale_factor` and `add_offset` values produce incorrect values

### ISSUE THREAD

**Issue by bcalton** [Unidata/thredds#842]
If you create an aggregated dataset using NcML where the source files have a `scale_factor` and `add_offset` value, and these values are different in each file, the resulting values produced are incorrect for all but data from one of the files. 

I have a set of 7 files downloaded from ECMWF (https://rsg.pml.ac.uk/thredds/catalog-era-interim.html) that are available as individual files or as an aggregation. If you make a WCS request from the aggregated dataset you receive a different answer from the same request directed at the individual files. I think is due to way that variable attributes are handled in the aggregation process; the aggregated version takes the `scale_factor` and `add_offset` from one of the files in the aggregation and uses it for all files. This means that when the integer data values are processed, as per the netCDF conventions, they are being calculated using the wrong `scale_factor` and `add_offset` values.

This plot illustrates the issue https://plot.ly/~bac/5/

**Comment by cofinoa** [comment]
@bcalton 

For each `netcdf` element in the NcML aggregation you have add the `enhance="ScaleMissing"` to promote the data variable to the _uncompress_ status using the `scale_factor` and `add_offset` been used on each file for the data variable. 

This is example of the resulting NcML

```xml
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
  <aggregation dimName="time" type="joinExisting">
    <netcdf location="https://rsg.pml.ac.uk/thredds/dodsC/era-interim-wind/era_interim_wind_2010.nc" enhance="ScaleMissing"/>
    <netcdf location="https://rsg.pml.ac.uk/thredds/dodsC/era-interim-wind/era_interim_wind_2011.nc" enhance="ScaleMissing"/>
 </aggregation>
</netcdf>
```
Regards

P.S.: Please, next time upload also the NcML sampling file.

**Comment by cwardgar** [comment]
@cofinoa has a clever solution that works in this instance. Basically, it processes the `scale_factor` and `add_offset` attributes *before* the datasets are aggregated. To demonstrate, let's use `era_interim_wind_2010.nc` and `era_interim_wind_2011.nc` as examples. By default, you have:
```
short u10(time=2920, latitude=241, longitude=480);
:_CoordinateAxes = "time latitude longitude ";
:scale_factor = 0.0013706892469132917; // double
:add_offset = -0.6592699393500191; // double
:_FillValue = -32767S; // short
:missing_value = -32767S; // short
:units = "m s**-1";
:long_name = "10 metre U wind component";

short v10(time=2920, latitude=241, longitude=480);
:_CoordinateAxes = "time latitude longitude ";
:scale_factor = 0.001098264690401091; // double
:add_offset = 1.8468248300571433; // double
:_FillValue = -32767S; // short
:missing_value = -32767S; // short
:units = "m s**-1";
:long_name = "10 metre V wind component";
```
But if you apply `enhance="ScaleMissing"`, you get:
```
double u10(time=2920, latitude=241, longitude=480);
:_CoordinateAxes = "time latitude longitude ";
:units = "m s**-1";
:long_name = "10 metre U wind component";

double v10(time=2920, latitude=241, longitude=480);
:_CoordinateAxes = "time latitude longitude ";
:units = "m s**-1";
:long_name = "10 metre V wind component";
```
Notice that the attributes are gone (they've been applied to the data) AND the variables are now of type `double`. Pretty cool.

However, it's important to note that—in general—the structural metadata of aggregation members are [expected to be homogenous](http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/ncml/faq.html). If it helps, you can control which dataset is selected as the [prototype dataset](http://www.unidata.ucar.edu/software/thredds/current/tds/reference/ThreddsConfigXMLFile.html#Aggregation).

**Comment by bcalton** [comment]
@cofinoa @cwardgar thank you both for a swift and thorough response, worked perfectly :)
