### ISSUE TITLE
Vulnerability related to jquery

### ISSUE THREAD

**Issue by ghkostov** [Unidata/thredds#865]
js/lib/jquery-1.7.2.min.js
↳ jquery 1.7.2.min has known vulnerabilities: severity: medium; bug: 11290, summary: Selector interpreted as HTML; http://bugs.jquery.com/ticket/11290 http://research.insecurelabs.org/jquery/test/ severity: medium; issue: 2432, summary: 3rd party CORS request may execute; https://github.com/jquery/jquery/issues/2432 http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/

**Comment by cwardgar** [comment]
Closed by #954.
