### ISSUE TITLE
Address this gis.stackexchange issue

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/thredds#87]
http://gis.stackexchange.com/questions/126601/fmrc-feature-in-thredds-presents-timesteps-incorrectly

**Comment by lesserwhirls** [comment]
On it...thanks for the heads-up @rsignell-usgs! We are trying to keep an eye on the multiple locations where we get questions, but we are still trying to get used to the process.

**Comment by JohnLCaron** [comment]
i think ryan was going to reproduce?
