### ISSUE TITLE
Bug for 360_day calendar and time period edges between 29 and 30th February

### ISSUE THREAD

**Issue by glevava** [Unidata/thredds#896]
Hi, 
I encountered an issue regarding the THREDDS calendar support.
Even THREDDS is able to support 360_day calendar, it raises an `IOexception for Invalid Catalog` if the start or end coverage date time is between the 29th and 30th February.

The XML catalog is properly generate but java raises the following error when it try to read it:
`java.lang.IllegalArgumentException: Illegal base time specification: '2066-02-30' Value 30 for dayOfMonth must be in the range [1,28]`

If I manually change the date in the XML catalog to `2066-03-01` for instance, it works as expected.

**Comment by cofinoa** [comment]
@glevava, could you attach the .XML catalog file with the problematic date?

**Comment by glevava** [comment]
Hi Antonio, attached is (one of) the "affected" catalog (in txt format).

[invalid_catalog.txt](https://github.com/Unidata/thredds/files/1163637/invalid_catalog.txt)

**Comment by cofinoa** [comment]
@glevava 
Currently the XML elements in the `<timeCoverage>` doesn't support other calendars/dates/periods than the Gregorian one: 
```xml
<timeCoverage>
  <start>1980-12-01T00:00:00</start>
  <end>2066-02-30T00:00:00</end>
</timeCoverage>
...
```
A modification on the catalog builder should allow to an attribute like this: 
```xml
<timeCoverage calendar="360_day">
  <start>1980-12-01T00:00:00</start>
  <end>2066-02-30T00:00:00</end>
</timeCoverage>
```

then any date/period element refers to the calendar been specified in the attribute.

**Comment by cofinoa** [comment]
It may be also the `<addTimeCoverage>` for the server-side catalog specification should be also modified. 

Any other thoughts?

**Comment by glevava** [comment]
I manually modified the catalog to get:
```
<timeCoverage calendar="360_day">
  <start>1980-12-01T00:00:00</start>
  <end>2066-02-30T00:00:00</end>
</timeCoverage>
```
And try publication again. It fails with the same error.
