### ISSUE TITLE
Godiva2 showing dataset and variable as "undefined"  in TDS 4.6.x

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/thredds#973]
When working correctly, Godiva2 shows the dataset name and variable selected, like on this thredds 4.3.21 server:
http://geoport.whoi.edu/thredds/godiva2/godiva2.html?server=http://geoport.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd
![2017-12-12_7-49-24](https://user-images.githubusercontent.com/1872600/33886043-440bb5f6-df13-11e7-879c-1b010401174d.png)

Both dataset and variable selected show up as "undefined", however, on my thredds 4.6.10 server:
http://geoport-dev.whoi.edu/thredds/godiva2/godiva2.html?server=http://geoport-dev.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd
![2017-12-12_8-02-49](https://user-images.githubusercontent.com/1872600/33886161-a7ac4e2c-df13-11e7-9559-e0f71b48464f.png)

I notice that same problem exists on Unidata's thredds.ucar.edu 4.6.11 server as well:
http://thredds.ucar.edu/thredds/godiva2/godiva2.html?server=http://thredds.ucar.edu/thredds/wms/grib/NCEP/GFS/Global_onedeg/Best#
![2017-12-12_8-11-47](https://user-images.githubusercontent.com/1872600/33886331-3699c470-df14-11e7-8305-831b071153ab.png)

I don't know how far back this problem goes, but perhaps the whole 4.6.x line or further back than that!

Let's get this fixed!  Must be something easy!

**Comment by lesserwhirls** [comment]
Found the issue - making a PR right now.

**Comment by rsignell-usgs** [comment]
Nice!
