### ISSUE TITLE
thredds-parent 4.3.22 not on Maven Central

### ISSUE THREAD

**Issue by davidmoten** [Unidata/thredds#98]
netcdf-4.3.22 is deployed to Maven Central at http://search.maven.org/#browse%7C2058465994 but its dependency thredds-parent-4.3.22 is not. Can this be rectified please?

**Comment by cwardgar** [comment]
Hi David,

Publishing to Maven Central is a tedious process for us, so I'm not sure we're going to do that for an old release. However, we upload all of our artifacts to our own public repository [1]. Is there any reason you can't use that in your Maven build?

[1] http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/JarDependencies.html

**Comment by davidmoten** [comment]
Thanks, am now using your repo.
Dave
