### ISSUE TITLE
How to get one dimensional time for grib2 FeatureCollection aggregation?

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/thredds#986]
I created a grib aggregation using `featureCollection` here:
https://js-170-55.jetstream-cloud.org/thredds/dodsC/grib/CFSr_v2/tmp2m.html
but it ends up with two dimensional time (1336x6), instead of the 8016 time steps I expected.

When I use convert the grb2 files to netcdf using `wgrib2`, I get the uniform, monotonic 1D time coordinate I expect, with 8016 values.   

Right now I'm using this `featureCollection` specification:

```xml
<featureCollection name="CFSr_v2" featureType="GRIB2" path="grib/CFSr_v2/tmp2m">
  <metadata inherited="true">
     <serviceName inherited="true">gridServices</serviceName>
     <documentation type="summary">NCEP CFSr_v2 Model </documentation>
  </metadata>
  <collection name="cvsr-v2-tmp2m" spec="/data/CFSR/2017/tmp2m.cdas1.*\.grb2$"/>
 </featureCollection>
```
How can I tell the `featureCollection` to do the same thing as `wgrib2` and generate a 1D time coordinate?

**Comment by lesserwhirls** [comment]
Try adding a `<gribConfig>` element, like this:


```java
<featureCollection name="CFSr_v2" featureType="GRIB2" path="grib/CFSr_v2/tmp2m">
  <metadata inherited="true">
     <serviceName inherited="true">gridServices</serviceName>
     <documentation type="summary">NCEP CFSr_v2 Model </documentation>
  </metadata>
  <collection name="cvsr-v2-tmp2m" spec="/data/CFSR/2017/tmp2m.cdas1.*\.grb2$"/>
  <gribConfig datasetTypes="TwoD Best" />
</featureCollection>
```

I think you are seeing the TwoD now. Let’s see what happens with that.

**Comment by cofinoa** [comment]
@rsignell-usgs wgrib2 it's ignoring that the grib2 files reprents 2D time coordinates. 

The original grib2 files are 6-hourly forecast_reference_time (reftime dimension) and 1-hourly (6 steps) forecast_period (time dimension)
http://js-170-55.jetstream-cloud.org/thredds/dodsC/data/CFSR/2017/tmp2m.cdas1.201711.grb2.html

It may be one possible solution it's to split the grib2 per 1 forecast_reference_time havinf only forecast_period .

**Comment by rsignell-usgs** [comment]
@lesserwhirls , I tried specifying:
```
  <gribConfig datasetTypes="Best" />
```
in the catalog and now I only see one dataset here (no more raw datasets):
https://js-170-55.jetstream-cloud.org/thredds/catalog/grib/CFSr_v2/tmp2m/catalog.html

Unfortunately, it still presents the 2D dataset, with two time dimensions on the dependent variable:
`Temperature_height_above_ground`


@cofinoa, exactly right -- these forecasts contain no overlapping time periods, so I don't know why best time series isn't working.   Here's what they look like in wgrib2:
```
25:27809669:d=2017010200:TMP:2 m above ground:1 hour fcst:
26:28973871:d=2017010200:TMP:2 m above ground:2 hour fcst:
27:30135542:d=2017010200:TMP:2 m above ground:3 hour fcst:
28:31295925:d=2017010200:TMP:2 m above ground:4 hour fcst:
29:32444030:d=2017010200:TMP:2 m above ground:5 hour fcst:
30:33594883:d=2017010200:TMP:2 m above ground:6 hour fcst:
31:34748176:d=2017010206:TMP:2 m above ground:1 hour fcst:
32:35913730:d=2017010206:TMP:2 m above ground:2 hour fcst:
33:37079295:d=2017010206:TMP:2 m above ground:3 hour fcst:
34:38245853:d=2017010206:TMP:2 m above ground:4 hour fcst:
35:39403451:d=2017010206:TMP:2 m above ground:5 hour fcst:
36:40565679:d=2017010206:TMP:2 m above ground:6 hour fcst:
37:41730990:d=2017010212:TMP:2 m above ground:1 hour fcst:
38:42907080:d=2017010212:TMP:2 m above ground:2 hour fcst:
39:44081414:d=2017010212:TMP:2 m above ground:3 hour fcst:
40:45256163:d=2017010212:TMP:2 m above ground:4 hour fcst:
41:46418794:d=2017010212:TMP:2 m above ground:5 hour fcst:
42:47584124:d=2017010212:TMP:2 m above ground:6 hour fcst:
43:48749083:d=2017010218:TMP:2 m above ground:1 hour fcst:
44:49921321:d=2017010218:TMP:2 m above ground:2 hour fcst:
45:51088304:d=2017010218:TMP:2 m above ground:3 hour fcst:
46:52253224:d=2017010218:TMP:2 m above ground:4 hour fcst:
47:53405193:d=2017010218:TMP:2 m above ground:5 hour fcst:
48:54559738:d=2017010218:TMP:2 m above ground:6 hour fcst:
49:55715537:d=2017010300:TMP:2 m above ground:1 hour fcst:
```

**Comment by rsignell-usgs** [comment]
Hmm, it seems these folks are serving the same grib2 files via thredds:
https://rda.ucar.edu/thredds/catalog/aggregations/g/ds094.1/ds094.1-2017/catalog.html
so perhaps I can just get their catalogs/configuration to see what I'm doing wrong.  

@lesserwhirls, so you know who maintains that RDA thredds server?

**Comment by lesserwhirls** [comment]
Let's try one last thing - can you add the following:

 ~~~xml
<featureCollection name="CFSr_v2" featureType="GRIB2" path="grib/CFSr_v2/tmp2m">
  <metadata inherited="true">
     <serviceName inherited="true">gridServices</serviceName>
     <documentation type="summary">NCEP CFSr_v2 Model </documentation>
  </metadata>
  <collection name="cvsr-v2-tmp2m"
              spec="/data/CFSR/2017/tmp2m.cdas1.*\.grb2$"/
              timePartition="file"
              dateFormatMark="yyyyMM#.grb2#">
  <gribConfig datasetTypes="TwoD Best Files" />
</featureCollection>
~~~

John used to maintain the RDA as he was scaling the GRIB featureCollection. The latest catalog we have is [here](https://github.com/Unidata/TdsConfig/blob/master/rdavm/catalog_ds094.1.xml)l; however, this is a 5.0 catalog, so it's not drop-and-go with 4.6 due to changes in default values.

**Comment by rsignell-usgs** [comment]
Woohoo!!
https://js-170-55.jetstream-cloud.org/thredds/dodsC/grib/CFSr_v2/tmp2m/Best.html

So was it the `timePartition`, the `dateFormatMark`, or both?

**Comment by rsignell-usgs** [comment]
Wow, it was `timePartition="file"` that was the key.  So my catalog now reads:

```xml
 <featureCollection name="CFSr_v2" featureType="GRIB2" path="grib/CFSr_v2/tmp2m"
>
  <metadata inherited="true">
     <serviceName inherited="true">gridServices</serviceName>
     <documentation type="summary">NCEP CFSr_v2 Model </documentation>
  </metadata>
  <collection name="cfsr-v2-tmp2m"
      spec="/data/CFSR/2017/tmp2m.cdas1.*\.grb2$"
      timePartition="file" />
  <gribConfig datasetTypes="Best" />
  <update startup="always"/>
 </featureCollection>
```

**Comment by lesserwhirls** [comment]
Great! The `dateFormatMark` may speed up things a bit by not requiring all of the GRIB metadata to be read in to construct the time partition (especially in large collections).

**Comment by rsignell-usgs** [comment]
In this case, there are 720 grib records per grib file, so it probably wouldn't speed things up **that** much, right?

**Comment by lesserwhirls** [comment]
YMMV. ¯\_(ツ)_/¯
